IF
  Global("cd_do_dlg_stuff","LOCALS",1)
THEN
  RESPONSE #100
    MoveToPointNoInterrupt([681.588])
    SetGlobal("cd_do_dlg_stuff","LOCALS",2)
END    

IF
  Global("cd_do_dlg_stuff","LOCALS",2)
THEN
  RESPONSE #100
    FaceObject("bddelend")
    ActionOverride("bddelend",FaceObject("bdbartle"))
    SetGlobalTimer("bd_bartleby_timer","BD0108",ONE_MINUTE)
    SetGlobal("cd_do_dlg_stuff","LOCALS",3)
END  