COPY_EXISTING ~spell.ids~ ~override~
  REPLACE_EVALUATE ~^\([0-9]+\)\([ %TAB%]+\)\([^ %TAB%%LNL%%MNL%%WNL%]+\)~ BEGIN
    SET number = 0
    PATCH_IF MATCH1 >= 4000 BEGIN SPRINT prefix spcl SET number = MATCH1 - 4000 END ELSE 
    PATCH_IF MATCH1 >= 3000 BEGIN SPRINT prefix spin SET number = MATCH1 - 3000 END ELSE 
    PATCH_IF MATCH1 >= 2000 BEGIN SPRINT prefix spwi SET number = MATCH1 - 2000 END ELSE 
    PATCH_IF MATCH1 >= 1000 BEGIN SPRINT prefix sppr SET number = MATCH1 - 1000 END
    SPRINT ~%MATCH3%~ ~%prefix%%number%~
  END ~%MATCH1%%MATCH2%%MATCH3%~
  BUT_ONLY