/////                                                  \\\\\
///// string fixes                                     \\\\\
/////                                                  \\\\\

// string fixes, processed automatically if tra file exists
LAUNCH_ACTION_FUNCTION cd_string_set_from_tra
  STR_VAR input_tra  = EVAL ~eefixpack/languages/%LANGUAGE%/fixes_%game%.tra~ // tra file to process
          output_tph = EVAL ~weidu_external/eefixpack/fixes_%game%.tph~ // tph being built; use weidu_external for this
END

/////                                                  \\\\\
///// ids/2da fixes                                    \\\\\
/////                                                  \\\\\

INCLUDE ~eefixpack/files/tph/clswpbon.tpa~ // tbd, cam: fix non-prof penalties for shadowdancers, mage-thieves

/////                                                  \\\\\
///// mass copy/includes actions                       \\\\\
/////                                                  \\\\\

COPY_EXISTING ~eefixpack/files/bam/ixbow04.bam~  ~override~ // tbd, cam: fix light crossbow BAM
              ~eefixpack/files/2da/clabmo02.2da~ ~override~ // tbd, cam: borked kit ability table, dark moon monk
              ~eefixpack/files/2da/clabmo03.2da~ ~override~ // tbd, cam: borked kit ability table, sun soul monk
              ~eefixpack/files/2da/clabrn02.2da~ ~override~ // tbd, cam: borked kit ability table, archer
              ~eefixpack/files/bam/mdem~         ~override~ // tbd, sam.: merging four-frame animations to fix issues, demogorgon
              ~eefixpack/files/bam/mdr1~         ~override~ // tbd, sam.: merging four-frame animations to fix issues, dragon red
              ~eefixpack/files/bam/mdr2~         ~override~ // tbd, sam.: merging four-frame animations to fix issues, dragon black
              ~eefixpack/files/bam/mdr3~         ~override~ // tbd, sam.: merging four-frame animations to fix issues, dragon silver
              ~eefixpack/files/bam/mwyv~         ~override~ // tbd, sam.: merging four-frame animations to fix issues, wyvern big

// tbd, sam.
// merging multi-part area animations to eliminate issues
ACTION_BASH_FOR ~eefixpack/files/bam/area_anim~ ~^.+\.bam$~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%BASH_FOR_RES%.bam~ BEGIN
    COPY ~eefixpack/files/bam/area_anim/%BASH_FOR_RES%.bam~ ~override~
  END
END  

/////                                                  \\\\\
///// dialogue fixes                                   \\\\\
/////                                                  \\\\\

COMPILE ~eefixpack/files/d/%game%_core_fixes.d~ // misc dialogue fixes

/////                                                  \\\\\
///// script fixes                                     \\\\\
/////                                                  \\\\\

// ie-5948, cam
// Generic cleric AI script can hang
COPY_EXISTING ~pries14a.bcs~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY ~\(IF[ %TAB%%LNL%%MNL%%WNL%]See(NearestEnemyOf(Myself))[ %TAB%%LNL%%MNL%%WNL%]+HaveSpell(CLERIC_CONFUSION)[ %TAB%%LNL%%MNL%%WNL%]+THEN[ %TAB%%LNL%%MNL%%WNL%]+RESPONSE #100[ %TAB%%LNL%%MNL%%WNL%]\)\(END\)~
      ~\1 Spell(NearestEnemyOf(Myself),CLERIC_CONFUSION) \2~
END
BUT_ONLY



// ie-5281, cam
// bp2: Golem fight is well-nigh impossible on Legacy of Bhaal difficulty
COPY_EXISTING ~ohb_t302.bcs~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY ~LevelGT(Myself,10)~ ~HasItem("immune1",Myself)~
  END
  BUT_ONLY



// tbd, cam (two issues here, see bysohim in main d compile)
// Yoshimo Should Have Follow-Up Banters with the PC
EXTEND_BOTTOM ~yoshimo.bcs~ ~eefixpack/files/baf/yoshimo_banter.baf~ // add script prompt for third banter


/////                                                  \\\\\
///// area fixes                                       \\\\\
/////                                                  \\\\\

/////                                                  \\\\\
///// creature file fixes                              \\\\\
/////                                                  \\\\\

// ie-3658, cam
// Jassar (and others) shouldn't drop identified magic armor
COPY_EXISTING ~ohbgit01.cre~ ~override~
              ~ohbthr01.cre~ ~override~
              ~ohdcru04.cre~ ~override~
              ~ohdlufpl.cre~ ~override~
              ~ohnvgc.cre~   ~override~
              ~ohrjassa.cre~ ~override~
  REPLACE_CRE_ITEM ~plat23~ #0 #0 #0 ~NONE~ ~ARMOR~ // replace plat19, the special 0-lore armor from wish with identical plate with lore



// BGCS-469, luke
// Lizard Men should be flagged as 'LIZARDMAN'
WITH_SCOPE BEGIN
  COPY_EXISTING_REGEXP ~ohbliz0[1-3].cre~ ~override~ // The Black Pits 2
    WRITE_BYTE 0x272 IDS_OF_SYMBOL ("RACE" "LIZARDMAN")
  BUT_ONLY_IF_IT_CHANGES
END

/////                                                  \\\\\
///// item file fixes                                  \\\\\
/////                                                  \\\\\

// luke
// Mis-indexed effects
WITH_SCOPE BEGIN
  COPY_EXISTING ~hamm06.itm~ ~override~ // Dwarven Thrower +3
                ~staf01.itm~ ~override~ // Quarterstaff
    LAUNCH_PATCH_FUNCTION ~FJ_SPL_ITM_REINDEX~ END
  BUT_ONLY_IF_IT_CHANGES
END

// luke
// – Neera's Staff +1 => When the staff strikes a target, there is a 10% chance that either the target or the wielder will take 1 point of fire damage
//// This isn't implemented properly since the two op12 effects share the same probability range... Also, whilw we're at it, make sure it's 10% chance and not 11% chance...
WITH_SCOPE BEGIN
  COPY_EXISTING ~stafn1.itm~ ~override~ // Neera's Staff +1
    LAUNCH_PATCH_FUNCTION ~ALTER_EFFECT~ INT_VAR ~check_globals~ = 0 ~multi_match~ = 1 ~match_opcode~ = 12 ~probability1~ = 9 END // 10% chance (target)
    LAUNCH_PATCH_FUNCTION ~ALTER_EFFECT~ INT_VAR ~check_globals~ = 0 ~match_opcode~ = 12 ~match_probability1~ = 10 ~probability2~ = 10 ~probability1~ = 19 END // 10% chance (wielder)
  BUT_ONLY_IF_IT_CHANGES
END

// tbd, cam
// fixing paperdoll animations
ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_paperdoll_animations BEGIN 
  misc9q   => sc // Habib's Mighty Scimitar uses a katana paperdoll animation instead of scimitar 
  rodsword => fs // The Flaming Long Sword +1 from the Rod of Lordly Might (rodsword) should use the flaming sword animation
  sw1h66   => ss // Yamato +4 uses a scimitar animation instead of short sword (like other wakizashi) 
  sw1h67   => s1 // Usuno's Blade uses a scimitar animation instead of long sword (like other ninja-to) 
  sw1h68a  => s2 // The undroppable copy of the Spectral brand has no animation 
END

ACTION_PHP_EACH cd_paperdoll_animations AS item => anim BEGIN

  COPY_EXISTING ~%item%.itm~ ~override~
    WRITE_ASCIIE 0x22 "%anim%" #2

END

/////                                                  \\\\\
///// spell fixes                                      \\\\\
/////                                                  \\\\\

// ie-5931, cam
// Stoneskin from Demogorgon & Melissan cannot be breached
COPY_EXISTING ~melstone.spl~ ~override~
  WRITE_BYTE 0x27 7 // change secondary to Combat Protections
  BUT_ONLY



// luke
// Mis-indexed effects
WITH_SCOPE BEGIN
  COPY_EXISTING ~ohbwi302.spl~ ~override~ // Remove Magic
                ~ohbwi304.spl~ ~override~ // Fireball
    LAUNCH_PATCH_FUNCTION ~FJ_SPL_ITM_REINDEX~ END
  BUT_ONLY_IF_IT_CHANGES
END



// luke
// Mimic Glue should not set the GREASE stat
WITH_SCOPE BEGIN
  COPY_EXISTING ~%MIMIC_GLUE%.spl~ ~override~ // Mimic Glue
    LAUNCH_PATCH_FUNCTION "ALTER_EFFECT" INT_VAR "match_opcode" = 158 "opcode" = 215 "parameter2" = 1 STR_VAR "resource" = "GREASED" END // Grease overlay => Play visual effect, Mode: Over target (attached)
  BUT_ONLY_IF_IT_CHANGES
END



// luke
// Spirit Fire => should not interact with spell protections
// As a result, do not use "bddoom.spl" (since its effects are coded as `power=1`)
WITH_SCOPE BEGIN
  INCLUDE "eefixpack/files/tph/luke/cleric_spirit_fire.tph"
  LAUNCH_ACTION_FUNCTION "CLERIC_SPIRIT_FIRE" END
END



// luke
// Nature's Beauty – permanent blindness (until dispelled)
// 1) Timing Mode 1 will permanently set the creature's STATE_BLIND flag, leaving no removable effect.
// 2) Related: the -4 penalty to AC and THAC0 are apparently tied to the effect (op74), not STATE_BLIND.
// As a result, we suggest to stick with a limited `timing_mode` and set `duration` to a very high random value (max signed value...?).
// Additionally, this spell should only affect HUMANOID (there are a lot of unnatural creatures that are immune to it via op206; also, it is intended, right...?)
WITH_SCOPE BEGIN
  COPY_EXISTING ~%CLERIC_NATURE_BEAUTY%.spl~ ~override~
    LPF "ADD_SPELL_EFFECT" INT_VAR "insert_point" = 0 "opcode" = 324 "target" = 2 "power" = 7 "parameter2" = 6 "resist_dispel" = BIT1 STR_VAR "resource" = "%DEST_RES%" END // Immunity to resource and message (GENERAL != HUMANOID)
    LAUNCH_PATCH_FUNCTION "ALTER_EFFECT" INT_VAR "match_opcode" = 74 "timing" = 0 "duration" = 0x7FFFFFFF END // Blindness
  BUT_ONLY_IF_IT_CHANGES
END

/////                                                  \\\\\
///// store fixes                                      \\\\\
/////                                                  \\\\\

/////                                                  \\\\\
///// misc/other fixes                                 \\\\\
/////                                                  \\\\\

/////                                                  \\\\\
///// final batch of INCLUDEs and cross-patching       \\\\\
/////                                                  \\\\\

INCLUDE ~eefixpack/files/tph/tbd_bg2ee_probabilities.tph~ // tbd, cam: probability fixes
INCLUDE "%MOD_FOLDER%/files/tph/dw_fixes.tph" // tbd, davidw:  318/324 immunity, 109/175/185 disentanglement, and more