/////                                                  \\\\\
///// string fixes                                     \\\\\
/////                                                  \\\\\

// string fixes, processed automatically if tra file exists
LAUNCH_ACTION_FUNCTION cd_string_set_from_tra
  STR_VAR input_tra  = EVAL ~eefixpack/languages/%LANGUAGE%/fixes_%game%.tra~ // tra file to process
          output_tph = EVAL ~weidu_external/eefixpack/fixes_%game%.tph~ // tph being built; use weidu_external for this
END
ACTION_IF game_contains_sod BEGIN
  LAUNCH_ACTION_FUNCTION cd_string_set_from_tra
    STR_VAR input_tra  = EVAL ~eefixpack/languages/%LANGUAGE%/fixes_%game%_sod.tra~ // tra file to process
            output_tph = EVAL ~weidu_external/eefixpack/fixes_%game%_sod.tph~ // tph being built; use weidu_external for this
  END
END

/////                                                  \\\\\
///// ids/2da fixes                                    \\\\\
/////                                                  \\\\\

/////                                                  \\\\\
///// mass copy/includes actions                       \\\\\
/////                                                  \\\\\

COPY_EXISTING ~eefixpack/files/bam/ixbow04.bam~  ~override~ // tbd, cam: fix light crossbow BAM
              ~eefixpack/files/2da/clabmo02.2da~ ~override~ // tbd, cam: borked kit ability table, dark moon monk
              ~eefixpack/files/2da/clabmo03.2da~ ~override~ // tbd, cam: borked kit ability table, sun soul monk
              ~eefixpack/files/2da/clabrn02.2da~ ~override~ // tbd, cam: borked kit ability table, archer
              ~eefixpack/files/bam/mdem~         ~override~ // tbd, sam.: merging four-frame animations to fix issues, demogorgon
              ~eefixpack/files/bam/mwyv~         ~override~ // tbd, sam.: merging four-frame animations to fix issues, wyvern big

ACTION_IF game_contains_sod BEGIN

  COPY_EXISTING ~eefixpack/files/bam/mdr1~         ~override~ // tbd, sam.: merging four-frame animations to fix issues, dragon red
  
END

// tbd, sam.
// merging multi-part area animations to eliminate issues
ACTION_BASH_FOR ~eefixpack/files/bam/area_anim~ ~^.+\.bam$~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%BASH_FOR_RES%.bam~ BEGIN
    COPY ~eefixpack/files/bam/area_anim/%BASH_FOR_RES%.bam~ ~override~
  END
END  

/////                                                  \\\\\
///// dialogue fixes                                   \\\\\
/////                                                  \\\\\

COMPILE ~eefixpack/files/d/%game%_core_fixes.d~ // misc dialogue fixes

ACTION_IF game_contains_sod BEGIN
  COMPILE ~eefixpack/files/d/%game%_sod_core_fixes.d~ // misc dialogue fixes
END

/////                                                  \\\\\
///// script fixes                                     \\\\\
/////                                                  \\\\\

// tbd, cam
// can't reach the required deathcount for comments on lower difficulty since too many 'Followers' despawn
COPY_EXISTING ~bd0120.bcs~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY ~NumDeadGT("Followers",4)~ ~NumDeadGT("Followers",2)~
  END
  BUT_ONLY IF_EXISTS // sod



// tbd, cam
// referring to wrong DV for Halatathlaer
// wrong variable scope for timer
COPY_EXISTING ~bd5300.bcs~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY ~DisplayStringHead("bdhalat")~ ~DisplayStringHead("bdhalata")~ // script has a createcreature bdhalat, so need to extra bit of trigger to match
    REPLACE_TEXTUALLY ~"bd_sdd350b_ot_timer","bd2000"~ ~"bd_sdd350b_ot_timer","bd5300"~ // wrong variable scope
  END
  BUT_ONLY IF_EXISTS // sod




// tbd, cam
// referring to wrong DV for Imoen
COPY_EXISTING ~bd6200.bcs~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY ~"bdimoen"~ ~"imoen"~
  END
  BUT_ONLY IF_EXISTS // sod




// tbd, cam
// referring to wrong DV for Corwin
COPY_EXISTING ~bd7300.bcs~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY ~"bdcorwin"~ ~"corwin"~
  END
  BUT_ONLY IF_EXISTS // sod




// tbd, cam
// possibly missing Minsc-rasaad banter due to typo
COPY_EXISTING ~bdminsc.bcs~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY ~"rasaad'"~ ~"rasaad"~
  END
  BUT_ONLY IF_EXISTS // sod
  
  

// tbd, cam
// spike trigger is a little too happy to murderize everyone, swap trigger
COPY_EXISTING ~bdlever2.bcs~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY ~WalkedToTrigger~ ~Clicked~
  END
  BUT_ONLY IF_EXISTS // sod




// tbd, cam
// sod imoen missing xp-matching scripting, among other things
ACTION_IF game_contains_sod BEGIN
  EXTEND_BOTTOM ~imoen.bcs~ ~eefixpack/files/baf/sod_imoen_bottom.baf~
END



// tbd, cam
// bad string refs for AI scripting
COPY_EXISTING ~bdimoenc.bcs~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY ~DisplayString(Myself,46150)~ ~DisplayString(Myself,31249)~ // *quaffs a potion*
  END
  BUT_ONLY
  
COPY_EXISTING ~bdeldotc.bcs~ ~override~
              ~bdgarrcc.bcs~ ~override~
              ~bdgarric.bcs~ ~override~
              ~bdkivanc.bcs~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY ~DisplayString(Myself,56560)~ ~DisplayString(Myself,31249)~ // *quaffs a potion*
  END
  BUT_ONLY
 
SET use_wand = RESOLVE_STR_REF (@100)
COPY_EXISTING ~bddefai.bcs~  ~override~
              ~bddynac.bcs~  ~override~
              ~bdedwinc.bcs~ ~override~
              ~bdxzarc.bcs~  ~override~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY ~DisplayString(Myself,66959)~ ~DisplayString(Myself,%use_wand%)~ // *uses a wand*
  END
  BUT_ONLY

/////                                                  \\\\\
///// area fixes                                       \\\\\
/////                                                  \\\\\

/////                                                  \\\\\
///// creature file fixes                              \\\\\
/////                                                  \\\\\

// tbd, cam
// crusaders with the wrong DV
COPY_EXISTING ~bdcrus21.cre~ ~override~
              ~bdcrus22.cre~ ~override~
              ~bdcrus6d.cre~ ~override~
              ~bdcrus7d.cre~ ~override~
              ~bdcrus8d.cre~ ~override~
              ~bdcrus9d.cre~ ~override~
  WRITE_ASCIIE 0x280 ~%SOURCE_RES%~ #32 // was bdcrus20
  BUT_ONLY IF_EXISTS // sod

/////                                                  \\\\\
///// item file fixes                                  \\\\\
/////                                                  \\\\\

/////                                                  \\\\\
///// spell fixes                                      \\\\\
/////                                                  \\\\\

/////                                                  \\\\\
///// store fixes                                      \\\\\
/////                                                  \\\\\

/////                                                  \\\\\
///// misc/other fixes                                 \\\\\
/////                                                  \\\\\

/////                                                  \\\\\
///// final batch of INCLUDEs and cross-patching       \\\\\
/////                                                  \\\\\

INCLUDE "%MOD_FOLDER%/files/tph/dw_fixes.tph" // tbd, davidw:  318/324 immunity, 109/175/185 disentanglement, and more