// spell state ends up in wrong place, include thac0 penalty as part of fear
OUTER_SET panic_immunity = IDS_OF_SYMBOL (~splstate~ ~PANIC_IMMUNITY~)
COPY_EXISTING ~spin536.spl~  ~override~ // (spl) Fear - causes fear - unknown long effect - portrait icon 36 - plays sound EFF_E05 [has expiry sound, thac0 penalty attached to fear]
              ~spin772.spl~  ~override~ // (spl) [HELL_FEAR] - causes fear - unknown long effect - portrait icon 36 - plays sound EFF_E05 [has expiry sound, thac0 penalty attached to fear]
              ~spin882.spl~  ~override~ // (spl) Vampire Fear - causes fear - portrait icon 36 - unknown long effect - portrait icon 36 [has expiry sound, thac0 penalty attached to fear]
              ~spin895.spl~  ~override~ // (spl) Dragon Fear - causes fear - unknown long effect - portrait icon 36 - plays sound EFF_E05 [has expiry sound, thac0 penalty attached to fear]
  LPF DELETE_EFFECT INT_VAR match_opcode = 324 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 24 opcode = 324 parameter1 = panic_immunity parameter2 = 110 timing = 0 duration = 0 resist_dispel = 0 STR_VAR insert = first resource = EVAL ~%SOURCE_RES%~ END

/*
When building the cdcurXXX.spl there is a list of skipped resources. Resources are generally skipped
because they only cause the main effect without additional long-term effects, or with soemthing that
can be removed like a portrait icon. In short, they have effects that can be reversed without a 321.

Sleep has additional skips, mainly because it doubles as the unconsciousness effect for wing buffets.

*/

COPY_EXISTING ~spmindat.vvc~ ~override/cdfeeble.vvc~ // create new vvc that plays spmindat for feeblemind
              ~spmindat.vvc~ ~override/cdstun.vvc~   // create new vvc that plays spmindat for stun

/////                                                  \\\\\
///// berserk                                          \\\\\
/////                                                  \\\\\

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur4.spl~
  PATCH_FOR_EACH res IN
//              ~berserk.itm~  ~override~ // <Invalid Strref -1> - causes berserk
//              ~blun09.itm~   ~override~ // Kiel's Morning Star +3 - causes berserk
    spin117 // (spl) Berserk - cures fear - causes berserk - [Minsc's berserk comes with many additional bonuses]
//              ~sw1h19.itm~   ~override~ // The Vampire's Revenge +1 - causes berserk
//              ~sw2h03.itm~   ~override~ // Cursed Berserking Sword +3 - causes berserk
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END

COPY_EXISTING ~bpdispel.spl~ ~override~ // <Invalid Strref -1> - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun
              ~cdhgtrl.spl~  ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtorgal.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtrlblz.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~ohsmode1.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohsmode4.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohtyr1.spl~   ~override~ // Exaltation - cures berserk - cures confusion - cures drunkenness - cures feeblemind - cures fear - cures sleep
              ~trollreg.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
  LPF cd_apply_batch STR_VAR array_name = cd_cure_berserk END
  BUT_ONLY

/////                                                  \\\\\
///// blind                                            \\\\\
/////                                                  \\\\\

// change wand of glitterdust to just cast the spell
COPY_EXISTING ~ohdwand1.itm~ ~override~ // Wand of Glitterdust - cures invisibility - causes blind - unknown long effect - unknown long effect - plays sound EFF_E07
  LPF DELETE_EFFECT END // delete existing effects
  LPF ALTER_HEADER INT_VAR range = 30 primary = 0 secondary = 0 projectile = 1 END
  LPF ADD_ITEM_EFFECT INT_VAR opcode = 148 target = 1 parameter1 = 10 timing = 1 STR_VAR resource = spwi224 END

// chromatic orb blinds at levels 1 and 4; don't want to roll back entire spell for two levels of blind so we subspell it
COPY_EXISTING ~spdr101.spl~  ~override~ // Chromatic Orb (druid)
              ~spwi118.spl~  ~override~ // Chromatic Orb (arcane)
  LPF DELETE_EFFECT INT_VAR match_opcode = 74 END // delete blind effect from headers 0 and 3
  LPF DELETE_EFFECT INT_VAR header = 0 match_opcode = 139 END // uses strref 14674 "blinded" on header 0
  LPF DELETE_EFFECT INT_VAR header = 3 match_opcode = 139 END // uses strref 14674 "blindness: on header 3
  LPF ALTER_EFFECT INT_VAR header = 0 match_opcode = 174 match_timing = 4 opcode = 146 parameter2 = 2 timing = 1 duration = 0 STR_VAR match_resource = eff_e05 resource = spwi118a END // change expiry sounds to spell casts
  LPF ALTER_EFFECT INT_VAR header = 3 match_opcode = 174 match_timing = 4 opcode = 146 parameter2 = 2 timing = 1 duration = 0 STR_VAR match_resource = eff_e05 resource = spwi118d END // change expiry sounds to spell casts
  
// create blind subspells for chromatic orb 
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/spwi118a.spl~ // create blind subspell for header 0 
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 74 target = 2 duration = 6 END // add blind effect
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 139 target = 2 parameter1 = 14674 timing = 1 END // add blinded string
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 174 target = 2 parameter1 = 10 timing = 4 duration = 6 STR_VAR resource = eff_e05 END // add expiry sound
COPY_EXISTING ~spwi118a.spl~ ~override/spwi118d.spl~ // create blind subspell for header 3 
  LPF ALTER_EFFECT INT_VAR match_duration = 6 duration = 60 END

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur75.spl~
  PATCH_FOR_EACH res IN
//              ~chalcy2.itm~  ~override~ // The Shadow's Blade +3 - causes blind
//              ~gorwom4.itm~  ~override~ // Drow Flail +3 - causes blind - unknown long effect - unknown long effect
    halb06 // (itm) Blackmist +4 - causes blind [has expiry sound]
//              ~ohbwfog.spl~  ~override~ // I need rings, wands, and amulets. What do you have for sale? - causes blind - unknown long effect - unknown long effect
//              ~ohdwand1.itm~ ~override~ // Wand of Glitterdust - changed to cast spwi224 directly, above
//              ~ohrblind.spl~ ~override~ // <Invalid Strref -1> - causes blind
    ohrdark // (spl) Darkness, 15' Radius - causes blind - plays sound EFF_E06 [expiry sound]
//              ~spcl239a.spl~ ~override~ // <Invalid Strref -1> - causes blind
    spdm101 // (spl) Blindness - causes blind - plays sound EFF_E07 [expiry sound]
//              ~spdr101.spl~  ~override~ // Chromatic Orb - has expiry sound for blind, which is shunted into subspell above
//              ~spin595.spl~  ~override~ // Yellow Dragon Scorching Sand - causes blind - unknown long effect
//              ~spin878.spl~  ~override~ // Level Drain - causes blind - causes level drain - unknown long effect
//              ~spin893.spl~  ~override~ // Shadow Dragon Breath - causes blind - causes level drain - unknown long effect
//              ~spin929.spl~  ~override~ // Mist Ball - causes blind - unknown long effect
//              ~spin931.spl~  ~override~ // Sooty Ball - causes blind - unknown long effect
//              ~sppr614a.spl~ ~override~ // <Invalid Strref -1> - causes blind
//              ~sppr614b.spl~ ~override~ // <Invalid Strref -1> - causes blind
//              ~sppr704.spl~  ~override~ // Nature's Beauty - causes blind
//              ~sppr707b.spl~ ~override~ // <Invalid Strref -1> - causes blind
    spwi106 // Blindness - causes blind - plays sound EFF_E07 [expiry sound]
//              ~spwi118.spl~  ~override~ // Chromatic Orb - has expiry sound for blind, which is shunted into subspell above
    spwi118a // new chromatic orb subspell with blindness expiry sound (for spwi118, spdr101)
    spwi118d // new chromatic orb subspell with blindness expiry sound (for spwi118, spdr101)
    spwi224 // (spl) Glitterdust - cures invisibility - causes blind [expiry sound]
//              ~spwi714.spl~  ~override~ // Prismatic Spray - causes blind - causes feeblemind - unknown long effect
    spwi815 // (spl) Power Word, Blind - causes blind [expiry sound]
    spwi958 // (spl) Power Word, Blind - causes blind [expiry sound]
    spwm178 // Blindness - causes blind  [expiry sound]
//              ~sw1h51.itm~   ~override~ // Celestial Fury +3 - causes blind - causes stun - unknown long effect
//              ~wand19.itm~   ~override~ // Wand of Cursing - causes blind & deafness & silence - has expiry sound, but for all combined effects
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END

COPY_EXISTING ~amsoul01.itm~ ~override~ // Malla's Soul Stone - cures blind - cures deafness - cures disease - cures poison
              ~bhaal1a.spl~  ~override~ // Mass Healing - cures blind - cures deafness - cures disease - cures drunkenness - cures poison
              ~bpdispel.spl~ ~override~ // <Invalid Strref -1> - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun
              ~cdhgtrl.spl~  ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtorgal.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtrlblz.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~devaheal.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~ohbbclt1.spl~ ~override~ // <Invalid Strref -1> - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~ohsmode1.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohsmode4.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~senspihe.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spin201.spl~  ~override~ // Neutralize Poison - cures blind - cures deafness - cures disease - cures poison
              ~spin679.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spin699.spl~  ~override~ // Healing Lick - cures blind - cures deafness - cures disease - cures poison
              ~spin711.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spin734.spl~  ~override~ // Wish - cures blind - cures deafness - cures disease - cures drunkenness - cures poison
              ~sppr317.spl~  ~override~ // Cure Disease - cures blind - cures deafness - cures disease - cures feeblemind
              ~sppr404.spl~  ~override~ // Neutralize Poison - cures blind - cures deafness - cures disease - cures poison
              ~sppr607.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spwish28.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spwm168.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~trollreg.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
  LPF cd_apply_batch STR_VAR array_name = cd_cure_blind END
  BUT_ONLY

/////                                                  \\\\\
///// confusion                                        \\\\\
/////                                                  \\\\\

// immune to confusion, but missing spconfus immunity
COPY_EXISTING ~ohhgmum.cre~  ~override~ // greater mummy - immune to fear - immune to confusion
              ~ohhraffi.cre~ ~override~ // raffiyah - immune to fear - immune to confusion
  LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 101 match_parameter2 = 128 opcode = 296 parameter2 = 0 STR_VAR resource = spconfus END
  BUT_ONLY

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur242.spl~
  PATCH_FOR_EACH res IN
    bdsha01a // (spl) <Invalid Strref -1> - causes confusion - plays animation SPCONFUS - portrait icon 3
    dwfpdgcn // (spl) <Invalid Strref -1> - causes confusion - portrait icon 47 - plays sound EFF_E05 - plays animation SPCONFUS
//              ~magiconf.itm~ ~override~ // Ghoul hand - causes confusion - unknown long effect - portrait icon 3
    misc3m // (itm) Harp of Discord - causes confusion - plays animation SPCONFUS [extended animation]
    ohbjoke1 // (spl) <NO TEXT> - causes confusion - plays animation SPCONFUS
//              ~sirine1.itm~  ~override~ // Ghoul hand - causes confusion - unknown long effect - portrait icon 3 - portrait icon 48
//              ~spcl751a.spl~ ~override~ // <Invalid Strref -1> - causes confusion - plays spconfus, but only lasts one round before it renews so leave it alone rather than painfully extracting
    spdr501 // (spl) Chaos - causes confusion - portrait icon 47 - plays sound EFF_E05 - plays animation SPCONFUS
//              ~spin582.spl~  ~override~ // Confusion - causes confusion - portrait icon 3
    spin674 // (spl) Chaos - causes confusion - portrait icon 47 - plays sound EFF_E05 - plays animation SPCONFUS
    spin704 // (spl) Confusion - causes confusion - portrait icon 3 - plays sound EFF_E05 - plays animation SPCONFUS - portrait icon 3 - plays sound EFF_E05 - plays animation SPCONFUS - portrait icon 3 - plays sound EFF_E05 - plays animation SPCONFUS - portrait icon 3 - plays sound EFF_E05 - plays animation SPCONFUS - portrait icon 3 - plays sound EFF_E05 - plays animation SPCONFUS - portrait icon 3 - plays sound EFF_E05 - plays animation SPCONFUS - portrait icon 3 - plays sound EFF_E05 - plays animation SPCONFUS
    spin839 // (spl) Confusion - causes confusion - plays animation SPCONFUS - portrait icon 3 - plays sound EFF_E05
    spin976 // (spl) Confusion - causes confusion - plays animation SPCONFUS - portrait icon 3 - plays sound EFF_E05
    sppr311 // (spl) Rigid Thinking - causes confusion - portrait icon 2 - plays sound EFF_E06 [expiry sound]
    sppr609 // (spl) False Dawn - causes confusion - plays animation SPCONFUS via eff
    sppr709 // (spl) Confusion - causes confusion - portrait icon 3 - plays sound EFF_E05 - plays animation SPCONFUS
    sppr983 // (spl) Confusion - causes confusion - plays animation SPCONFUS - portrait icon 3 - plays sound EFF_E05
    spwi401 // (spl) Confusion - causes confusion - portrait icon 3 - plays sound EFF_E05 - plays animation SPCONFUS
    spwi508 // (spl) Chaos - causes confusion - portrait icon 47 - plays sound EFF_E05 - plays animation SPCONFUS
//              ~spwi711.spl~  ~override~ // Sphere of Chaos - causes confusion - causes hold - causes sleep - unknown long effect
    wa2harp // (itm) Harp of Pandemonium - causes confusion - plays animation SPCONFUS - portrait icon 3
    was2h  // (itm) Joril's Dagger +3 - causes confusion - portrait icon 3 - plays animation SPCONFUS
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END

COPY_EXISTING ~bdbrd03.spl~  ~override~ // Dispel Confusion - cures confusion
              ~bpdispel.spl~ ~override~ // <Invalid Strref -1> - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun
              ~cdhgtrl.spl~  ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtorgal.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtrlblz.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~globblu2.itm~ ~override~ // Blue Globe - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~ohbresto.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~ohsmode1.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohsmode4.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohtyr1.spl~   ~override~ // Exaltation - cures berserk - cures confusion - cures drunkenness - cures feeblemind - cures fear - cures sleep
              ~sppr350.spl~  ~override~ // Spiritual Clarity - cures confusion - cures feeblemind - cures fear
              ~sppr713.spl~  ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~spwish07.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~spwish46.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~trollreg.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
  LPF cd_apply_batch STR_VAR array_name = cd_cure_confusion END
  BUT_ONLY

/////                                                  \\\\\
///// deafness                                         \\\\\
/////                                                  \\\\\

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur242.spl~
/*
  PATCH_FOR_EACH res IN
              ~ohncoll.itm~  ~override~ // Collar Bell - cures sleep - causes deafness - portrait icon 112
              ~sppr710.spl~  ~override~ // Holy Word - causes deafness - causes stun - unknown long effect - unknown long effect - unknown long effect - portrait icon 105 - portrait icon 112
              ~sppr715.spl~  ~override~ // Unholy Word - causes deafness - causes stun - unknown long effect - unknown long effect - unknown long effect - portrait icon 105 - portrait icon 112
              ~spwi223.spl~  ~override~ // Deafness - causes deafness
              ~wand19.itm~   ~override~ // Wand of Cursing - causes blind - causes deafness - causes silence - unknown long effect - plays sound EFF_E06 - portrait icon 34 - unknown long effect - portrait icon 112
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END
*/

COPY_EXISTING ~amsoul01.itm~ ~override~ // Malla's Soul Stone - cures blind - cures deafness - cures disease - cures poison
              ~arow07.itm~   ~override~ // Arrow of Dispelling - cures deafness - cures feeblemind
              ~bdhelm11.itm~ ~override~ // Bard Hat - cures deafness - cures silence
              ~bhaal1a.spl~  ~override~ // Mass Healing - cures blind - cures deafness - cures disease - cures drunkenness - cures poison
              ~bpdispel.spl~ ~override~ // <Invalid Strref -1> - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun
              ~carsomyr.itm~ ~override~ // Carsomyr +5 - cures deafness - cures feeblemind
              ~cdhgtrl.spl~  ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtorgal.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtrlblz.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~deva.itm~     ~override~ // Mace of Disruption +2 - cures deafness - cures feeblemind - causes stun
              ~devaevil.itm~ ~override~ // Silver Sword - cures deafness - cures feeblemind
              ~devaheal.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~elemchan.itm~ ~override~ // Skull - cures deafness - cures feeblemind
              ~elemcryo.itm~ ~override~ // Skull - cures deafness - cures feeblemind
              ~elemhydr.itm~ ~override~ // Skull - cures deafness - cures feeblemind - causes stun - plays animation SPFIRESB - plays animation SPFIRESA - unknown long effect
              ~elemimix.itm~ ~override~ // Skull - cures deafness - cures feeblemind
              ~elemogre.itm~ ~override~ // Skull - cures deafness - cures feeblemind
              ~elemsunn.itm~ ~override~ // Skull - cures deafness - cures feeblemind
              ~elemyanc.itm~ ~override~ // Skull - cures deafness - cures feeblemind
              ~elemzaam.itm~ ~override~ // Skull - cures deafness - cures feeblemind
              ~finsol01.itm~ ~override~ // <Invalid Strref -1> - cures deafness - cures feeblemind
              ~misc5c.itm~   ~override~ // Rift Device - cures deafness - cures feeblemind
              ~ohbantim.spl~ ~override~ // <Invalid Strref -1> - cures deafness - cures feeblemind
              ~ohbbclt1.spl~ ~override~ // <Invalid Strref -1> - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~ohbbrvgr.itm~ ~override~ // Skull - cures deafness - cures feeblemind - causes sleep - unknown long effect
              ~ohbsuza1.spl~ ~override~ // <Invalid Strref -1> - cures deafness - cures feeblemind - causes pause - plays animation OHBGOLD - unknown long effect
              ~ohbwi302.spl~ ~override~ // Remove Magic - cures deafness - cures feeblemind
              ~ohreaver.itm~ ~override~ // Ir'revrykal +5 - cures deafness - cures feeblemind
              ~ohsmode1.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohsmode4.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~planetar.itm~ ~override~ // Silver Sword - cures deafness - cures feeblemind
              ~potn33.itm~   ~override~ // Potion of Magic Blocking - cures deafness - cures feeblemind
              ~ravag01.itm~  ~override~ // Skull - cures deafness - cures feeblemind - causes sleep - unknown long effect
              ~reaver.itm~   ~override~ // Unholy Reaver - cures deafness - cures feeblemind
              ~scrl07.itm~   ~override~ // Protection From Magic - cures deafness - cures feeblemind
              ~senspihe.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spcl231.spl~  ~override~ // Dispel Magic - cures deafness - cures feeblemind
              ~spin112.spl~  ~override~ // Dispel Magic - cures deafness - cures feeblemind
              ~spin201.spl~  ~override~ // Neutralize Poison - cures blind - cures deafness - cures disease - cures poison
              ~spin550.spl~  ~override~ // Anti-Magic Ray - cures deafness - cures feeblemind
              ~spin646.spl~  ~override~ // <Invalid Strref -1> - cures deafness - cures feeblemind
              ~spin647.spl~  ~override~ // Hold Person - cures deafness - cures feeblemind
              ~spin679.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spin699.spl~  ~override~ // Healing Lick - cures blind - cures deafness - cures disease - cures poison
              ~spin703.spl~  ~override~ // Dispel Magic - cures deafness - cures feeblemind
              ~spin711.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spin712.spl~  ~override~ // <Invalid Strref -1> - cures deafness - cures feeblemind
              ~spin734.spl~  ~override~ // Wish - cures blind - cures deafness - cures disease - cures drunkenness - cures poison
              ~spin768.spl~  ~override~ // <Invalid Strref -1> - cures deafness - cures feeblemind
              ~spin779.spl~  ~override~ // Anti-Magic - cures deafness - cures feeblemind
              ~spin866.spl~  ~override~ // Dispel Magic - cures deafness - cures feeblemind
              ~spin992.spl~  ~override~ // Anti-Magic Ray - cures deafness - cures feeblemind
              ~sppr303.spl~  ~override~ // Dispel Magic - cures deafness - cures feeblemind
              ~sppr317.spl~  ~override~ // Cure Disease - cures blind - cures deafness - cures disease - cures feeblemind
              ~sppr404.spl~  ~override~ // Neutralize Poison - cures blind - cures deafness - cures disease - cures poison
              ~sppr607.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spwi010.spl~  ~override~ // <Invalid Strref -1> - cures deafness - cures feeblemind
              ~spwi302.spl~  ~override~ // Remove Magic - cures deafness - cures feeblemind
              ~spwi326.spl~  ~override~ // Dispel Magic - cures deafness - cures feeblemind
              ~spwish28.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spwm168.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~staf11.itm~   ~override~ // Staff of the Magi - cures deafness - cures feeblemind - causes invisibility
              ~sw2h10.itm~   ~override~ // Carsomyr +5 - cures deafness - cures feeblemind
              ~sw2h10dm.spl~ ~override~ // Dispel Magic - cures deafness - cures feeblemind
              ~sw2h19.itm~   ~override~ // Carsomyr +6 - cures deafness - cures feeblemind
              ~trollreg.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
  LPF cd_apply_batch STR_VAR array_name = cd_cure_deafness END
  BUT_ONLY

/////                                                  \\\\\
///// disease                                          \\\\\
/////                                                  \\\\\

// tie otyugh slow icon to disease effect so it gets cleared by disease cures
COPY_EXISTING ~iotyugh.itm~ ~override~ // (itm) Attack - causes disease - portrait icon 41
              ~otyugh.itm~  ~override~ // (itm) Attack - causes disease - portrait icon 41
  LPF DELETE_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 41 END // delete slow effect
  LPF ALTER_EFFECT INT_VAR match_opcode = 78 match_parameter2 = 10 special = 41 END // change slow-via-disease to use slow icon instead of disease (other disease effect already uses disease icon)

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur242.spl~
  PATCH_FOR_EACH res IN
//              ~dartmel.itm~  ~override~ // Bone Dagger - causes disease - causes stun
//              ~demogorg.itm~ ~override~ // <Invalid Strref -1> - cures fear - causes disease - causes level drain - portrait icon 59
//              ~ghoullor.itm~ ~override~ // Ghoul Touch - causes disease - causes hold - portrait icon 13 - plays sound EFF_E05
//    iotyugh // (itm) Attack - causes disease - portrait icon 41 [uses slow icon with its disease]
//              ~lacedo.itm~   ~override~ // Attack - causes disease - causes hold - portrait icon 13 - plays sound EFF_E05
//              ~lacedo02.itm~ ~override~ // Ghoul Touch - causes disease - causes hold - portrait icon 13 - plays sound EFF_E05
//              ~mumgrew.itm~  ~override~ // <Invalid Strref -1> - causes disease
//              ~mummyw.itm~   ~override~ // <Invalid Strref -1> - causes disease
//              ~ohbcdis.spl~  ~override~ // Cause Disease - causes disease
//              ~ohbjoke2.spl~ ~override~ // <NO TEXT> - causes disease
//              ~ohbjoke3.spl~ ~override~ // <NO TEXT> - causes disease
//              ~ohhgmum1.itm~ ~override~ // <Invalid Strref -1> - causes disease
    ohrslng1 // (itm) Lupine Sling +2 - causes disease - portrait icon 41 [uses slow icon with its disease]
//    otyugh // (itm) Attack - causes disease - portrait icon 41 [uses slow icon with its disease]
//              ~p1-2p.itm~    ~override~ // Skull - causes disease
//              ~pudden01.itm~ ~override~ // <Invalid Strref -1> - causes disease
//              ~sahzom01.itm~ ~override~ // <Invalid Strref -1> - causes disease
//              ~spin784.spl~  ~override~ // Snake Gaze - causes disease
//              ~spwi409.spl~  ~override~ // Contagion - causes disease
//              ~zomsea.itm~   ~override~ // Short Sword - causes disease
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END

COPY_EXISTING ~amsoul01.itm~ ~override~ // Malla's Soul Stone - cures blind - cures deafness - cures disease - cures poison
              ~bhaal1a.spl~  ~override~ // Mass Healing - cures blind - cures deafness - cures disease - cures drunkenness - cures poison
              ~bpdispel.spl~ ~override~ // <Invalid Strref -1> - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun
              ~cdhgtrl.spl~  ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtorgal.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtrlblz.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~devaheal.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~globblu2.itm~ ~override~ // Blue Globe - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~ohbbclt1.spl~ ~override~ // <Invalid Strref -1> - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~ohbresto.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~ohsmode1.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohsmode4.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~potn17.itm~   ~override~ // Elixir of Health - cures disease - cures poison - causes drunkenness
              ~senspihe.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spin201.spl~  ~override~ // Neutralize Poison - cures blind - cures deafness - cures disease - cures poison
              ~spin599.spl~  ~override~ // <Invalid Strref -1> - cures disease - cures poison
              ~spin679.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spin699.spl~  ~override~ // Healing Lick - cures blind - cures deafness - cures disease - cures poison
              ~spin711.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spin734.spl~  ~override~ // Wish - cures blind - cures deafness - cures disease - cures drunkenness - cures poison
              ~spin746.spl~  ~override~ // <Invalid Strref -1> - cures disease - cures poison
              ~sppr317.spl~  ~override~ // Cure Disease - cures blind - cures deafness - cures disease - cures feeblemind
              ~sppr404.spl~  ~override~ // Neutralize Poison - cures blind - cures deafness - cures disease - cures poison
              ~sppr607.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~sppr713.spl~  ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~spwish07.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~spwish28.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spwish46.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~spwm168.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~staf10.itm~   ~override~ // Staff of Curing - cures disease - cures drunkenness - cures poison
              ~trollreg.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
  LPF cd_apply_batch STR_VAR array_name = cd_cure_disease END
  BUT_ONLY

/////                                                  \\\\\
///// drunkenness                                      \\\\\
/////                                                  \\\\\

COPY_EXISTING ~potn17.itm~ ~override~ // Elixir of Health - set drunkenness to 0, just change to 'cure drunk' instead
  LPF ALTER_EFFECT INT_VAR match_opcode = 94 opcode = 164 parameter2 = 0 END // flesh out effects below

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur164.spl~
  PATCH_FOR_EACH res IN
//              ~potn25.itm~   ~override~ // Potion of Healing - causes drunkenness
    spwish33 // (spl) Intoxication - causes drunkenness - plays sound EFF_E06 - portrait icon 5
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END

COPY_EXISTING ~amul22.itm~   ~override~ // Periapt of Proof Against Poison - cures drunkenness - cures poison
              ~bhaal1a.spl~  ~override~ // Mass Healing - cures blind - cures deafness - cures disease - cures drunkenness - cures poison
              ~brac20.itm~   ~override~ // Gloves of Healing - cures drunkenness - cures poison
              ~devaheal.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~globred2.itm~ ~override~ // Red Globe - cures drunkenness
              ~ohbbclt1.spl~ ~override~ // <Invalid Strref -1> - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~ohtyr1.spl~   ~override~ // Exaltation - cures berserk - cures confusion - cures drunkenness - cures feeblemind - cures fear - cures sleep
              ~potn17.itm~   ~override~ // Elixir of Health - set drunkenness to 0, just change to 'cure drunk' instead
              ~senspihe.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spin101.spl~  ~override~ // Cure Light Wounds - cures drunkenness
              ~spin102.spl~  ~override~ // Slow Poison - cures drunkenness - cures poison
              ~spin200.spl~  ~override~ // Cure Serious Wounds - cures drunkenness
              ~spin679.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spin711.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spin734.spl~  ~override~ // Wish - cures blind - cures deafness - cures disease - cures drunkenness - cures poison
              ~spin923.spl~  ~override~ // Limited Wish - cures drunkenness
              ~spin958.spl~  ~override~ // Cure Serious Wounds - cures drunkenness
              ~sppr103.spl~  ~override~ // Cure Light Wounds - cures drunkenness
              ~sppr212.spl~  ~override~ // Slow Poison - cures drunkenness
              ~sppr315.spl~  ~override~ // Cure Medium Wounds - cures drunkenness
              ~sppr401.spl~  ~override~ // Cure Serious Wounds - cures drunkenness
              ~sppr502.spl~  ~override~ // Cure Critical Wounds - cures drunkenness
              ~sppr514.spl~  ~override~ // Mass Cure - cures drunkenness
              ~sppr607.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spwish28.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spwm168.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~staf10.itm~   ~override~ // Staff of Curing - cures disease - cures drunkenness - cures poison
  LPF cd_apply_batch STR_VAR array_name = cd_cure_drunkenness END
  BUT_ONLY

/////                                                  \\\\\
///// fear and loathing in las baldur's gate           \\\\\
/////                                                  \\\\\

// stuff that causes fear and plays spmindat should be updated to play cdhorror instead
COPY_EXISTING ~ohbdfa1.spl~  ~override~ // how did you come to be here, elf? - causes fear - plays spmindat
              ~ohbtgaze.spl~ ~override~ // terrifying gaze - causes fear - plays spmindat
              ~spin680.spl~  ~override~ // deathsong - causes fear - plays spmindat
  LPF ALTER_EFFECT INT_VAR match_opcode = 215 STR_VAR match_resource = spmindat resource = cdhorror END
  BUT_ONLY

// split moondog howl's fear bits into separate spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/spin891a.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 24 target = 2 duration = 18 END // add panic [moondog]
  LPF CLONE_EFFECT INT_VAR match_opcode = 24 opcode = 142 parameter2 = 36 END // add 'panic' icon [moond2]
  LPF CLONE_EFFECT INT_VAR match_opcode = 24 opcode = 215 parameter2 = 1 STR_VAR resource = cdhorror END // play animation [moond4]
  LPF CLONE_EFFECT INT_VAR match_opcode = 24 opcode = 50 duration = 1 parameter1 = ((255 >> 32) + (195 >> 16) + 123) parameter2 = 1 END // color pulse [moond5]
  LPF CLONE_EFFECT INT_VAR match_opcode = 24 opcode = 106 duration = 1 parameter1 = 20 parameter2 = 1 END // set morale break [moond7]
  LPF CLONE_EFFECT INT_VAR match_opcode = 24 opcode = 139 timing = 1 duration = 0 parameter1 = 14007 END // add 'panic' string [moond1]
  LPF CLONE_EFFECT INT_VAR match_opcode = 139 opcode = 174 parameter2 = 0 STR_VAR resource = eff_m07 END // play sound [moond3]
  LPF CLONE_EFFECT INT_VAR match_opcode = 24 opcode = 324 parameter1 = panic_immunity parameter2 = 110 timing = 0 duration = 0 resist_dispel = 0 STR_VAR insert = first resource = EVAL ~%DEST_RES%~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 139 opcode =  12 parameter1 = 5 STR_VAR insert = first END // damage [moond8]
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 match_timing = 1 timing = 4 duration =  6 END // delayed damage 1 [moond8]
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 match_timing = 1 timing = 4 duration = 12 END // delayed damage 2 [moond8]

// replace effs aimed at mask_evil to a single 326 that calls spin891a instead
COPY_EXISTING ~spin891.spl~  ~override~ // Moon Dog Howl - cures fear - causes fear
  LPF ALTER_EFFECT INT_VAR multi_match = 1 match_opcode = 177 match_parameter1 = 3 match_parameter2 = 8 opcode = 326 parameter1 = 0 parameter2 = 37 timing = 1 duration = 0 STR_VAR resource = spin891a END
  LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 3 match_parameter2 = 8 END
  LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = spin891 END                                                      // delete out of stack
  LPF CLONE_EFFECT  INT_VAR multi_match = 1 match_opcode = 161 opcode = 321 parameter2 = 0 STR_VAR insert = first resource = spin891 END // insert back at top of stack
  
// placement of panic 324 blocks insect animation and spell failure icon
COPY_EXISTING ~sppr517.spl~  ~override~ // Insect Plague - causes fear - unknown long effect - plays animation ICINHIT - portrait icon 83
  PATCH_FOR_EACH op IN 324 24 BEGIN
    LPF CLONE_EFFECT  INT_VAR match_opcode = op STR_VAR insert = last END // copy to end of stack
    LPF DELETE_EFFECT INT_VAR match_opcode = op multi_match = 1 END       // delete original
  END  

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur161.spl~
  PATCH_FOR_EACH res IN
//              ~b1-12m4.itm~  ~override~ // Skull - causes fear
    bdsha01c // (spl) <Invalid Strref -1> - causes fear - portrait icon 36 - plays animation CDHORROR
//              ~bearspir.itm~ ~override~ // Attack - causes fear
//              ~flpr717a.spl~ ~override~ // <Invalid Strref -1> - causes fear - portrait icon 36
//              ~helm32.itm~   ~override~ // Helm of the Rock - causes fear - portrait icon 36 - unknown long effect
//              ~mistho.itm~   ~override~ // Skull - causes fear - portrait icon 36 - unknown long effect
//              ~mistice.itm~  ~override~ // Skull - causes fear - portrait icon 36 - unknown long effect
    ohbdfa1 // (spl) How did you come to be here, elf? - causes fear [has expiry sound, plays cdhorror]
    ohbdrag2 // (spl) Dragon Fear - causes fear [has expiry sound, plays cdhorror]
    ohbtgaze // (spl) Terrifying Gaze - causes fear - unknown long effect - portrait icon 36 - plays animation cdhorror
    ohreyeb3 // (spl) Fear - causes fear - portrait icon 36 - plays animation CDHORROR - plays sound EFF_E05
    ohrfear // (spl) Fear - causes fear - portrait icon 36 - plays animation OHRMIND - plays sound EFF_E05
//              ~rodmace.itm~  ~override~ // Mace +2 - causes fear
//              ~rods05.itm~   ~override~ // Rod of Terror - causes fear - portrait icon 36
//              ~spbatt1.itm~  ~override~ // Attack - causes fear
//              ~spbatt2.itm~  ~override~ // Attack - causes fear
//              ~spbatt3.itm~  ~override~ // Attack - causes fear
//              ~spbatt4.itm~  ~override~ // Attack - causes fear
//              ~spbatt5.itm~  ~override~ // Attack - causes fear
//              ~spcl103.spl~  ~override~ // Aura of Despair - [mixed - causes fear at higher levels, but rest of effects are from "despair"]
    spcl908 // (spl) War Cry - causes fear - portrait icon 36 - plays sound EFF_E05
    spin105 // (spl) Horror - causes fear - portrait icon 36 - plays animation cdhorror - plays sound EFF_E05
    spin203 // (spl) Cloak of Fear - causes fear - portrait icon 36 - plays sound EFF_E05
    spin536 // (spl) Fear - causes fear - unknown long effect - portrait icon 36 - plays sound EFF_E05 [has expiry sound, thac0 penalty attached to fear]
    spin559 // (apl) Keening - causes fear - portrait icon 36 - plays sound EFF_E05 [expiry sound]
    spin675 // (apl) Wandering Horror - causes fear - portrait icon 36 - unknown long effect - plays sound EFF_E05 [expiry sound]
    spin680 // (spl) Deathsong - causes fear - portrait icon 36 - plays animation cdhorror - plays sound EFF_E05 - unknown long effect [expiry sound, animation]
    spin772 // (spl) [HELL_FEAR] - causes fear - unknown long effect - portrait icon 36 - plays sound EFF_E05 [has expiry sound, thac0 penalty attached to fear]
//              ~spin807.spl~  ~override~ // Slayer Fear - causes fear - portrait icon 36
    spin882 // (spl) Vampire Fear - causes fear - portrait icon 36 - unknown long effect - portrait icon 36 [has expiry sound, thac0 penalty attached to fear]
    spin890 // (spl) Demon Fear - causes fear - portrait icon 36 - plays sound EFF_E05 [expiry sound]
//              ~spin891.spl~  ~override~ // Moon Dog Howl - cures fear - causes fear
    spin891a // (spl) Fear effects from moon dog howl have been shunted into this spell
    spin895 // (spl) Dragon Fear - causes fear - unknown long effect - portrait icon 36 - plays sound EFF_E05 [has expiry sound, thac0 penalty attached to fear]
//              ~spin921.spl~  ~override~ // Deathsong - causes fear - unknown long effect - unknown long effect
//              ~spin981.spl~  ~override~ // Fear - causes fear - portrait icon 36
    sppr416 // (spl) Cloak of Fear - causes fear - portrait icon 36 - plays sound EFF_E05 [expiry sound]
//              ~sppr517.spl~  ~override~ // Insect Plague - causes fear - portrait icon 83 - unknown long effect - unknown long effect - unknown long effect - unknown long effect - plays animation ICINHIT
    sppr706 // (spl) Symbol, Fear - causes fear - portrait icon 36 - plays sound EFF_E05 [expiry sound]
    spwi125 // (spl) Spook - causes fear - portrait icon 36 - plays sound EFF_E06 [expiry sound]
    spwi205 // (spl) Horror - causes fear - portrait icon 36 - plays animation cdhorror - plays sound EFF_E05
    spwi811 // (spl) Symbol, Fear - causes fear - portrait icon 36 - plays sound EFF_E05 [expiry sound]
    spwi899 // (spl) Symbol, Fear - causes fear - portrait icon 36 - plays sound EFF_E05 [expiry sound]
    spwi956 // (spl) Symbol, Fear - causes fear - portrait icon 36 - plays sound EFF_E05 [expiry sound]
    spwm123 // (spl) Symbol, Fear - causes fear - portrait icon 36 - plays sound EFF_E05 [expiry sound]
//              ~wand02.itm~   ~override~ // Wand of Fear - causes fear - portrait icon 36
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END

// stuff that cures fear should also remove anything that plays cdhorror (ignore creature files for this)
COPY_EXISTING ~abazring.itm~ ~override~ // Ring - cures fear
              ~ammonk07.cre~ ~override~ // Monk - cures fear
              ~ammonk08.cre~ ~override~ // Monk - cures fear
              ~amsmith.cre~  ~override~ // Kerrick the Smith - cures fear
              ~amul17.itm~   ~override~ // Greenstone Amulet - cures fear
              ~balth.cre~    ~override~ // Balthazar - cures fear
              ~bazdra02.cre~ ~override~ // Draconis - cures fear
              ~bazpatrg.itm~ ~override~ // Ring - cures fear - causes hold
              ~bhaalhp1.itm~ ~override~ // <Invalid Strref -1> - cures fear
              ~bhaalimm.itm~ ~override~ // <Invalid Strref -1> - cures fear
              ~bpdispel.spl~ ~override~ // <Invalid Strref -1> - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun
              ~brdflut1.itm~ ~override~ // Magic Flute - cures fear
              ~brdflute.itm~ ~override~ // Magic Flute - cures fear
              ~cdgoliro.itm~ ~override~ // Attack - cures fear
              ~cdhgtrl.spl~  ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdrngchr.itm~ ~override~ // <Invalid Strref -1> - cures fear
              ~cdtorgal.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtrlblz.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~chalcy3.itm~  ~override~ // Greenstone Amulet - cures fear
              ~chalslay.itm~ ~override~ // Ring - cures fear
              ~chwraith.itm~ ~override~ // <Invalid Strref -1> - cures fear
              ~clck30.itm~   ~override~ // Cloak of Bravery - cures fear
              ~ddguard1.cre~ ~override~ // Guardian - cures fear
              ~ddguard2.cre~ ~override~ // Guardian - cures fear
              ~ddguard3.cre~ ~override~ // Guardian - cures fear
              ~ddguard4.cre~ ~override~ // Guardian - cures fear
              ~ddguard5.cre~ ~override~ // Guardian - cures fear
              ~ddguard6.cre~ ~override~ // Guardian - cures fear
              ~ddguard7.cre~ ~override~ // Guardian - cures fear
              ~demogorg.itm~ ~override~ // <Invalid Strref -1> - cures fear - causes disease - causes level drain - portrait icon 59
              ~elemhydr.cre~ ~override~ // Olhydra - cures fear
              ~finmel01.itm~ ~override~ // <Invalid Strref -1> - cures fear
              ~firlch01.cre~ ~override~ // Fire Lich - cures fear
              ~fjbarda.spl~  ~override~ // <Invalid Strref -1> - cures fear
              ~fjbardb.spl~  ~override~ // <Invalid Strref -1> - cures fear
              ~fjbladeb.spl~ ~override~ // <Invalid Strref -1> - cures fear
              ~flpr717a.spl~ ~override~ // <Invalid Strref -1> - causes fear - portrait icon 36
              ~fsspir.itm~   ~override~ // Ring - cures fear
              ~globblu2.itm~ ~override~ // Blue Globe - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~golbra.itm~   ~override~ // <Invalid Strref -1> - cures fear
              ~golbra01.cre~ ~override~ // Brain Golem - cures fear
              ~golcla.itm~   ~override~ // Attack - cures fear
              ~golfle.itm~   ~override~ // Attack - cures fear
              ~golmag01.itm~ ~override~ // <Invalid Strref -1> - cures fear
              ~golstone.itm~ ~override~ // Ring - cures fear
              ~gorair01.cre~ ~override~ // Lesser Air Elemental - cures fear
              ~gorair02.cre~ ~override~ // Greater Air Elemental - cures fear
              ~gorcamb6.cre~ ~override~ // Fell Cat - cures fear
              ~gorcamb7.cre~ ~override~ // Fell Cat - cures fear
              ~gorchr.itm~   ~override~ // Ring - cures fear
              ~gorfirg.itm~  ~override~ // Ring - cures fear
              ~gorjelfu.itm~ ~override~ // Ring - cures fear
              ~gorjelgr.itm~ ~override~ // Ring - cures fear
              ~gormisti.itm~ ~override~ // Ring - cures fear
              ~gormistp.cre~ ~override~ // Poison Mist - cures fear
              ~gorstalk.cre~ ~override~ // Guardian of Air - cures fear
              ~hamm11.itm~   ~override~ // Runehammer +5 - cures fear
              ~helljon.cre~  ~override~ // Jon Irenicus - cures fear
              ~helljon2.cre~ ~override~ // Jon Irenicus - cures fear
              ~helm14.itm~   ~override~ // Kiel's Helmet - cures fear
              ~hgber01.itm~  ~override~ // Two-handed Sword +1 - cures fear
              ~hgfel01.cre~  ~override~ // Fell Cat - cures fear
              ~hllich.cre~   ~override~ // Elemental Lich - cures fear
              ~hlshade.cre~  ~override~ // Shade Lich - cures fear
              ~holdring.itm~ ~override~ // Ring - cures fear - causes hold
              ~igolem01.cre~ ~override~ // Sewage Golem - cures fear
              ~imoenhp1.itm~ ~override~ // Imoen's Belt - cures fear
              ~innoc.itm~    ~override~ // Ring - cures fear
              ~invulner.itm~ ~override~ // Ring - cures fear
              ~ipsion.itm~   ~override~ // Greenstone Amulet - cures fear
              ~irongol.itm~  ~override~ // <Invalid Strref -1> - cures fear
              ~jonhp1.itm~   ~override~ // <Invalid Strref -1> - cures fear
              ~kaypal02.cre~ ~override~ // Reynald de Chatillon - cures fear
              ~kaypal03.cre~ ~override~ // Fallen Paladin - cures fear
              ~kaysmg01.cre~ ~override~ // Rindus - cures fear
              ~kaysmg02.cre~ ~override~ // Smuggler - cures fear
              ~kaysmg03.cre~ ~override~ // Smuggler - cures fear
              ~killsw01.itm~ ~override~ // Varscona +2 - cures fear
              ~lichel01.cre~ ~override~ // Elemental Lich - cures fear
              ~mage20.cre~   ~override~ // Mage - cures fear
              ~mage20b.cre~  ~override~ // Mage - cures fear
              ~mage20c.cre~  ~override~ // Mage - cures fear
              ~maharper.itm~ ~override~ // Master Harper item - cures fear
              ~mane01.itm~   ~override~ // Ring - cures fear
              ~mdk2gun.itm~  ~override~ // Big Gun - cures fear
              ~mdk2ring.itm~ ~override~ // Big Gun - cures fear
              ~mdog1.itm~    ~override~ // <Invalid Strref -1> - cures fear
              ~mel01.itm~    ~override~ // Imoen's Belt - cures fear
              ~minhp1.itm~   ~override~ // <Invalid Strref -1> - cures fear
              ~misc3n.itm~   ~override~ // Azlaer's Harp - cures fear
              ~miscbc.itm~   ~override~ // Blackrazor +3 - cures fear - causes level drain - portrait icon 21 - unknown long effect - unknown long effect
              ~mistpo01.cre~ ~override~ // Poison Mist - cures fear
              ~mistposu.cre~ ~override~ // Poison Mist - cures fear
              ~nofear.itm~   ~override~ // <Invalid Strref -1> - cures fear
              ~objring.itm~  ~override~ // Ring - cures fear
              ~ohbbanno.spl~ ~override~ // <Invalid Strref -1> - cures fear
              ~ohbdtrai.itm~ ~override~ // <Invalid Strref -1> - cures fear
              ~ohbgol01.itm~ ~override~ // Attack - cures fear
              ~ohbresto.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~ohbwing2.itm~ ~override~ // Dark Justice +5 - cures fear
              ~ohdmask.itm~  ~override~ // The Visage - cures fear
              ~ohdmhp1.itm~  ~override~ // <Invalid Strref -1> - cures fear
              ~ohhayesh.cre~ ~override~ // Rabi'ah - cures fear
              ~ohhexam1.itm~ ~override~ // Hexxat's Amulet - cures fear
              ~ohhexam2.itm~ ~override~ // Hexxat's Amulet - cures fear
              ~ohhexam3.itm~ ~override~ // Hexxat's Amulet - cures fear
              ~ohhexam4.itm~ ~override~ // Hexxat's Amulet - cures fear
              ~ohhexam5.itm~ ~override~ // Hexxat's Amulet - cures fear
              ~ohhghuf.cre~  ~override~ // Sukayna - cures fear
              ~ohrrage.spl~  ~override~ // Animal Rage - cures fear - cures stun
              ~ohsmode1.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohsmode4.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohtyr1.spl~   ~override~ // Exaltation - cures berserk - cures confusion - cures drunkenness - cures feeblemind - cures fear - cures sleep
              ~palring.itm~  ~override~ // Ring - cures fear
              ~potn21.itm~   ~override~ // Potion of Clarity - cures fear
              ~ppireni2.cre~ ~override~ // Jon Irenicus - cures fear
              ~ravag03.itm~  ~override~ // <Invalid Strref -1> - cures fear
              ~ring94.itm~   ~override~ // Ring - cures fear
              ~ring95.itm~   ~override~ // Ring - cures fear
              ~ring98.itm~   ~override~ // Ring - cures fear
              ~ring99.itm~   ~override~ // Ring - cures fear
              ~ringdemn.itm~ ~override~ // <Invalid Strref -1> - cures fear
              ~ringkora.itm~ ~override~ // Ring - cures fear
              ~sendai7.cre~  ~override~ // Sendai - cures fear
              ~sengua04.itm~ ~override~ // <Invalid Strref -1> - cures fear - causes invisibility
              ~sewyag04.cre~ ~override~ // Yaga-Shura Mage - cures fear
              ~shalt01.itm~  ~override~ // Ring - cures fear
              ~shararm.itm~  ~override~ // Darkmail +3 - cures fear
              ~slayerw2.itm~ ~override~ // Attack - cures fear
              ~slayerw3.itm~ ~override~ // Attack - cures fear
              ~slayerw4.itm~ ~override~ // Attack - cures fear
              ~spbatt1.itm~  ~override~ // Attack - causes fear
              ~spbatt2.itm~  ~override~ // Attack - causes fear
              ~spbatt3.itm~  ~override~ // Attack - causes fear
              ~spbatt4.itm~  ~override~ // Attack - causes fear
              ~spbatt5.itm~  ~override~ // Attack - causes fear
              ~spcl104.spl~  ~override~ // Resist Fear - cures fear
              ~spcl152.spl~  ~override~ // Barbarian Rage - cures fear - cures stun
              ~spcl221.spl~  ~override~ // <Invalid Strref -1> - cures fear
              ~spcl222.spl~  ~override~ // Remove Fear - cures fear
              ~spcl321.spl~  ~override~ // Enrage - cures fear - cures stun
              ~spcl542a.spl~ ~override~ // <Invalid Strref -1> - cures fear
              ~spcl920a.spl~ ~override~ // <Invalid Strref -1> - cures fear
              ~spcl921a.spl~ ~override~ // <Invalid Strref -1> - cures fear
              ~spec01.itm~   ~override~ // Ring - cures fear
              ~spec02.itm~   ~override~ // <Invalid Strref -1> - cures fear
              ~spin117.spl~  ~override~ // Berserk - cures fear - causes berserk - [Minsc's berserk comes with many additional bonuses]
              ~spin676.spl~  ~override~ // Invoke Courage - cures fear
              ~spin872.spl~  ~override~ // <Invalid Strref -1> - cures fear
              ~spin891.spl~  ~override~ // Moon Dog Howl - cures fear - causes fear - unknown long effect - unknown long effect - portrait icon 36 - plays animation cdhorror - portrait icon 37 - portrait icon 9
              ~spin906.spl~  ~override~ // <Invalid Strref -1> - cures fear
              ~sppr108.spl~  ~override~ // Remove Fear - cures fear
              ~sppr350.spl~  ~override~ // Spiritual Clarity - cures confusion - cures feeblemind - cures fear
              ~sppr713.spl~  ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~sprngb01.itm~ ~override~ // <1pp leftover> - cures fear
              ~sprngb02.itm~ ~override~ // <1pp leftover> - cures fear
              ~sprngb03.itm~ ~override~ // <1pp leftover> - cures hold - cures fear - cures stun
              ~sprngb04.itm~ ~override~ // <1pp leftover> - cures hold - cures fear - cures stun
              ~sprngl02.itm~ ~override~ // <1pp leftover> - cures fear
              ~sprngl03.itm~ ~override~ // <1pp leftover> - cures hold - cures fear - cures stun
              ~sprngl04.itm~ ~override~ // <1pp leftover> - cures hold - cures fear - cures stun
              ~sprngz05.itm~ ~override~ // <1pp leftover> - cures hold - cures fear - cures stun
              ~spwi210.spl~  ~override~ // Resist Fear - cures fear
              ~spwi411.spl~  ~override~ // Emotion: Hopelessness - cures fear - causes sleep [sleep and related effects shunted to subspell]
              ~spwish07.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~spwish46.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~stalker.itm~  ~override~ // Ring - cures fear
              ~sujon.cre~    ~override~ // Jon Irenicus - cures fear
              ~sujon2.cre~   ~override~ // Jon Irenicus - cures fear
              ~suraam.cre~   ~override~ // Raamilat - cures fear
              ~surehp1.itm~  ~override~ // Ring - cures fear
              ~susuneer.cre~ ~override~ // Suneer - cures fear
              ~sword01.cre~  ~override~ // Magical Sword - cures fear
              ~telslav2.itm~ ~override~ // <Invalid Strref -1> - cures fear
              ~trollimm.itm~ ~override~ // Ring - cures fear
              ~trollreg.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~tstatue.itm~  ~override~ // <Invalid Strref -1> - cures fear
              ~uddrow50.cre~ ~override~ // Drow Wizard - cures fear
              ~udgolem.cre~  ~override~ // Brain Golem - cures fear
              ~udlesa.cre~   ~override~ // Lasaonar - cures fear
              ~vampreg.itm~  ~override~ // Ring - cures fear
              ~vampreg1.itm~ ~override~ // Ring - cures fear
              ~vampreg2.itm~ ~override~ // Ring - cures fear
  LPF cd_apply_batch STR_VAR array_name = cd_cure_fear END
  BUT_ONLY

/////                                                  \\\\\
///// feeblemind                                       \\\\\
/////                                                  \\\\\

// the feeblemind effect already sets INT=3, so purging redundant effects
COPY_EXISTING ~sirine.itm~   ~override~ // Ghoul hand - causes feeblemind - unknown long effect - plays sound EFF_E05 - portrait icon 48
  LPF DELETE_EFFECT INT_VAR match_opcode = 19 END

// stuff that causes feeblemind and plays spmindat should be updated to play cdfeeble instead
COPY_EXISTING ~sppr650.spl~  ~override~ // spiritual lock - causes feeblemind - plays spmindat
              ~spwi509.spl~  ~override~ // feeblemind - causes feeblemind - plays spmindat
  LPF ALTER_EFFECT INT_VAR match_opcode = 215 STR_VAR match_resource = spmindat resource = cdfeeble END
  BUT_ONLY

// update anything which provides immunity to feeblemind by ADDING a new block for cdfeeble (basically stuff that also blocks hold, or didn't block spmindat originally)
COPY_EXISTING ~amul17.itm~   ~override~ // greenstone amulet - blocks cdhorror - cures fear - blocks spmindat - blocks spconfus - immune to hold - immune to confusion - immune to feeblemind - immune to fear - immune to stun
              ~cdrngchr.itm~ ~override~ // <invalid strref -1> - blocks cdhorror - cures fear - blocks spconfus - immune to feeblemind - immune to confusion - immune to fear
              ~chalcy3.itm~  ~override~ // greenstone amulet - blocks cdhorror - cures fear - blocks spmindat - blocks spconfus - immune to hold - immune to confusion - immune to feeblemind - immune to fear - immune to stun
              ~demogorg.itm~ ~override~ // <invalid strref -1> - blocks cdhorror - cures fear - blocks spmindat - immune to hold - blocks spconfus - immune to fear - immune to stun - immune to feeblemind - immune to confusion
              ~devaevil.cre~ ~override~ // fallen deva - blocks spconfus - immune to confusion - immune to feeblemind
              ~devagood.cre~ ~override~ // deva - blocks spconfus - immune to confusion - immune to feeblemind
              ~devast01.cre~ ~override~ // astral deva - blocks spconfus - immune to confusion - immune to feeblemind
              ~devmon01.cre~ ~override~ // monadic deva - blocks spconfus - immune to confusion - immune to feeblemind
              ~fangel01.cre~ ~override~ // einhiris - blocks spconfus - immune to confusion - immune to feeblemind
              ~finmel01.itm~ ~override~ // <invalid strref -1> - blocks cdhorror - cures fear - blocks spmindat - immune to hold - blocks spconfus - immune to fear - immune to stun - immune to feeblemind - immune to confusion
              ~finsol01.cre~ ~override~ // solar - blocks spconfus - immune to confusion - immune to feeblemind
              ~finsol04.cre~ ~override~ // fallen solar - blocks spmindat - immune to hold - blocks spconfus - immune to confusion - immune to feeblemind - immune to stun
              ~ipsion.itm~   ~override~ // greenstone amulet - blocks cdhorror - cures fear - blocks spmindat - immune to stun - immune to hold - immune to confusion - immune to feeblemind - immune to fear - blocks spconfus
              ~killsw01.itm~ ~override~ // varscona +2 - blocks cdhorror - cures fear - blocks spmindat - blocks spconfus - immune to fear - immune to stun - immune to confusion - immune to hold - immune to feeblemind
              ~mane01.itm~   ~override~ // ring - blocks cdhorror - cures fear - blocks spconfus - immune to fear - immune to confusion - immune to feeblemind
              ~mdk2gun.itm~  ~override~ // big gun - blocks cdhorror - cures fear - blocks spconfus - immune to feeblemind - immune to confusion - immune to fear
              ~mdk2ring.itm~ ~override~ // big gun - blocks cdhorror - cures fear - blocks spconfus - immune to feeblemind - immune to confusion - immune to fear
              ~minhp1.itm~   ~override~ // <invalid strref -1> - blocks cdhorror - cures fear - immune to feeblemind - immune to fear - immune to stun - immune to confusion - blocks spconfus - blocks spmindat - immune to hold
              ~ohbcel01.cre~ ~override~ // ariziel - blocks spconfus - immune to confusion - immune to feeblemind
              ~ohbcel02.cre~ ~override~ // fallen astral deva - blocks spconfus - immune to confusion - immune to feeblemind
              ~ohbcel03.cre~ ~override~ // fallen monadic deva - blocks spconfus - immune to confusion - immune to feeblemind
              ~ohbdva01.cre~ ~override~ // fallen deva - blocks spconfus - immune to confusion - immune to feeblemind
              ~ohbwing.cre~  ~override~ // the winged - blocks spconfus - immune to confusion - immune to feeblemind
              ~ohbwing2.cre~ ~override~ // the winged - blocks spconfus - immune to confusion - immune to feeblemind
              ~ohbwing2.itm~ ~override~ // dark justice +5 - blocks cdhorror - cures fear - blocks spmindat - blocks spconfus - immune to fear - immune to stun - immune to confusion - immune to hold - immune to feeblemind
              ~ohdmask.itm~  ~override~ // the visage - cures fear - blocks cdhorror - blocks spconfus - immune to fear - immune to feeblemind - immune to confusion
              ~ohdmhp1.itm~  ~override~ // <invalid strref -1> - blocks cdhorror - cures fear - immune to feeblemind - immune to fear - immune to stun - immune to confusion - blocks spconfus - blocks spmindat - immune to hold
              ~ohdplanb.cre~ ~override~ // planetar - blocks spconfus - immune to confusion - immune to feeblemind
              ~ohdplanj.cre~ ~override~ // planetar - blocks spconfus - immune to confusion - immune to feeblemind
              ~ohdplanl.cre~ ~override~ // planetar - blocks spconfus - immune to confusion - immune to feeblemind
              ~ohdpplan.cre~ ~override~ // planetar - blocks spconfus - immune to confusion - immune to feeblemind
              ~ohdsolar.cre~ ~override~ // planetar - blocks spconfus - immune to confusion - immune to feeblemind
              ~ohdsplan.cre~ ~override~ // planetar - blocks spconfus - immune to confusion - immune to feeblemind
              ~ohhexam4.itm~ ~override~ // hexxat's amulet - cures fear - blocks cdhorror - blocks spconfus - blocks spmindat - immune to fear - immune to stun - immune to feeblemind - immune to confusion - immune to hold
              ~ohrrage.spl~  ~override~ // animal rage - blocks cdhorror - cures fear - blocks spmindat - blocks spconfus - immune to fear - immune to hold - immune to confusion - immune to feeblemind - immune to stun - cures stun
              ~ohsmode1.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohsmode4.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohtyr1.spl~   ~override~ // exaltation - cures feeblemind - cures fear - cures confusion - blocks cdhorror - immune to fear - immune to feeblemind - blocks spconfus - immune to confusion
              ~planet01.cre~ ~override~ // planetar - blocks spconfus - immune to confusion - immune to feeblemind
              ~planevil.cre~ ~override~ // fallen planetar - blocks spconfus - immune to confusion - immune to feeblemind
              ~plangood.cre~ ~override~ // planetar - blocks spconfus - immune to confusion - immune to feeblemind
              ~planwish.cre~ ~override~ // fallen planetar - blocks spconfus - immune to confusion - immune to feeblemind
              ~potn21.itm~   ~override~ // potion of clarity - blocks cdhorror - cures fear - blocks spconfus - immune to feeblemind - immune to confusion - immune to fear
              ~ppguy01.cre~  ~override~ // <invalid strref -1> - blocks spconfus - immune to confusion - immune to feeblemind
              ~ravag03.itm~  ~override~ // <invalid strref -1> - blocks cdhorror - cures fear - blocks spmindat - immune to hold - blocks spconfus - immune to fear - immune to stun - immune to feeblemind - immune to confusion
              ~ringdemn.itm~ ~override~ // <invalid strref -1> - blocks cdhorror - cures fear - blocks spconfus - immune to feeblemind - immune to confusion - immune to fear
              ~solar.cre~    ~override~ // solar - blocks spconfus - immune to confusion - immune to feeblemind
              ~solar01.cre~  ~override~ // solar - blocks spconfus - immune to confusion - immune to feeblemind
              ~spcl321.spl~  ~override~ // enrage - blocks cdhorror - cures fear - blocks spmindat - blocks spconfus - immune to fear - immune to hold - immune to confusion - immune to stun - immune to feeblemind - cures stun
              ~spin117.spl~  ~override~ // Berserk - cures fear - causes berserk - [Minsc's berserk comes with many additional bonuses]
              ~sppr508.spl~  ~override~ // chaotic commands - immune to feeblemind - immune to confusion - immune to hold - blocks spmindat - blocks spconfus - immune to stun
              ~sprngb04.itm~ ~override~ // <unrelated> - blocks cdhorror - immune to hold - blocks spmindat - cures hold - cures stun - immune to feeblemind - immune to confusion - blocks spconfus - immune to fear - cures fear
              ~sprngl04.itm~ ~override~ // <unrelated> - blocks cdhorror - immune to hold - blocks spmindat - cures hold - cures stun - immune to feeblemind - immune to confusion - blocks spconfus - immune to fear - cures fear
              ~sprngs03.itm~ ~override~ // <unrelated> - immune to hold - blocks spmindat - cures hold - cures stun - immune to feeblemind - immune to confusion - blocks spconfus
              ~sprngs04.itm~ ~override~ // <unrelated> - immune to hold - blocks spmindat - cures hold - cures stun - immune to feeblemind - immune to confusion - blocks spconfus
              ~sprngz05.itm~ ~override~ // <unrelated> - blocks cdhorror - immune to hold - blocks spmindat - cures hold - cures stun - immune to feeblemind - immune to confusion - blocks spconfus - immune to fear - cures fear
              ~sword01.cre~  ~override~ // magical sword - blocks cdhorror - cures fear - immune to hold - blocks spmindat - blocks spconfus - immune to fear - immune to stun - immune to feeblemind - immune to confusion
              ~trollimm.itm~ ~override~ // ring - blocks cdhorror - cures fear - blocks spconfus - immune to stun - immune to hold - immune to fear - blocks spmindat - immune to confusion - immune to feeblemind
  LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 101 match_parameter2 = 76 opcode = 296 parameter2 = 0 STR_VAR resource = cdfeeble END
  BUT_ONLY

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur77.spl~
  PATCH_FOR_EACH res IN
//              ~dwfpdgfb.spl~ ~override~ // <Invalid Strref -1> - causes feeblemind - portrait icon 48
    potn23 // (itm) Oil of Speed - causes feeblemind - portrait icon 3 - plays sound EFF_E07 [use confusion icon and other stuff, but main effect is feeblemind not confusion]
//              ~ring23.itm~   ~override~ // Discipliner - causes feeblemind
//              ~scrl18.itm~   ~override~ // Cursed Scroll of Stupidity - causes feeblemind [has expiry sound but also uses whole bunch of other effects, so leave]
    sirine // (itm) Ghoul hand - causes feeblemind - unknown long effect - plays sound EFF_E05 - portrait icon 48
    sppr650 // (spl) Spiritual Lock - causes feeblemind - plays animation cdfeeble - portrait icon 48 - plays sound EFF_E05 [expiry sound, animation]
//              ~spwi509.spl~  ~override~ // Feeblemind - causes feeblemind [plays animation, but only for two seconds]
//              ~spwi714.spl~  ~override~ // Prismatic Spray - causes blind - causes feeblemind - unknown long effect
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END

COPY_EXISTING ~arow07.itm~   ~override~ // Arrow of Dispelling - cures deafness - cures feeblemind
              ~bpdispel.spl~ ~override~ // <Invalid Strref -1> - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun
              ~carsomyr.itm~ ~override~ // Carsomyr +5 - cures deafness - cures feeblemind
              ~cdhgtrl.spl~  ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtorgal.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtrlblz.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~deva.itm~     ~override~ // Mace of Disruption +2 - cures deafness - cures feeblemind - causes stun
              ~devaevil.itm~ ~override~ // Silver Sword - cures deafness - cures feeblemind
              ~devaheal.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~elemchan.itm~ ~override~ // Skull - cures deafness - cures feeblemind
              ~elemcryo.itm~ ~override~ // Skull - cures deafness - cures feeblemind
              ~elemhydr.itm~ ~override~ // Skull - cures deafness - cures feeblemind - causes stun - plays animation SPFIRESB - plays animation SPFIRESA - unknown long effect
              ~elemimix.itm~ ~override~ // Skull - cures deafness - cures feeblemind
              ~elemogre.itm~ ~override~ // Skull - cures deafness - cures feeblemind
              ~elemsunn.itm~ ~override~ // Skull - cures deafness - cures feeblemind
              ~elemyanc.itm~ ~override~ // Skull - cures deafness - cures feeblemind
              ~elemzaam.itm~ ~override~ // Skull - cures deafness - cures feeblemind
              ~finsol01.itm~ ~override~ // <Invalid Strref -1> - cures deafness - cures feeblemind
              ~globblu2.itm~ ~override~ // Blue Globe - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~misc5c.itm~   ~override~ // Rift Device - cures deafness - cures feeblemind
              ~ohbantim.spl~ ~override~ // <Invalid Strref -1> - cures deafness - cures feeblemind
              ~ohbbclt1.spl~ ~override~ // <Invalid Strref -1> - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~ohbbrvgr.itm~ ~override~ // Skull - cures deafness - cures feeblemind - causes sleep - unknown long effect
              ~ohbresto.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~ohbsuza1.spl~ ~override~ // <Invalid Strref -1> - cures deafness - cures feeblemind - causes pause - plays animation OHBGOLD - unknown long effect
              ~ohbwi302.spl~ ~override~ // Remove Magic - cures deafness - cures feeblemind
              ~ohreaver.itm~ ~override~ // Ir'revrykal +5 - cures deafness - cures feeblemind
              ~ohsmode1.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohsmode4.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohtyr1.spl~   ~override~ // Exaltation - cures berserk - cures confusion - cures drunkenness - cures feeblemind - cures fear - cures sleep
              ~planetar.itm~ ~override~ // Silver Sword - cures deafness - cures feeblemind
              ~potn33.itm~   ~override~ // Potion of Magic Blocking - cures deafness - cures feeblemind
              ~ravag01.itm~  ~override~ // Skull - cures deafness - cures feeblemind - causes sleep - unknown long effect
              ~reaver.itm~   ~override~ // Unholy Reaver - cures deafness - cures feeblemind
              ~scrl07.itm~   ~override~ // Protection From Magic - cures deafness - cures feeblemind
              ~senspihe.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spcl231.spl~  ~override~ // Dispel Magic - cures deafness - cures feeblemind
              ~spin112.spl~  ~override~ // Dispel Magic - cures deafness - cures feeblemind
              ~spin550.spl~  ~override~ // Anti-Magic Ray - cures deafness - cures feeblemind
              ~spin646.spl~  ~override~ // <Invalid Strref -1> - cures deafness - cures feeblemind
              ~spin647.spl~  ~override~ // Hold Person - cures deafness - cures feeblemind
              ~spin679.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spin703.spl~  ~override~ // Dispel Magic - cures deafness - cures feeblemind
              ~spin711.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spin712.spl~  ~override~ // <Invalid Strref -1> - cures deafness - cures feeblemind
              ~spin768.spl~  ~override~ // <Invalid Strref -1> - cures deafness - cures feeblemind
              ~spin779.spl~  ~override~ // Anti-Magic - cures deafness - cures feeblemind
              ~spin866.spl~  ~override~ // Dispel Magic - cures deafness - cures feeblemind
              ~spin992.spl~  ~override~ // Anti-Magic Ray - cures deafness - cures feeblemind
              ~sppr303.spl~  ~override~ // Dispel Magic - cures deafness - cures feeblemind
              ~sppr317.spl~  ~override~ // Cure Disease - cures blind - cures deafness - cures disease - cures feeblemind
              ~sppr350.spl~  ~override~ // Spiritual Clarity - cures confusion - cures feeblemind - cures fear
              ~sppr607.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~sppr713.spl~  ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~spwi010.spl~  ~override~ // <Invalid Strref -1> - cures deafness - cures feeblemind
              ~spwi302.spl~  ~override~ // Remove Magic - cures deafness - cures feeblemind
              ~spwi326.spl~  ~override~ // Dispel Magic - cures deafness - cures feeblemind
              ~spwish07.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~spwish28.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spwish46.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~spwm168.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~staf11.itm~   ~override~ // Staff of the Magi - cures deafness - cures feeblemind - causes invisibility
              ~sw2h10.itm~   ~override~ // Carsomyr +5 - cures deafness - cures feeblemind
              ~sw2h10dm.spl~ ~override~ // Dispel Magic - cures deafness - cures feeblemind
              ~sw2h19.itm~   ~override~ // Carsomyr +6 - cures deafness - cures feeblemind
              ~trollreg.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
  LPF cd_apply_batch STR_VAR array_name = cd_cure_feeblemind END
  BUT_ONLY

/////                                                  \\\\\
///// hold/paralyze                                    \\\\\
/////                                                  \\\\\

// split hold from bounty hunter's special snare into own spell
OUTER_SET hold_immunity = IDS_OF_SYMBOL (~splstate~ ~HOLD_IMMUNITY~)
COPY ~eefixpack/files/spl/spcl415h.spl~ ~override~ // just the hold ability farmed out into separate spell
  LPF ALTER_EFFECT INT_VAR match_opcode = 324 parameter1 = hold_immunity END
COPY_EXISTING ~spcl415.spl~ ~override~
  LPF DELETE_EFFECT INT_VAR match_opcode = 177 END // deletes hold EFFs
  LPF ALTER_EFFECT INT_VAR match_opcode = 175 opcode = 326 power = 0 parameter1 = 0 parameter2 = 5 timing = 1 duration = 0 resist_dispel = 0 savingthrow = 0 savebonus = 0 STR_VAR resource = spcl415h END // change hold to apply spell to humanoids
  BUT_ONLY

// immune to hold, but missing spmindat immunity
COPY_EXISTING ~ohbetrai.itm~ ~override~ // <invalid strref -1> - immune to stun - immune to hold
  LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 101 match_parameter2 = 175 opcode = 296 parameter2 = 0 STR_VAR resource = spmindat END
  BUT_ONLY

// shunt ghast/ghoul lord hold stuff to new ability
OUTER_SET hold_immunity = IDS_OF_SYMBOL (~splstate~ ~HOLD_IMMUNITY~)
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/ghast1p.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 109 target = 2 parameter2 = 2 duration = 42 END // add paralyze
  LPF CLONE_EFFECT INT_VAR match_opcode = 109 opcode = 142 parameter2 = 13 STR_VAR insert = below END // add 'held' icon
  LPF CLONE_EFFECT INT_VAR match_opcode = 109 opcode = 141 timing = 1 duration = 0 parameter2 = 1 STR_VAR insert = below END // add 'necromancy earth' effect
  LPF CLONE_EFFECT INT_VAR match_opcode = 141 opcode = 61 duration = 1 parameter1 = ((120 << 24) + (90 << 16) + (60 << 8)) parameter2 = (25 << 16) STR_VAR insert = below END
  LPF CLONE_EFFECT INT_VAR match_opcode = 141 opcode = 174 duration = 0 parameter2 = 0 STR_VAR resource = eff_p11 insert = below END // immediate sound
  LPF CLONE_EFFECT INT_VAR match_opcode = 174 timing = 4 duration = 42 STR_VAR resource = eff_e05 insert = below END // expiry sound
  LPF CLONE_EFFECT INT_VAR match_opcode = 109 opcode = 324 parameter1 = hold_immunity parameter2 = 110 timing = 0 resist_dispel = 0 duration = 0 STR_VAR insert = first resource = EVAL ~%DEST_RES%~ END

// shunt ghoul lord hold stuff to new ability
COPY_EXISTING ~ghast1p.spl~ ~override/ghoulloh.spl~ // make one for ghoul lord (different duration)
  LPF ALTER_EFFECT INT_VAR match_duration = 42 duration = 30 END
  LPF ALTER_EFFECT INT_VAR match_opcode = 324 STR_VAR resource = EVAL ~%DEST_RES%~ END

// shunt ghast hold stuff to new ability
COPY_EXISTING ~ghast1.itm~   ~override~ // Attack - causes hold - portrait icon 13 - plays sound EFF_E05 - plays sound EFF_E07 - unknown long effect - portrait icon 126
              ~ghoullor.itm~ ~override~ // Ghoul Touch - causes disease - causes hold - portrait icon 13 - plays sound EFF_E05
              ~lacedo.itm~   ~override~ // Attack - causes disease - causes hold - portrait icon 13 - plays sound EFF_E05
              ~lacedo02.itm~ ~override~ // Ghoul Touch - causes disease - causes hold - portrait icon 13 - plays sound EFF_E05
  LPF ALTER_EFFECT INT_VAR match_opcode = 109 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ghast1p END // change paralyze to cast spells
  LPF DELETE_EFFECT INT_VAR match_opcode = 141 END // delete related
  LPF DELETE_EFFECT INT_VAR match_opcode = 61 END // delete related
  LPF DELETE_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 13 END // delete related
  LPF DELETE_EFFECT INT_VAR match_opcode = 174 STR_VAR match_resource = eff_e05 END // delete related
  LPF DELETE_EFFECT INT_VAR match_opcode = 174 STR_VAR match_resource = eff_p11 END // delete related

// shunt ghoul lord hold stuff to new ability
COPY_EXISTING ~ghoullor.itm~ ~override~ // make one for ghoul lord (different duration)
  LPF ALTER_EFFECT INT_VAR match_opcode = 146 STR_VAR resource = ghoulloh END // change paralyze to cast spells

// elven immunity to ghoul attack should also block expiry sound
COPY_EXISTING ~ghoul1.itm~   ~override~ // Ghoul Touch - causes hold - plays sound EFF_E05 - portrait icon 13 [expiry sound]
  LPF CLONE_EFFECT INT_VAR match_opcode = 324 opcode = 424 STR_VAR insert = first END
  LPF DELETE_EFFECT INT_VAR match_opcode = 324 END
  LPF ALTER_EFFECT INT_VAR match_opcode = 424 opcode = 324 END

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur162.spl~
  PATCH_FOR_EACH res IN
//              ~basilg1.itm~  ~override~ // Attack - causes hold
//              ~basill1.itm~  ~override~ // Attack - causes hold
//              ~bazpatrg.itm~ ~override~ // Ring - cures fear - causes hold
    carrio1 // (itm) Attack - causes hold - portrait icon 13 - plays sound EFF_E05 [expiry sound]
//              ~dagg17.itm~   ~override~ // Stiletto of Demarchess +2 - causes hold - portrait icon 13
    demmau01 // (itm) Skull - causes hold - portrait icon 13 - plays sound EFF_E05 [expiry sound]
//              ~ghast1.itm~   ~override~ // Attack - causes hold - portrait icon 13 - plays sound EFF_E05 - plays sound EFF_E07 - unknown long effect - portrait icon 126
    ghast1p // (spl) hold effects from ghast1.itm, lacedo.itm, lacedo02.itm have been moved here
    ghoul1 // (itm) Ghoul Touch - causes hold - plays sound EFF_E05 - portrait icon 13 [expiry sound]
//              ~ghoullor.itm~ ~override~ // Ghoul Touch - causes disease - causes hold - portrait icon 13 - plays sound EFF_E05
    ghoullop // (spl) hold effects from ghoullor.itm shunted into this spell
    ghoult // (itm) Ghoul Touch - causes hold - portrait icon 13 - plays sound EFF_E05 [expiry sound]
//              ~holdring.itm~ ~override~ // Ring - cures fear - causes hold
    kaldw1 // (itm) <Invalid Strref -1> - causes hold - portrait icon 13 - plays sound EFF_E03 [expiry sound]
//              ~lacedo.itm~   ~override~ // Attack - causes disease - causes hold - portrait icon 13 - plays sound EFF_E05
//              ~lacedo02.itm~ ~override~ // Ghoul Touch - causes disease - causes hold - portrait icon 13 - plays sound EFF_E05
//              ~lich02.itm~   ~override~ // Ghoul Touch - causes hold - portrait icon 13
//              ~ohbdagg1.itm~ ~override~ // Ornate Dagger - causes hold - portrait icon 13
    ohbenvlp // (spl) Yoshimo's Katana +1 - causes hold - plays animation SPMINDAT - portrait icon 13
    ohnwand1 // (spl) <NO TEXT> - causes hold - unknown long effect - plays animation OHNWAND1 - unknown long effect - unknown long effect
    ohreyeb2 // (spl) Paralyze - causes hold - plays sound EFF_E08 [expiry sound]
//              ~parabasi.itm~ ~override~ // <Invalid Strref -1> - causes hold
    revent1 // (itm) <Invalid Strref -1> - causes hold - portrait icon 13 - plays sound EFF_E05 [expiry sound]
//              ~rodsword.itm~ ~override~ // Flaming Long Sword +1 - causes hold - unknown long effect
    spcl415h // (spl) <Invalid Strref -1> - causes hold - plays animation SPMINDAT - portrait icon 13 [animation]
    spcl742 // (spl) Hold Undead - causes hold - plays animation CDUNHVIS - plays sound EFF_E06 [expiry sound, animation]
    spin648 // Hold Person - causes hold [plays spmindat permanently]
//              ~spin776.spl~  ~override~ // <Invalid Strref -1> - causes hold
//              ~spin863.spl~  ~override~ // <Invalid Strref -1> - causes hold
    spin914 // (spl) Mimic Glue - causes hold - plays animation GREASED - portrait icon 13 [animation]
//              ~spin960.spl~  ~override~ // Paralyzation Ray - causes hold
    spin988 // (spl) Hold Person - causes hold - plays animation SPMINDAT - plays sound EFF_E08 [expiry sound, animation]
    spin990 // (spl) Paralyze - causes hold - plays sound EFF_E08 [expiry sound]
//              ~spin996.spl~  ~override~ // Death Gaze - causes hold
    spin999 // (spl) Paralyze - causes hold - plays sound EFF_E05 [expiry sound]
    sppr208 // (spl) Hold Person - causes hold - plays animation SPMINDAT - plays sound EFF_E05 [animation, expiry sound]
    sppr305 // (spl) Hold Animal - causes hold - plays animation SPMINDAT - plays sound EFF_E06 [animation, expiry sound]
    sppr989 // (spl) Hold Person - causes hold - plays animation SPMINDAT - plays sound EFF_E08 [animation, expiry sound]
//              ~spwatt2.itm~  ~override~ // Attack - causes hold
//              ~spwatt3.itm~  ~override~ // Attack - causes hold
//              ~spwatt4.itm~  ~override~ // Attack - causes hold
//              ~spwatt5.itm~  ~override~ // Attack - causes hold - causes level drain
    spwi306 // (spl) Hold Person - causes hold - plays animation SPMINDAT - plays sound EFF_E08 [animation, expiry sound]
    spwi324 // (spl) Hold Undead - causes hold - plays animation CDUNHVIS - plays sound EFF_E06 [animation, expiry sound]
    spwi507 // (spl) Hold Monster - causes hold - plays sound EFF_E08 - plays animation SPMINDAT [animation, expiry sound]
//              ~spwi711.spl~  ~override~ // Sphere of Chaos - causes confusion - causes hold - causes sleep - unknown long effect
//              ~spwm114.spl~  ~override~ // Polymorph Other - causes hold
    spwm122 // (spl) Hold Person - causes hold - plays animation SPMINDAT - plays sound EFF_E05 [animation, expiry sound]
//              ~vampire.itm~  ~override~ // <Invalid Strref -1> - causes hold - portrait icon 13
    wolfva1 // (itm) <Invalid Strref -1> - causes hold - portrait icon 13 - plays sound EFF_E05 [expiry sound]
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END

COPY_EXISTING ~blun30.itm~   ~override~ // Flail of Ages +5 - cures hold - cures stun
              ~bpdispel.spl~ ~override~ // <Invalid Strref -1> - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun
              ~cdhgtrl.spl~  ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtorgal.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtrlblz.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~misc3o.itm~   ~override~ // Methild's Harp - cures hold - cures stun
              ~npplat.itm~   ~override~ // Firecam Full-Plate Armor - cures hold - cures stun
              ~ohsmode1.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohsmode4.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~potn45.itm~   ~override~ // Potion of Freedom - cures hold - cures stun
              ~ring09.itm~   ~override~ // Edventar's Gift - cures hold - cures stun
              ~sper12.itm~   ~override~ // Ixil's Spike +6 - cures hold - cures stun - causes sleep - unknown long effect - unknown long effect
              ~spin862.spl~  ~override~ // <Invalid Strref -1> - cures hold
              ~sppr308.spl~  ~override~ // Remove Paralysis - cures hold - cures stun
              ~sppr403.spl~  ~override~ // Free Action - cures hold - cures stun
              ~sprngb03.itm~ ~override~ // <1pp leftover> - cures hold - cures fear - cures stun
              ~sprngb04.itm~ ~override~ // <1pp leftover> - cures hold - cures fear - cures stun
              ~sprngl03.itm~ ~override~ // <1pp leftover> - cures hold - cures fear - cures stun
              ~sprngl04.itm~ ~override~ // <1pp leftover> - cures hold - cures fear - cures stun
              ~sprngs01.itm~ ~override~ // <1pp leftover> - cures hold - cures stun
              ~sprngs02.itm~ ~override~ // <1pp leftover> - cures hold - cures stun
              ~sprngs03.itm~ ~override~ // <1pp leftover> - cures hold - cures stun
              ~sprngs04.itm~ ~override~ // <1pp leftover> - cures hold - cures stun
              ~sprngz05.itm~ ~override~ // <1pp leftover> - cures hold - cures fear - cures stun
              ~sw2h06.itm~   ~override~ // Spider's Bane +2 - cures hold - cures stun
              ~sw2h13.itm~   ~override~ // Spider's Bane +2 - cures hold - cures stun
              ~trollreg.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
  LPF cd_apply_batch STR_VAR array_name = cd_cure_hold END
  BUT_ONLY

/////                                                  \\\\\
///// invisibility                                     \\\\\
/////                                                  \\\\\

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur116.spl~
  PATCH_FOR_EACH res IN
//              ~balth10.spl~  ~override~ // Shadow Stance! - causes invisibility - unknown long effect
//              ~bdact10.cre~  ~override~ // Marcus - causes invisibility
//              ~bdcutid.cre~  ~override~ // <Invalid Strref -1> - causes invisibility
//              ~bdddoorx.spl~ ~override~ // Dimension Door - causes invisibility
//              ~bdoffscr.cre~ ~override~ // <Invalid Strref -1> - causes invisibility
//              ~bdsha12b.itm~ ~override~ // Attack - causes invisibility
//              ~bdsha18b.itm~ ~override~ // Attack - causes invisibility
//              ~ch7spy.cre~   ~override~ // <Invalid Strref -1> - causes invisibility
//              ~cutspy.cre~   ~override~ // <Invalid Strref -1> - causes invisibility
//              ~cutspy2.cre~  ~override~ // <Invalid Strref -1> - causes invisibility
//              ~dagg21.itm~   ~override~ // Dagger of the Star +4 - causes invisibility
//              ~dagg22.itm~   ~override~ // Dagger of the Star +5 - causes invisibility
//              ~drstatu1.cre~ ~override~ // Statue - causes invisibility
//              ~drstatu2.cre~ ~override~ // Statue - causes invisibility
//              ~drstatu3.cre~ ~override~ // Statue - causes invisibility
//              ~firering.itm~ ~override~ // Sandthief's Ring - causes invisibility
//              ~fsglob.cre~   ~override~ // Globe Machine - causes invisibility
//              ~goboom.itm~   ~override~ // <Invalid Strref -1> - causes invisibility
//              ~gopoof.itm~   ~override~ // <Invalid Strref -1> - causes invisibility
//              ~gorbel.cre~   ~override~ // Bell Jar - causes invisibility
//              ~gordeck5.cre~ ~override~ // Assassin - causes invisibility
//              ~gordeck6.cre~ ~override~ // Assassin - causes invisibility
//              ~gordeck7.cre~ ~override~ // Assassin - causes invisibility
//              ~gordeck8.cre~ ~override~ // Assassin - causes invisibility
//              ~gordeck9.cre~ ~override~ // Assassin - causes invisibility
//              ~gordecka.cre~ ~override~ // Assassin - causes invisibility
//              ~gorfan.cre~   ~override~ // <Invalid Strref -1> - causes invisibility
//              ~gorlum.cre~   ~override~ // Machine of Lum - causes invisibility
//              ~gorspy.cre~   ~override~ // <Invalid Strref -1> - causes invisibility
//              ~gortor1.cre~  ~override~ // Torch - causes invisibility
//              ~gortor2.cre~  ~override~ // Torch - causes invisibility
//              ~gortor3.cre~  ~override~ // Torch - causes invisibility
//              ~gortor4.cre~  ~override~ // Torch - causes invisibility
//              ~gortor5.cre~  ~override~ // Torch - causes invisibility
//              ~gortor6.cre~  ~override~ // Torch - causes invisibility
//              ~hellspy.cre~  ~override~ // <Invalid Strref -1> - causes invisibility
//              ~hellspy2.cre~ ~override~ // <Invalid Strref -1> - causes invisibility
//              ~hellspy3.cre~ ~override~ // <Invalid Strref -1> - causes invisibility
//              ~hellspy4.cre~ ~override~ // <Invalid Strref -1> - causes invisibility
//              ~hellspy5.cre~ ~override~ // <Invalid Strref -1> - causes invisibility
//              ~hellspy6.cre~ ~override~ // <Invalid Strref -1> - causes invisibility
//              ~impinvis.itm~ ~override~ // Sandthief's Ring - causes invisibility
//              ~invisabo.cre~ ~override~ // <Invalid Strref -1> - causes invisibility
//              ~m05pcspy.cre~ ~override~ // <Invalid Strref -1> - causes invisibility
//              ~mage01.itm~   ~override~ // Sandthief's Ring - causes invisibility
//              ~nosave.cre~   ~override~ // <Invalid Strref -1> - causes invisibility
//              ~observe.cre~  ~override~ // <Invalid Strref -1> - causes invisibility
//              ~ohbcutsc.cre~ ~override~ // <Invalid Strref -1> - causes invisibility - causes nondetection
    ohbwi405 // (spl) Improved Invisibility - causes invisibility - plays sound EFF_M10 [expiry sound]
//              ~ohdportl.cre~ ~override~ // Glowing Portal - causes invisibility
//              ~ohdscrol.cre~ ~override~ // Scroll of Retribution - causes invisibility
//              ~ohdswaz.cre~  ~override~ // Azothet - causes invisibility
//              ~ohdswur.cre~  ~override~ // Ur-Gothoz - causes invisibility
//              ~ohdxach.cre~  ~override~ // Xachrimos - causes invisibility
//              ~ohdxach2.cre~ ~override~ // Xachrimos - causes invisibility
//              ~ohnrefin.cre~ ~override~ // <Invalid Strref -1> - causes invisibility
//              ~ohnsub11.cre~ ~override~ // Subject 11 Notes - causes invisibility
//              ~ohnsub13.cre~ ~override~ // Subject 13 Notes - causes invisibility
//              ~ohnsub34.cre~ ~override~ // Subject 34 Notes - causes invisibility
//              ~ohnsub42.cre~ ~override~ // Subject 42 Notes - causes invisibility
//              ~ohnsub5.cre~  ~override~ // Subject 5 Notes - causes invisibility
//              ~ohnsub55.cre~ ~override~ // Subject 55 Notes - causes invisibility
//              ~ohnsub69.cre~ ~override~ // Subject 69 Notes - causes invisibility
//              ~ohnsub9.cre~  ~override~ // Subject 9 Notes - causes invisibility
//              ~ohrring2.itm~ ~override~ // Ring - causes invisibility - causes nondetection
//              ~ohrstalk.cre~ ~override~ // Invisible Stalker - causes invisibility
//              ~potn10.itm~   ~override~ // Potion of Invisibility - causes invisibility
//              ~ppguy01.cre~  ~override~ // <Invalid Strref -1> - causes invisibility - unknown long effect - unknown long effect - unknown long effect
//              ~ring05.itm~   ~override~ // Sandthief's Ring - causes invisibility
//              ~ring39.itm~   ~override~ // Ring of Gaxx - causes invisibility - unknown long effect
//              ~ring42.itm~   ~override~ // The Specter's Ring - causes invisibility
//              ~rossland.itm~ ~override~ // Sandthief's Ring - causes invisibility
//              ~sargrd09.cre~ ~override~ // Thief - causes invisibility
//              ~sengua04.itm~ ~override~ // <Invalid Strref -1> - cures fear - causes invisibility
//              ~sewsw.cre~    ~override~ // Glowing Pool - causes invisibility
//              ~spcl415a.spl~ ~override~ // <Invalid Strref -1> - causes invisibility
//              ~spcl938.spl~  ~override~ // Shadow Form - causes invisibility [has whole mess of effects from HLA]
//              ~spcl940.spl~  ~override~ // Spirit Form - causes invisibility [has whole mess of effects from HLA]
    spdr401 // (spl) Improved Invisibility - causes invisibility - plays sound EFF_P05 [expiry sound]
//              ~spin118.spl~  ~override~ // Invisibility - causes invisibility
    spin544 // (spl) Improved Invisibility - causes invisibility - plays sound EFF_M10 [expiry sound]
//              ~spin672.spl~  ~override~ // <Invalid Strref -1> - causes invisibility
    spin687 // Create Shadows - causes invisibility - plays sound EFF_M10 [expiry sound]
//              ~spin698.spl~  ~override~ // Improved Invisibility - causes invisibility - causes nondetection
//              ~sppr516.spl~  ~override~ // Pixie Dust - causes invisibility
//              ~spwi206.spl~  ~override~ // Invisibility - causes invisibility
    spwi307 // (spl) Invisibility, 10' Radius - causes invisibility - plays sound EFF_M10 [expiry sound]
    spwi405 // (spl) Improved Invisibility - causes invisibility - plays sound EFF_M10 [expiry sound]
//              ~spwi413a.spl~ ~override~ // <Invalid Strref -1> - causes invisibility [otiluke's]
    spwi505 // (spl) Shadow Door - causes invisibility - plays sound EFF_E01 [expiry sound]
//              ~spwi607.spl~  ~override~ // Mislead - causes invisibility - unknown long effect
    spwi721 // (spl) Mass Invisibility - causes invisibility - plays sound EFF_M10 [expiry sound]
//              ~spwi927.spl~  ~override~ // Ethereal - causes invisibility - unknown long effect - unknown long effect
//              ~spy406.cre~   ~override~ // <Invalid Strref -1> - causes invisibility
//              ~staf11.itm~   ~override~ // Staff of the Magi - cures deafness - cures feeblemind - causes invisibility
//              ~suspy.cre~    ~override~ // <Invalid Strref -1> - causes invisibility
//              ~swordi.itm~   ~override~ // <Invalid Strref -1> - causes invisibility - causes nondetection
//              ~trollspi.itm~ ~override~ // Attack - causes invisibility - unknown long effect - portrait icon 91
//              ~ucounter.cre~ ~override~ // <Invalid Strref -1> - causes invisibility [essentially a cutspy]
//              ~uhostile.cre~ ~override~ // <Invalid Strref -1> - causes invisibility [essentially a cutspy]
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END

COPY_EXISTING ~jwtrue.spl~   ~override~ // <Invalid Strref -1> - cures invisibility
              ~ohbddeti.spl~ ~override~ // <Invalid Strref -1> - cures invisibility - cures nondetection
              ~ohdpotn1.spl~ ~override~ // Detect Invisibility - cures invisibility
//              ~ohdwand1.itm~ ~override~ // Wand of Glitterdust - changed to cast spwi224 directly, above
              ~ohdxdis.spl~  ~override~ // Invisibility Purge - cures invisibility
              ~spcl232.spl~  ~override~ // True Sight - cures invisibility
              ~spcl232d.spl~ ~override~ // True Sight - cures invisibility
              ~spcl732.spl~  ~override~ // True Sight - cures invisibility
              ~sppr309.spl~  ~override~ // Invisibility Purge - cures invisibility
              ~sppr505.spl~  ~override~ // True Seeing - cures invisibility
              ~sppr505d.spl~ ~override~ // True Seeing - cures invisibility
              ~sppr950.spl~  ~override~ // True Sight - cures invisibility
              ~spwi203.spl~  ~override~ // Detect Invisibility - cures invisibility
              ~spwi224.spl~  ~override~ // Glitterdust - cures invisibility - causes blind - unknown long effect - unknown long effect - plays sound EFF_E07
              ~spwi515.spl~  ~override~ // Oracle - cures invisibility
              ~spwi609.spl~  ~override~ // True Sight - cures invisibility
              ~spwi609d.spl~ ~override~ // True Sight - cures invisibility
  LPF cd_apply_batch STR_VAR array_name = cd_cure_invisbility END
  BUT_ONLY

/////                                                  \\\\\
///// level drain                                      \\\\\
/////                                                  \\\\\

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur224.spl~
/* because level drains are permanent, none of them have limited companion effects
  PATCH_FOR_EACH res IN
              ~blakblad.itm~ ~override~ // Black Blade of Disaster - causes level drain
              ~bodhi.itm~    ~override~ // <Invalid Strref -1> - causes level drain
              ~dagg20.itm~   ~override~ // Life-Stealer +4 - causes level drain
              ~demogorg.itm~ ~override~ // <Invalid Strref -1> - cures fear - causes disease - causes level drain - portrait icon 59
              ~demsuc01.itm~ ~override~ // <Invalid Strref -1> - causes level drain - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect
              ~dogwawp.itm~  ~override~ // Attack - causes level drain - unknown long effect
              ~gorwom1.itm~  ~override~ // <Invalid Strref -1> - causes level drain - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - portrait icon 1
              ~hgwra01.itm~  ~override~ // Quarterstaff - causes level drain - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect
              ~innoc2.itm~   ~override~ // <Invalid Strref -1> - causes level drain - unknown long effect
              ~mindfl02.itm~ ~override~ // Skull - causes level drain
              ~miscbc.itm~   ~override~ // Blackrazor +3 - cures fear - causes level drain - portrait icon 21 - unknown long effect - unknown long effect
              ~mistva.itm~   ~override~ // Skull - causes level drain - unknown long effect
              ~mistva2.itm~  ~override~ // Skull - causes level drain
              ~ohbskiss.spl~ ~override~ // Oh, don't be such a preposterously petulant persnicket. I'll tell you what—because you've been so gracious about all this kidnapping and forced to fight to the death business, I'll give you a reward! - causes level drain
              ~ohhnecr1.spl~ ~override~ // Level Drain - causes level drain
              ~ohhnecr2.spl~ ~override~ // Level Drain - causes level drain
              ~ohhnecr3.spl~ ~override~ // Level Drain - causes level drain
              ~ohhnecr4.spl~ ~override~ // Level Drain - causes level drain
              ~ohhnecr5.spl~ ~override~ // Level Drain - causes level drain
              ~ohhwrsw.itm~  ~override~ // Attack - causes level drain
              ~slaysh01.itm~ ~override~ // <Invalid Strref -1> - causes level drain - unknown long effect
              ~spectr.itm~   ~override~ // <Invalid Strref -1> - causes level drain
              ~spidwr.itm~   ~override~ // Ghoul hand - causes level drain
              ~spin571.spl~  ~override~ // Energy Drain - causes level drain
              ~spin586.spl~  ~override~ // <Invalid Strref -1> - causes level drain
              ~spin587.spl~  ~override~ // <Invalid Strref -1> - causes level drain
              ~spin666.spl~  ~override~ // Level Drain - causes level drain
              ~spin878.spl~  ~override~ // Level Drain - causes blind - causes level drain - unknown long effect
              ~spin893.spl~  ~override~ // Shadow Dragon Breath - causes blind - causes level drain - unknown long effect
              ~spwatt5.itm~  ~override~ // Attack - causes hold - causes level drain
              ~spwi914.spl~  ~override~ // Energy Drain - causes level drain
              ~spwish19.spl~ ~override~ // Energy Drain - causes level drain
              ~sw1h59.itm~   ~override~ // Short Sword of Mask +5 - causes level drain - unknown long effect - portrait icon 144 - unknown long effect - unknown long effect - plays sound EFF_M22A
              ~sw2h18.itm~   ~override~ // Gram the Sword of Grief +5 - causes level drain
              ~sw2hdeat.itm~ ~override~ // Soul Reaver +4 - causes level drain
              ~telslav.itm~  ~override~ // <Invalid Strref -1> - causes level drain
              ~telwrai.itm~  ~override~ // <Invalid Strref -1> - causes level drain
              ~vamp.itm~     ~override~ // <Invalid Strref -1> - causes level drain
              ~vamp1.itm~    ~override~ // <Invalid Strref -1> - causes level drain
              ~vamp2.itm~    ~override~ // <Invalid Strref -1> - causes level drain
              ~vamp3.itm~    ~override~ // <Invalid Strref -1> - causes level drain
              ~wight.itm~    ~override~ // <Invalid Strref -1> - causes level drain
              ~wolfspir.itm~ ~override~ // Attack - causes level drain - unknown long effect
              ~wraith1.itm~  ~override~ // Attack - causes level drain
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END
*/

COPY_EXISTING ~cdpr417.spl~  ~override~ // Lesser Restoration - cures level drain
              ~globblu2.itm~ ~override~ // Blue Globe - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~ohbresto.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~ohsmode1.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohsmode4.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~spin581.spl~  ~override~ // <Invalid Strref -1> - cures level drain
              ~sppr417.spl~  ~override~ // Lesser Restoration - cures level drain
              ~sppr713.spl~  ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~spwish07.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~spwish46.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
  LPF cd_apply_batch STR_VAR array_name = cd_cure_leveldrain END
  BUT_ONLY

/////                                                  \\\\\
///// nondetection                                     \\\\\
/////                                                  \\\\\

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur70.spl~
  PATCH_FOR_EACH res IN
//              ~clck06.itm~   ~override~ // Whispers of Silence - causes nondetection
//              ~comps37.itm~  ~override~ // Taragarth the Bloodbrand +1 - causes nondetection
//              ~misc5x.itm~   ~override~ // Harper Pin - causes nondetection
//              ~ohbcutsc.cre~ ~override~ // <Invalid Strref -1> - causes invisibility - causes nondetection
//              ~ohrring2.itm~ ~override~ // Ring - causes invisibility - causes nondetection
//              ~spin698.spl~  ~override~ // Improved Invisibility - causes invisibility - causes nondetection
    spwi310 // (spl) Non-Detection - causes nondetection - portrait icon 31 - plays sound EFF_E04 [expiry sound]
//              ~sw1h37.itm~   ~override~ // Taragarth the Bloodbrand +1 - causes nondetection
//              ~swordi.itm~   ~override~ // <Invalid Strref -1> - causes invisibility - causes nondetection
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END

COPY_EXISTING ~ohbddeti.spl~ ~override~ // <Invalid Strref -1> - cures invisibility - cures nondetection
  LPF cd_apply_batch STR_VAR array_name = cd_cure_nondetection END
  BUT_ONLY

/////                                                  \\\\\
///// pause                                            \\\\\
/////                                                  \\\\\

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur270.spl~
  PATCH_FOR_EACH res IN
//              ~ohbsuza1.spl~ ~override~ // <Invalid Strref -1> - cures deafness - cures feeblemind - causes pause - plays animation OHBGOLD - unknown long effect
//              ~ohhdrai2.spl~ ~override~ // <Invalid Strref -1> - causes pause - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect
//              ~ohhdrain.spl~ ~override~ // Blood Drain - causes pause
//              ~spdd03.spl~   ~override~ // Breath Weapon - causes pause
//              ~spin539.spl~  ~override~ // Magma Ball - causes pause
//              ~spin937.spl~  ~override~ // Color Spray - causes pause - causes sleep - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect
//              ~spin942.spl~  ~override~ // Breathes Grit - causes pause
//              ~spwi103.spl~  ~override~ // Burning Hands - causes pause
//              ~spwi105.spl~  ~override~ // Color Spray - causes pause - causes sleep - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect
//              ~spwi217.spl~  ~override~ // Agannazar's Scorcher - causes pause
    spwi516 // (spl) Conjure Lesser Fire Elemental - causes pause - plays animation SPELEMND - portrait icon 131 [mental combat junk]
    spwi520 // (spl) Conjure Lesser Air Elemental - causes pause - plays animation SPELEMND - portrait icon 131 [mental combat junk]
    spwi521 // (spl) Conjure Lesser Earth Elemental - causes pause - plays animation SPELEMND - portrait icon 131 [mental combat junk]
    spwi620 // (spl) Conjure Fire Elemental - causes pause - plays animation SPELEMND - portrait icon 131 [mental combat junk]
    spwi621 // (spl) Conjure Air Elemental - causes pause - plays animation SPELEMND - portrait icon 131 [mental combat junk]
    spwi622 // (spl) Conjure Earth Elemental - causes pause - plays animation SPELEMND - portrait icon 131 [mental combat junk]
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END

COPY_EXISTING ~spin873.spl~  ~override~ // <Invalid Strref -1> - cures pause
  LPF cd_apply_batch STR_VAR array_name = cd_cure_pause END
  BUT_ONLY

/////                                                  \\\\\
///// poison                                           \\\\\
/////                                                  \\\\\

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur11.spl~
  PATCH_FOR_EACH res IN
//              ~abisred1.itm~ ~override~ // Skull - causes poison
//              ~acidooz3.itm~ ~override~ // Broken Shield - causes poison - unknown long effect - unknown long effect
  acidooz4 // Broken Shield - causes poison [has delayed kill effect tied to poison]
//              ~arow05.itm~   ~override~ // Arrow of Biting - causes poison
//              ~arow12.itm~   ~override~ // Arrow of Biting - causes poison
//              ~arow14.itm~   ~override~ // Poisoned Arrow - causes poison
//              ~barlfl.itm~   ~override~ // Flail - causes poison
//              ~basilg3.itm~  ~override~ // Attack - causes poison
//              ~bdpweapn.spl~ ~override~ // <Invalid Strref -1> [has 206 to prevent poison stacking & damage, but leaving in place]
//              ~bdsha01b.spl~ ~override~ // <Invalid Strref -1> - causes poison
    bhaal2b // Dark Taint - causes poison - portrait icon 6 - plays sound EFF_E07 [has seemingly unrelated slow effect, but since that's blocked by poison immunity, choose to remove all]
//              ~bolt04.itm~   ~override~ // Bolt of Biting  - causes poison
//              ~chalcy1.itm~  ~override~ // The Shadow's Blade +3 - causes poison
//              ~comps38.itm~  ~override~ // Jhor the Bleeder +2 - causes poison
//              ~cornugon.itm~ ~override~ // Skull - causes poison - causes stun
//              ~dagg16.itm~   ~override~ // Poisoned Throwing Dagger - causes poison
//              ~dart04.itm~   ~override~ // Dart of Wounding - causes poison
//              ~dart05.itm~   ~override~ // Asp's Nest +1 - causes poison
//              ~demabi01.itm~ ~override~ // Skull - causes poison
//              ~etterc.itm~   ~override~ // Ghoul hand - causes poison
//              ~etterc2.itm~  ~override~ // Attack - causes poison
//              ~figspid.itm~  ~override~ // Attack - causes poison
//              ~gbasil.itm~   ~override~ // Ghoul hand - causes poison
//              ~gispid.itm~   ~override~ // Ghoul hand - causes poison
//              ~gordem2.itm~  ~override~ // Skull - causes poison
//              ~gorsnake.itm~ ~override~ // Skull - causes poison - causes stun
//              ~hlolth.itm~   ~override~ // Handmaiden's Mace +2 - causes poison
//              ~huspid.itm~   ~override~ // Ghoul hand - causes poison
//              ~impclaw.itm~  ~override~ // Attack - causes poison
    jellgr1  // (itm) Broken Shield - causes poison [has delayed kill effect tied to poison]
//              ~jellmu1.itm~  ~override~ // Attack - causes poison - unknown long effect - unknown long effect
//              ~jellmu2.itm~  ~override~ // Broken Shield - causes poison - unknown long effect - unknown long effect
//              ~marili.itm~   ~override~ // Sword of Flame +1 - causes poison
//              ~misc1i.itm~   ~override~ // Belladonna Flowers - causes poison
//              ~misc75.itm~   ~override~ // Dagger of Venom +2 - causes poison
//              ~mistpo.itm~   ~override~ // Attack - causes poison
//              ~nebdag.itm~   ~override~ // Neb's Nasty Cutter +2 - causes poison
//              ~npsw04.itm~   ~override~ // Corthala Family Blade - causes poison
//              ~npsw05.itm~   ~override~ // Entropy +2 - causes poison
//              ~ohbdpitf.itm~ ~override~ // Attack - causes poison
//              ~ohhphrey.itm~ ~override~ // Soultaker Dagger - causes poison
//              ~ohhspid1.itm~ ~override~ // Attack - causes poison
//              ~ohnsnake.itm~ ~override~ // Skull - causes poison
//              ~phspid.itm~   ~override~ // Ghoul hand - causes poison
//              ~plyjelly.itm~ ~override~ // Attack - causes poison - unknown long effect - unknown long effect
//              ~plyspid.itm~  ~override~ // Attack - causes poison
//              ~plywyvrn.itm~ ~override~ // Attack - causes poison
//              ~poisa.itm~    ~override~ // <Invalid Strref -1> - causes poison
//              ~poisf.itm~    ~override~ // Ghoul hand - causes poison
//              ~poisk.itm~    ~override~ // Ghoul hand - causes poison
//              ~poisspid.itm~ ~override~ // <Invalid Strref -1> - causes poison
//              ~polyjell.itm~ ~override~ // Attack - causes poison - unknown long effect - unknown long effect
//              ~potn48.itm~   ~override~ // Vial of Mysterious Liquid - causes poison
//              ~ravag02.itm~  ~override~ // Boneblade +4 - causes poison - causes stun
    scrl17 // (itm)Cursed Scroll of Ailment - causes poison - plays sound EFF_E05 [has delayed kill effect tied to poison]
//              ~sendai.itm~   ~override~ // Drow Flail +3 - causes poison - unknown long effect - unknown long effect
//              ~senspi01.itm~ ~override~ // <Invalid Strref -1> - causes poison [has kill effect tied to poison, but it's instant]
//              ~sharswd.itm~  ~override~ // Bastard Sword +1 - causes poison - unknown long effect - unknown long effect - unknown long effect - portrait icon 91
//              ~snakspir.itm~ ~override~ // Attack - causes poison
//              ~spcl422.spl~  ~override~ // <Invalid Strref -1> - causes poison - unknown long effect
//              ~spidgi1.itm~  ~override~ // Attack - causes poison
//              ~spidhu1.itm~  ~override~ // <Invalid Strref -1> - causes poison
//              ~spidph1.itm~  ~override~ // Attack - causes poison
//              ~spidvo01.itm~ ~override~ // <Invalid Strref -1> - causes poison [has kill effect tied to poison, but it's instant]
//              ~spin583.spl~  ~override~ // <Invalid Strref -1> - causes poison
//              ~spin707.spl~  ~override~ // <Invalid Strref -1> - causes poison
//              ~spin733.spl~  ~override~ // Wish - causes poison
//              ~spin979.spl~  ~override~ // Gas Cloud - causes poison
    sppr411 // (spl) Poison - causes poison [has expiry sound, color pulse]
    sppr610 // (spl) Dolorous Decay - causes poison [has expiry sound and slow effect, but since that's blocked by poison immunity, choose to remove all]
//              ~sppr722.spl~  ~override~ // Storm of Vengeance - causes poison - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect
    spsatt1 // (itm) Attack - causes poison [expiry sound]
    spsatt2 // (itm) Attack - causes poison [expiry sound]
    spsatt3 // (itm) Attack - causes poison [expiry sound]
    spsatt4 // (itm) Attack - causes poison [expiry sound]
    spsatt5 // (itm) Attack - causes poison [expiry sound]
//              ~spspid.itm~   ~override~ // <Invalid Strref -1> - causes poison
//              ~spspid3.itm~  ~override~ // <Invalid Strref -1> - causes poison
//              ~spwi008.spl~  ~override~ // <Invalid Strref -1> - causes poison
//              ~spwi019.spl~  ~override~ // <Invalid Strref -1> - causes poison
//              ~staf23.itm~   ~override~ // Serpent Shaft - causes poison
//              ~sw1h38.itm~   ~override~ // Jhor the Bleeder +2 - causes poison
//              ~waninja.itm~  ~override~ // Ninjatō of the Scarlet Brotherhood +3 - causes poison
//              ~werewyv.itm~  ~override~ // Skull - causes poison
//              ~wyvern.itm~   ~override~ // Ghoul hand - causes poison
//              ~wyvern2.itm~  ~override~ // Attack - causes poison
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END

COPY_EXISTING ~amsoul01.itm~ ~override~ // Malla's Soul Stone - cures blind - cures deafness - cures disease - cures poison
              ~amul22.itm~   ~override~ // Periapt of Proof Against Poison - cures drunkenness - cures poison
              ~bhaal1a.spl~  ~override~ // Mass Healing - cures blind - cures deafness - cures disease - cures drunkenness - cures poison
              ~bpdispel.spl~ ~override~ // <Invalid Strref -1> - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun
              ~brac20.itm~   ~override~ // Gloves of Healing - cures drunkenness - cures poison
              ~cdhgtrl.spl~  ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtorgal.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtrlblz.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~devaheal.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~globblu2.itm~ ~override~ // Blue Globe - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~misc76.itm~   ~override~ // The Dream Potion - cures poison
              ~ohbbclt1.spl~ ~override~ // <Invalid Strref -1> - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~ohbresto.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~ohsmode1.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohsmode4.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~potn17.itm~   ~override~ // Elixir of Health - cures disease - cures poison - causes drunkenness
              ~potn20.itm~   ~override~ // Antidote - cures poison
              ~potn47.itm~   ~override~ // Marek's Potion of Antidote - cures poison
              ~potnmare.itm~ ~override~ // Marek's Potion of Antidote - cures poison
              ~scrl08.itm~   ~override~ // Protection From Poison - cures poison
              ~senspihe.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spin102.spl~  ~override~ // Slow Poison - cures drunkenness - cures poison
              ~spin201.spl~  ~override~ // Neutralize Poison - cures blind - cures deafness - cures disease - cures poison
              ~spin599.spl~  ~override~ // <Invalid Strref -1> - cures disease - cures poison
              ~spin679.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spin699.spl~  ~override~ // Healing Lick - cures blind - cures deafness - cures disease - cures poison
              ~spin711.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spin734.spl~  ~override~ // Wish - cures blind - cures deafness - cures disease - cures drunkenness - cures poison
              ~spin746.spl~  ~override~ // <Invalid Strref -1> - cures disease - cures poison
              ~sppr404.spl~  ~override~ // Neutralize Poison - cures blind - cures deafness - cures disease - cures poison
              ~sppr607.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~sppr713.spl~  ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~spwish07.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~spwish28.spl~ ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~spwish46.spl~ ~override~ // Greater Restoration - cures confusion - cures disease - cures feeblemind - cures fear - cures level drain - cures poison
              ~spwm168.spl~  ~override~ // Heal - cures blind - cures deafness - cures disease - cures drunkenness - cures feeblemind - cures poison
              ~staf10.itm~   ~override~ // Staff of Curing - cures disease - cures drunkenness - cures poison
              ~trollreg.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
  LPF cd_apply_batch STR_VAR array_name = cd_cure_poison END
  BUT_ONLY

/////                                                  \\\\\
///// silence                                          \\\\\
/////                                                  \\\\\

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur48.spl~
  PATCH_FOR_EACH res IN
//              ~misc3l.itm~   ~override~ // Horn of Silence - causes silence - portrait icon 34 - plays animation ICWRATI
    spin692 // (spl) Silence, 15' Radius - causes silence - portrait icon 34 - plays sound EFF_E06 [expiry sound]
    spin998 // (spl) Silence, 15' Radius - causes silence - portrait icon 34 - plays sound EFF_E06 [expiry sound]
    sppr211 // (spl) Silence, 15' Radius - causes silence - portrait icon 34 - plays sound EFF_E06 [expiry sound]
    sppr988 // (spl) Silence, 15' Radius - causes silence - portrait icon 34 - plays sound EFF_E06 [expiry sound]
    spwi612 // (spl) Power Word, Silence - causes silence - portrait icon 34 - plays sound EFF_E06 [expiry sound]
    spwish35 // (spl) Power Word, Silence - causes silence - portrait icon 34 - plays sound EFF_E06 [expiry sound]
//              ~sw1h36.itm~   ~override~ // Namarra +2 - causes silence - portrait icon 34
//              ~wand19.itm~   ~override~ // Wand of Cursing - causes blind - causes deafness - causes silence [has expiry sound, but conflated with blind and deaf]
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END

COPY_EXISTING ~amul21.itm~   ~override~ // Amulet of Power - cures silence
              ~bdhelm11.itm~ ~override~ // Bard Hat - cures deafness - cures silence
              ~spwi219.spl~  ~override~ // Vocalize - cures silence
              ~sw1h50.itm~   ~override~ // Shazzellim +1 - cures silence
  LPF cd_apply_batch STR_VAR array_name = cd_cure_silence END
  BUT_ONLY

/////                                                  \\\\\
///// sleep                                            \\\\\
/////                                                  \\\\\

// shunt enemy effects in emotion, hopelessness to subspell
OUTER_SET sleep_immunity = IDS_OF_SYMBOL (~splstate~ ~SLEEP_IMMUNITY~)
COPY_EXISTING ~spwi411.spl~  ~override/spwi411b.spl~ // Emotion: Hopelessness - cures fear - causes sleep
  LPF DELETE_EFFECT INT_VAR match_target = 1 END
  LPM cd_make_subspell 
  LPF CLONE_EFFECT INT_VAR match_opcode = 39 opcode = 324 parameter1 = sleep_immunity parameter2 = 110 timing = 0 duration = 0 STR_VAR insert = first resource = EVAL ~%DEST_RES%~ END

COPY_EXISTING ~spwi411.spl~  ~override~ // Emotion: Hopelessness - cures fear - causes sleep
  LPF ALTER_EFFECT INT_VAR match_opcode = 39 target = 3 opcode = 146 parameter1 = 0 parameter2 = 2 timing = 1 duration = 0 special = 0 STR_VAR resource = spwi411b END
  LPF DELETE_EFFECT INT_VAR match_target = 2 END
  LPF ALTER_EFFECT INT_VAR match_target = 3 target = 2 END

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur2.spl~
  PATCH_FOR_EACH res IN
//              ~abzaway.spl~  ~override~ // <Invalid Strref -1> - causes sleep [unconsciousness from knockback]
//              ~aurstaf.itm~  ~override~ // Staff of the Ram +4 - causes sleep [unconsciousness from knockback]
//              ~ax1h16.itm~   ~override~ // K'logarath +4 - causes sleep [unconsciousness from knockback]
//              ~balth01.spl~  ~override~ // Solar Stance! - causes sleep [unconsciousness from knockback]
//              ~balth09.spl~  ~override~ // Shadowless Kick! - causes sleep [unconsciousness from knockback]
//              ~bdsha12c.spl~ ~override~ // <Invalid Strref -1> - causes sleep
//              ~blun16.itm~   ~override~ // The Sleeper +2 - causes sleep
//              ~cdfampsd.itm~ ~override~ // Attack - causes sleep
//              ~cdhgtrl.spl~  ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
//              ~cdtorgal.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
//              ~cdtrlblz.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
//              ~ch3away.spl~  ~override~ // <Invalid Strref -1> - causes sleep [unconsciousness from knockback]
//              ~ch3drain.spl~ ~override~ // <Invalid Strref -1> - causes sleep - unknown long effect - unknown long effect - unknown long effect - unknown long effect
//              ~ch3flash.spl~ ~override~ // <Invalid Strref -1> - causes sleep - unknown long effect
//              ~ch3weak.spl~  ~override~ // <Invalid Strref -1> - causes sleep
//              ~d1skel.cre~   ~override~ // Gorion - causes sleep
//              ~dagg13.itm~   ~override~ // Pixie Prick +3 - causes sleep
//              ~dgwhirl.spl~  ~override~ // <Invalid Strref -1> - causes sleep [unconsciousness from knockback]
//              ~dwbolt01.itm~ ~override~ // Drow Bolt of Sleep - causes sleep
//              ~jwfall.spl~   ~override~ // <Invalid Strref -1> - causes sleep
//              ~jwsiege.spl~  ~override~ // <Invalid Strref -1> - causes sleep
//              ~jwsleep.spl~  ~override~ // <Invalid Strref -1> - causes sleep
//              ~jwwhirl.spl~  ~override~ // <Invalid Strref -1> - causes sleep [unconsciousness from knockback]
//              ~ohbbclt0.spl~ ~override~ // <Invalid Strref -1> - causes sleep [unconsciousness from knockback]
//              ~ohbbrvgr.itm~ ~override~ // Skull - cures deafness - cures feeblemind - causes sleep [unconsciousness from knockback]
//              ~ohbquake.spl~ ~override~ // Earthquake - causes sleep [extended effects tied to earthquake and not sleep]
//              ~ohddivrt.spl~ ~override~ // Divine Retribution - causes sleep - portrait icon 105 - unknown long effect - unknown long effect
//              ~ohdmask.spl~  ~override~ // Breathe Acid - causes sleep
//              ~ohrgrog.spl~  ~override~ // <Invalid Strref -1> - causes sleep
//              ~psdclaw.itm~  ~override~ // Attack - causes sleep
//              ~ravag01.itm~  ~override~ // Skull - cures deafness - cures feeblemind - causes sleep [unconsciousness from knockback]
//              ~sleep.itm~    ~override~ // <Invalid Strref -1> - causes sleep
//              ~spcl751a.spl~ ~override~ // <Invalid Strref -1> - causes confusion - causes sleep
//              ~spcl911b.spl~ ~override~ // <Invalid Strref -1> - causes sleep [unconsciousness from knockback]
    sper12 // (itm) Ixil's Spike +6 - cures hold - cures stun - causes sleep [has delayed damage from sleep (target is "pinned")]
//              ~spin531.spl~  ~override~ // Abazigal Shockwave - causes sleep - portrait icon 105 - unknown long effect - unknown long effect
//              ~spin547.spl~  ~override~ // Project Force - causes sleep [unconsciousness from knockback]
//              ~spin600.spl~  ~override~ // <Invalid Strref -1> - causes sleep [has expiry sound, but cutscene spell with 3-second sleep]
//              ~spin643.spl~  ~override~ // <Invalid Strref -1> - causes sleep [unconsciousness from knockback]
//              ~spin656.spl~  ~override~ // <Invalid Strref -1> - causes sleep
//              ~spin658.spl~  ~override~ // <Invalid Strref -1> - causes sleep [unconsciousness from knockback]
//              ~spin695.spl~  ~override~ // Wing Buffet - causes sleep [unconsciousness from knockback]
//              ~spin775.spl~  ~override~ // Psionic Blast - causes sleep
//              ~spin802.spl~  ~override~ // Psychic Drain - causes sleep
//              ~spin892.spl~  ~override~ // Sleep - causes sleep
    spin937 // (spl) Color Spray - causes pause - causes sleep [sets colors for sleep duration]
    spin940 // (spl) Stinking Cloud - causes sleep - plays sound EFF_E05 [expiry sound]
//              ~spin966.spl~  ~override~ // <Invalid Strref -1> - causes sleep
//              ~spogre01.spl~ ~override~ // Earthquake - causes sleep [extended effects tied to earthquake and not sleep]
    sppr102  // (spl) Command - causes sleep - plays sound EFF_E05 [expiry sound]
    sppr512 // (spl) Greater Command - causes sleep - plays sound EFF_E07 [expiry sound]
//              ~sppr720.spl~  ~override~ // Earthquake - causes sleep [extended effects tied to earthquake and not sleep]
//              ~spwi004.spl~  ~override~ // Stinking Cloud - causes sleep
    spwi105 // (spl) Color Spray - causes pause - causes sleep [sets colors for sleep duration]
    spwi116 // Sleep - causes sleep - plays sound EFF_E05 [expiry sound]
//              ~spwi213.spl~  ~override~ // Stinking Cloud - causes sleep
//    spwi220 // (spl) Power Word, Sleep - causes sleep [attaches permanent color pulse to target]
//              ~spwi411.spl~  ~override~ // Emotion: Hopelessness - cures fear - causes sleep [sleep and related effects shunted to subspell]
    spwi411b // (spl) Emotion: Hopelessness - new subspell for sleep et al [has spellstate and expiry sound]
//              ~spwi711.spl~  ~override~ // Sphere of Chaos - causes confusion - causes hold - causes sleep - unknown long effect
//              ~spwi922.spl~  ~override~ // Dragon's Breath - causes sleep [unconsciousness from knockback]
//              ~spwi925.spl~  ~override~ // Comet - causes sleep [unconsciousness from knockback]
//              ~spwish27.spl~ ~override~ // Knockback - causes sleep [unconsciousness from knockback]
//              ~spwm187.spl~  ~override~ // Stinking Cloud - causes sleep
//              ~spyanc01.spl~ ~override~ // Whirlwind - causes sleep [unconsciousness from knockback]
//              ~staf15.itm~   ~override~ // Staff of Air +2 - causes sleep - unknown long effect
//              ~staf21.itm~   ~override~ // Staff of the Ram +4 - causes sleep [unconsciousness from knockback]
//              ~staf22.itm~   ~override~ // Staff of the Ram +6 - causes sleep [unconsciousness from knockback]
//              ~trollreg.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
//              ~wand08.itm~   ~override~ // Wand of Sleep - causes sleep
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END

COPY_EXISTING ~bpdispel.spl~ ~override~ // <Invalid Strref -1> - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun
              ~cdhgtrl.spl~  ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtorgal.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtrlblz.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~ohncoll.itm~  ~override~ // Collar Bell - cures sleep - causes deafness - portrait icon 112
              ~ohsmode1.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohsmode4.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohtyr1.spl~   ~override~ // Exaltation - cures berserk - cures confusion - cures drunkenness - cures feeblemind - cures fear - cures sleep
              ~ohwakeup.spl~ ~override~ // <Invalid Strref -1> - cures sleep
              ~trollreg.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
  LPF cd_apply_batch STR_VAR array_name = cd_cure_sleep END
  BUT_ONLY

/////                                                  \\\\\
///// stun                                             \\\\\
/////                                                  \\\\\

// chromatic orb stuns at levels 5 and 7; don't want to roll back entire spell for two levels of blind so we subspell it
COPY_EXISTING ~spdr101.spl~  ~override~ // Chromatic Orb (druid)
              ~spwi118.spl~  ~override~ // Chromatic Orb (arcane)
  LPF DELETE_EFFECT INT_VAR match_opcode = 45 END // delete stun effect from headers 4 and 6
  LPF DELETE_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14043 END // delete stun string from headers 4 and 6
  LPF ALTER_EFFECT INT_VAR header = 4 match_opcode = 174 match_timing = 4 opcode = 146 parameter2 = 2 timing = 1 duration = 0 STR_VAR match_resource = eff_e05 resource = spwi118e END // change expiry sounds to spell casts
  LPF ALTER_EFFECT INT_VAR header = 6 match_opcode = 174 match_timing = 4 opcode = 146 parameter2 = 2 timing = 1 duration = 0 STR_VAR match_resource = eff_e05 resource = spwi118g END // change expiry sounds to spell casts
  
// create stun subspells for chromatic orb
OUTER_SET stun_immunity = IDS_OF_SYMBOL (~splstate~ ~STUN_IMMUNITY~)
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/spwi118e.spl~ // create blind subspell for header 0 
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 parameter1 = stun_immunity parameter2 = 110 STR_VAR resource = EVAL ~%DEST_RES%~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 45 target = 2 duration = 18 END // add stun effect
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 139 target = 2 parameter1 = 14043 timing = 1 END // add stun string
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 174 target = 2 timing = 4 duration = 18 STR_VAR resource = eff_e05 END // add expiry sound
COPY_EXISTING ~spwi118e.spl~ ~override/spwi118g.spl~ // create blind subspell for header 3 
  LPF ALTER_EFFECT INT_VAR match_duration = 18 duration = 120 END

// shunt stun effects into spell
COPY_EXISTING ~icetrl.itm~   ~override~ // Attack - causes stun - unknown long effect - unknown long effect
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 opcode = 146 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = icetrlst END
  LPF DELETE_EFFECT INT_VAR match_duration = 18 END

COPY ~eefixpack/files/spl/cdcure.spl~ ~override/icetrlst.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 parameter1 = stun_immunity parameter2 = 110 STR_VAR resource = EVAL ~%DEST_RES%~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode =  45 target = 2 duration = 18 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode =   7 target = 2 parameter1 = 71 parameter2 = 3 duration = 18 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 139 target = 2 parameter1 = 1280 timing = 1 END

// stuff that causes stun and plays spmindat should be updated to play cdstun instead
COPY_EXISTING ~fampsdat.itm~ ~override~ // skull - causes stun - plays spmindat
              ~spin974.spl~  ~override~ // psionic blast - causes stun - plays spmindat
  LPF ALTER_EFFECT INT_VAR match_opcode = 215 STR_VAR match_resource = spmindat resource = cdstun END

// update anything which provides immunity to stun by ALTERING immunity to the spmindat animation
COPY_EXISTING ~hslaywpn.itm~ ~override~ // <invalid strref -1> - immune to stun - blocks spconfus - blocks spmindat
              ~ohbbslay.itm~ ~override~ // <invalid strref -1> - immune to stun - blocks spconfus - blocks spmindat
              ~slayerw1.itm~ ~override~ // <invalid strref -1> - immune to stun - blocks spconfus - blocks spmindat
              ~slayerw3.itm~ ~override~ // attack - blocks cdhorror - cures fear - immune to confusion - immune to stun - immune to fear - immune to stun - blocks spconfus - blocks spmindat
              ~slayerwp.itm~ ~override~ // <invalid strref -1> - immune to stun - blocks spconfus - blocks spmindat
  LPF ALTER_EFFECT INT_VAR match_opcode = 296 STR_VAR match_resource = spmindat resource = cdstun END
  BUT_ONLY

// create resource removal spell
COPY ~eefixpack/files/spl/cdcure.spl~ ~override/cdcur46.spl~
  PATCH_FOR_EACH res IN
//              ~bdsha06a.spl~ ~override~ // <Invalid Strref -1> - causes stun
//              ~bolt07.itm~   ~override~ // Flasher Master Bruiser Mate - causes stun
//              ~carrio.itm~   ~override~ // Ghoul hand - causes stun
//              ~cdstaf12.spl~ ~override~ // Lightning Bolt - causes stun
//              ~cornugon.itm~ ~override~ // Skull - causes poison - causes stun
//              ~dart03.itm~   ~override~ // Dart of Stunning - causes stun
//              ~dartmel.itm~  ~override~ // Bone Dagger - causes disease - causes stun
//              ~demcor01.itm~ ~override~ // Skull - causes stun
//              ~deva.itm~     ~override~ // Mace of Disruption +2 - cures deafness - cures feeblemind - causes stun
//              ~dwbolt02.itm~ ~override~ // Drow Bolt of Stunning - causes stun
//              ~dwfpsmst.spl~ ~override~ // <Invalid Strref -1> - causes stun
//              ~elemhydr.itm~ ~override~ // Skull - cures deafness - cures feeblemind - causes stun - plays animation SPFIRESB - plays animation SPFIRESA - unknown long effect
    fampsdat // (itm) Skull - causes stun - plays animation cdstun
//              ~ghoulc.itm~   ~override~ // Ghoul hand - causes stun
//              ~goltome4.itm~ ~override~ // Attack - causes stun - unknown long effect
//              ~gorcamb.itm~  ~override~ // Two-handed Sword +2 - causes stun - unknown long effect - unknown long effect - unknown long effect - portrait icon 91
//              ~gorsnake.itm~ ~override~ // Skull - causes poison - causes stun
//              ~icetrl.itm~   ~override~ // Attack - causes stun - [stun and related effects shunted to spell]
    icetrlst // (spl) Attack - causes stun - [stun effects from icetrl.itm routed here]
//              ~kuobolt.itm~  ~override~ // Kuo-toan Bolt - causes stun
//              ~kuobolt2.itm~ ~override~ // Kuo-toan Bolt - causes stun
//              ~mepsal.itm~   ~override~ // Skull - causes stun
//              ~misc3h.itm~   ~override~ // Horn of Blasting - causes stun
//              ~mistwa.itm~   ~override~ // Skull - causes stun
//              ~ohbdcorn.spl~ ~override~ // Paralyze - causes stun - unknown long effect
//              ~ohbdeva.itm~  ~override~ // Mace of Disruption +2 - causes stun
//              ~ohhdag01.itm~ ~override~ // The Jade Fang +3 - causes stun - unknown long effect
//              ~paracarr.itm~ ~override~ // Ghoul hand - causes stun
//              ~paraghas.itm~ ~override~ // Ghoul Touch - causes stun - unknown long effect - portrait icon 126
//              ~paraghou.itm~ ~override~ // Ghoul Touch - causes stun
//              ~ravag02.itm~  ~override~ // Boneblade +4 - causes poison - causes stun
//              ~sahbolt.itm~  ~override~ // Paralytic Bolt +1 - causes stun
//              ~sareveff.spl~ ~override~ // <Invalid Strref -1> - causes stun
//              ~slng06.itm~   ~override~ // Sling of Arvoreen +4 - causes stun
//              ~spcl123.spl~  ~override~ // <Invalid Strref -1> - causes stun - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect - unknown long effect
//              ~spdr101.spl~  ~override~ // Chromatic Orb - causes blind - causes stun - plays sound EFF_E05 [stun expiry sound shunted to spwi118c.spl]
//              ~spin543.spl~  ~override~ // Inflict Pain - causes stun
//              ~spin727.spl~  ~override~ // Psionic Blast - causes stun
//              ~spin832.spl~  ~override~ // Silver Dragon Paralyzation - causes stun
//              ~spin834.spl~  ~override~ // Psionic Blast - causes stun
//              ~spin909.spl~  ~override~ // Ego Whip - causes stun
//              ~spin926.spl~  ~override~ // Water Jet - causes stun
//              ~spin927.spl~  ~override~ // Boiling Rain Storm - causes stun
//              ~spin934.spl~  ~override~ // Salt Crystals - causes stun
//              ~spin959.spl~  ~override~ // Psionic Blast - causes stun
    spin974 // (spl) Psionic Blast - causes stun - plays animation cdstun [ongoing animation]
//              ~sppr710.spl~  ~override~ // Holy Word - causes deafness - causes stun - [has multiple, unrelated effects]
//              ~sppr715.spl~  ~override~ // Unholy Word - causes deafness - causes stun - [has multiple, unrelated effects]
    sppr718 // (spl) Symbol, Stun - causes stun - plays sound EFF_E05 [expiry sound]
    sppr984 // (spl) Chromatic Orb - causes stun - plays sound EFF_E05 [expiry sound; limited edition of chromatic orb]
//              ~spwi118.spl~  ~override~ // Chromatic Orb - causes blind - causes stun - plays sound EFF_E05 [stun expiry sound shunted to spwi118c.spl]
    spwi118e // (spl) Chromatic Orb - causes blind - causes stun - plays sound EFF_E05 [stun expiry sound shunted here]
    spwi118g // (spl) Chromatic Orb - causes blind - causes stun - plays sound EFF_E05 [stun expiry sound shunted here]
    spwi816 // (spl) Symbol, Stun - causes stun - plays sound EFF_E05 [expiry sound]
    spwi898 // (spl) Symbol, Stun - causes stun - plays sound EFF_E05 [expiry sound]
//              ~spwm152.spl~  ~override~ // Polymorph Other - causes stun
//              ~staf13.itm~   ~override~ // Staff of Thunder and Lightning +2 - causes stun - plays animation SPSTRENH
//              ~sw1h51.itm~   ~override~ // Celestial Fury +3 - causes blind - causes stun - unknown long effect
//              ~wand04.itm~   ~override~ // Wand of Paralyzation - causes stun
  BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 1 STR_VAR resource = EVAL ~%res%~ END
  END

COPY_EXISTING ~blun30.itm~   ~override~ // Flail of Ages +5 - cures hold - cures stun
              ~bpdispel.spl~ ~override~ // <Invalid Strref -1> - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun
              ~cdhgtrl.spl~  ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtorgal.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~cdtrlblz.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
              ~misc3o.itm~   ~override~ // Methild's Harp - cures hold - cures stun
              ~npplat.itm~   ~override~ // Firecam Full-Plate Armor - cures hold - cures stun
              ~ohrrage.spl~  ~override~ // Animal Rage - cures fear - cures stun
              ~ohsmode1.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~ohsmode4.spl~ ~override~ // [story mode] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, level drain, poison, sleep, stun
              ~potn45.itm~   ~override~ // Potion of Freedom - cures hold - cures stun
              ~ring09.itm~   ~override~ // Edventar's Gift - cures hold - cures stun
              ~spcl152.spl~  ~override~ // Barbarian Rage - cures fear - cures stun
              ~spcl321.spl~  ~override~ // Enrage - cures fear - cures stun
              ~sper12.itm~   ~override~ // Ixil's Spike +6 - cures hold - cures stun - causes sleep - unknown long effect - unknown long effect
              ~sppr308.spl~  ~override~ // Remove Paralysis - cures hold - cures stun
              ~sppr403.spl~  ~override~ // Free Action - cures hold - cures stun
              ~sprngb03.itm~ ~override~ // <1pp leftover> - cures hold - cures fear - cures stun
              ~sprngb04.itm~ ~override~ // <1pp leftover> - cures hold - cures fear - cures stun
              ~sprngl03.itm~ ~override~ // <1pp leftover> - cures hold - cures fear - cures stun
              ~sprngl04.itm~ ~override~ // <1pp leftover> - cures hold - cures fear - cures stun
              ~sprngs01.itm~ ~override~ // <1pp leftover> - cures hold - cures stun
              ~sprngs02.itm~ ~override~ // <1pp leftover> - cures hold - cures stun
              ~sprngs03.itm~ ~override~ // <1pp leftover> - cures hold - cures stun
              ~sprngs04.itm~ ~override~ // <1pp leftover> - cures hold - cures stun
              ~sprngz05.itm~ ~override~ // <1pp leftover> - cures hold - cures fear - cures stun
              ~sw2h06.itm~   ~override~ // Spider's Bane +2 - cures hold - cures stun
              ~sw2h13.itm~   ~override~ // Spider's Bane +2 - cures hold - cures stun
              ~trollreg.spl~ ~override~ // [leftover troll revive spell] - cures berserk, blind, confusion, deafness, disease, feeblemind, hold, fear, poison, sleep, stun - causes sleep
  LPF cd_apply_batch STR_VAR array_name = cd_cure_stun END
  BUT_ONLY
