COPY_EXISTING ~mislead.spl~  ~override~ // mislead
              ~projimag.spl~ ~override~ // project image
              ~simulacr.spl~ ~override~ // simulacrum
  LPF CLONE_EFFECT  INT_VAR match_opcode = 206 STR_VAR match_resource = spwi420 resource = spcl936 END // block shadow twin ability
  PATCH_IF ("SOURCE_RES%" STRING_COMPARE_CASE "mislead") BEGIN // skip this for mislead
    LPF DELETE_EFFECT INT_VAR match_opcode = 144 match_parameter2 =  0 END // alow stealth
  END   
  BUT_ONLY
