//tbd, cam
// poison mists can be summoned but can also spawn as normal creatures, so need both a gender: neither and gender: summoned version
COPY_EXISTING ~mistpo01.cre~ ~override/mistposu.cre~ // create summoned version from original

COPY_EXISTING ~mistpo01.cre~ ~override~ // make normal ones gender: neither
  WRITE_BYTE 0x275 4 // gender: neither

COPY_EXISTING ~sppois.eff~ ~override~ // change summoning sell to use new, gender: summoned version
  WRITE_ASCII 0x30 ~mistposu~
