// tbd, cam
// missing/dupe entries in object.ids: https://www.gibberlings3.net/forums/topic/35564-objectids-typos-or-missing-lines
COPY_EXISTING ~object.ids~ ~override~
  PATCH_IF !game_is_iwdee BEGIN
    REPLACE_TEXTUALLY ~^[56]7 EigthNearest.+[ %TAB%%LNL%%MNL%%WNL%]+~ ~~
  END ELSE BEGIN
    REPLACE_TEXTUALLY ~^\([56]7 \)Eigth\(Nearest.+\)$~ ~\1Eighth\2~
    APPEND_FILE ~eefixpack/files/ids/object_iwdee.ids~
  END  
  BUT_ONLY