/* this code autogenerated by the following code (ugly, but it works)

<<<<<<<<./inline/bgee_charm_fixes_working.d

>>>>>>>>

COPY ~./inline/bgee_charm_fixes_working.d~ ~eefixpack/files/d/bgee_charm_fixes_working.d~

ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_bgee_charm BEGIN
  // dialogue file, charmed state, NTTT max, [optional] action to attach => name of creature/comment
  aldeth, 26, 0, ~~                                   => ~Aldeth Sashenstar (prevents quest)~
  alora,  10, 1, ~~                                   => ~Alora~
  alyth,   6, 0, ~~                                   => ~"Lady" Alyth Elendara~
  amnis2,  4, 0, ~~                                   => ~Amnian Soldier~
  amnise,  3, 0, ~~                                   => ~Amnian Soldier~
  ardeno,  4, 0, ~AddJournalEntry(26850,INFO)~        => ~Ardenor Crush~
  bandct,  8, 0, ~AddJournalEntry(26857,INFO)~        => ~unused bandct~
  bentan, 13, 0, ~~                                   => ~Bentan~
  boyba2,  2, 0, ~~                                   => ~Boy~
  boyba3,  3, 1, ~~                                   => ~Boy~
  boybe1,  2, 0, ~~                                   => ~Boy~
  boybe2,  2, 1, ~~                                   => ~Boy~
  branwe,  4, 0, ~AddJournalEntry(26891,INFO)~        => ~Branwen~
  brathl, 13, 6, ~SetGlobal("WardsClue","GLOBAL",1)~  => ~Brathlen~
  brevli, 30, 0, ~GivePartyGold(50)~                  => ~Brevlik~
  brielb, 15, 0, ~AddJournalEntry(26901,INFO)~        => ~Brielbara~
  brilla,  9, 1, ~~                                   => ~Brilla~
  centeo,  7, 0, ~AddJournalEntry(26909,INFO)~        => ~Centeol~
  charle, 22, 0, ~~                                   => ~Charleston~
  davaeo,  2, 0, ~AddJournalEntry(26929,QUEST_DONE)~  => ~Davaeorn - quest entry ok (cleared after mine floods)~
  deagan,  7, 0, ~AddJournalEntry(6580,INFO)~         => ~Deagan~
  delthy, 19, 0, ~AddJournalEntry(26964,INFO)~        => ~Delthyr~
  dillar,  7, 0, ~~                                   => ~Dillar~
  drienn,  5, 0, ~~                                   => ~Drienne~
  druidc,  5, 0, ~AddJournalEntry(6590,INFO)~         => ~Druid (one of Seniyad's shadow druids)~
  drunk,   5, 0, ~~                                   => ~Drunk~
  dynahe, 16, 0, ~~                                   => ~Dynaheir (NTTT can also break edwinj 0~
  fahrin,  6, 0, ~~                                   => ~Fahrington~
  faldor,  6, 0, ~AddJournalEntry(27061,INFO)~        => ~Faldorn~
  farm3,   1, 0, ~~                                   => ~Farmer~
  farm5,   5, 0, ~~                                   => ~Farmer (unused?)~
  farmbr, 13, 0, ~~                                   => ~Farmer Brun (prevents quest)~
  fcook2,  2, 0, ~~                                   => ~Cook~
  fcook3,  2, 0, ~~                                   => ~Cook~
  flam10,  8, 0, ~~                                   => ~Flaming Fist Mercenary~
  flam2,   5, 0, ~AddJournalEntry(27084,QUEST)~       => ~Flaming Fist Mercenary (viconia's tracker)~
  flam4,  14, 0, ~AddJournalEntry(27088,INFO)~        => ~Flaming Fist Mercenary (samuel's tracker)~
  flam5,  15, 0, ~AddJournalEntry(27088,INFO)~        => ~Flaming Fist Mercenary~
  flam7,   4, 0, ~~                                   => ~Flaming Fist Mercenary (guards treasury, has two charmed states)~
  flam7,   5, 0, ~~                                   => ~Flaming Fist Mercenary (guards treasury, has two charmed states)~
  flam8,   1, 0, ~~                                   => ~Flaming Fist Mercenary~
  flam9,   5, 0, ~~                                   => ~Flaming Fist Mercenary~
  flambg,  6, 0, ~AddJournalEntry(27088,INFO)~        => ~Dilos~
  flamen,  2, 0, ~~                                   => ~Flaming Fist Enforcer (flamen, flamen2) and Pheonix Guard (pheogurd)~
  flamgg,  3, 0, ~AddJournalEntry(6934,INFO)~         => ~Flaming Fist Mercenary (guard on bridge to BG)~
  friend,  6, 0, ~~                                   => ~Guard (FAI)~
  friwen,  3, 1, ~~                                   => ~unused (FAI server?)~
  ftobe2,  5, 0, ~~                                   => ~Commoner~
  ftobe3,  7, 0, ~~                                   => ~Commoner (former adventurer)~
  ftobe4,  3, 2, ~~                                   => ~Commoner (ar3316, calls guards)~
  ftobe5,  4, 1, ~GiveItem("RING11",LastTalkedToBy)~  => ~Commoner~
  ftobe6,  2, 0, ~~                                   => ~Commoner~
  ftobe7,  3, 2, ~~                                   => ~Commoner~
  ftobe8,  3, 0, ~~                                   => ~Commoner (unused?)~
  ftowb6,  3, 1, ~~                                   => ~Commoner~
  ftowb7,  3, 1, ~~                                   => ~Commoner~
  gallor, 10, 0, ~~                                   => ~Gallor~
  gantol,  8, 2, ~~                                   => ~Gantolandan~
  girba1,  2, 1, ~~                                   => ~Girl~
  girba2,  3, 1, ~~                                   => ~Girl~
  girba3,  4, 1, ~~                                   => ~Girl~
  glanma, 14, 0, ~~                                   => ~Glanmarie~
  haffg2, 10, 0, ~~                                   => ~Halfling Woman~
  halfen,  2, 0, ~~                                   => ~Halfling Enforcer~
  halffg,  1, 0, ~RevealAreaOnMap("AR4500")~          => ~Halfling Woman~
  halfg2,  9, 0, ~~                                   => ~Halfling Man (Bunsen)~
  halfg3,  9, 0, ~~                                   => ~Halfling Man~
  halfg4,  1, 0, ~GiveItem("POTN40",LastTalkedToBy)~  => ~Halfling Man~
  halfg5,  9, 0, ~~                                   => ~Halfling Man~
  halfg6,  1, 0, ~GiveItem("slng01",LastTalkedToBy)~  => ~Halfling Man~
  halftr,  8, 0, ~~                                   => ~Furret~
  hobgo5,  6, 0, ~AddJournalEntry(7012,INFO)~         => ~Hobgoblin~
  housen,  3, 0, ~~                                   => ~Guard Enforcer~
  housg1,  3, 2, ~~                                   => ~Carl~
  housg3,  0, 0, ~~                                   => ~Guard~
  housg4,  5, 0, ~~                                   => ~Guard (undercellar)~
  housg6,  5, 2, ~~                                   => ~Guard~
  hunter,  8, 0, ~~                                   => ~Ted~
  iron11,  5, 0, ~AddJournalEntry(27172,QUEST)~       => ~Guard - quest entry ok (cleared after mine floods)~
  iron12,  5, 0, ~~                                   => ~Guard~
  iron14,  8, 0, ~~                                   => ~Guard~
  iron3,   4, 0, ~AddJournalEntry(27172,QUEST)~       => ~Guard - quest entry ok (cleared after mine floods)~
  iron4,   1, 0, ~AddJournalEntry(27172,QUEST)~       => ~Guard - quest entry ok (cleared after mine floods)~
  iron5,   3, 0, ~AddJournalEntry(27172,QUEST)~       => ~Guard - quest entry ok (cleared after mine floods)~
  iron6,   1, 0, ~~                                   => ~Guard~
  ironm2,  0, 2, ~GivePartyGold(25)~                  => ~Merchant~
  ironm3,  3, 2, ~GivePartyGold(25)~                  => ~Merchant~
  ironm4, 11, 0, ~AddJournalEntry(7686,INFO)~         => ~Merchant~
  ithtyl,  0, 0, ~GivePartyGold(20)~                  => ~Ithtyl Calantryn~
  jebado,  8, 0, ~~                                   => ~Jebadoh~
  jhasso, 16, 0, ~~                                   => ~Jhasso~
  landri, 10, 0, ~~                                   => ~Landrin~
  lena,    7, 0, ~GivePartyGold(1000000)~             => ~Lena~
  lobar,   9, 0, ~~                                   => ~Lobar~
  marl,   17, 1, ~AddJournalEntry(27255,INFO)~        => ~Marl~
  mcook2,  2, 0, ~~                                   => ~Cook~
  mcook3,  2, 0, ~~                                   => ~Cook~
  mcook5,  3, 1, ~~                                   => ~Cook~   
  minec5,  2, 0, ~~                                   => ~Miner~
  monken,  1, 0, ~~                                   => ~Monk or Watcher at CK (when guards called)~
  mtbe10,  0, 1, ~~                                   => ~Butler~
  mtbe11, 11, 0, ~~                                   => ~Mr. Colquetle - don't re-weight for charmed dialogues~
  mtbe3,   5, 0, ~~                                   => ~Commoner~
  mtbe4,   4, 0, ~~                                   => ~Commoner~
  mtbe5,   7, 0, ~~                                   => ~Commoner~
  mtbe9,   3, 2, ~~                                   => ~Alain (ar3329) - summons mercs~
  mtob2,   5, 0, ~GivePartyGold(1)~                   => ~Commoner~
  mtob3,   2, 1, ~~                                   => ~Commoner~
  mtob4,   1, 0, ~~                                   => ~Commoner~
  mtob5,   4, 2, ~~                                   => ~Commoner~
  mtob7,   3, 2, ~GivePartyGold(1)~                   => ~Commoner~
  mtob8,   2, 1, ~GivePartyGold(1)~                   => ~Commoner~
  mtob9,   3, 2, ~GivePartyGold(1)~                   => ~Commoner~
  mtowf2,  8, 0, ~~                                   => ~Commoner~
  mtown2,  1, 0, ~~                                   => ~Commoner~
  niklos,  9, 0, ~~                                   => ~Niklos~
  nila,    9, 0, ~~                                   => ~Nila~
  nobl10,  6, 0, ~GiveItem("ring10",LastTalkedToBy)~  => ~Gerard Travenhurst~
  nobl11,  2, 0, ~GivePartyGold(10)~                  => ~Nobleman~
  nobl12,  2, 1, ~AddJournalEntry(27327,QUEST)~       => ~Nobleman (quest entry never clears)~   
  nobl14,  3, 1, ~~                                   => ~Nobleman~   
  nobl4,   7, 0, ~GivePartyGold(20)~                  => ~Nobleman~
  nobl5,   8, 1, ~~                                   => ~Nobleman~
  nobl6,   8, 0, ~~                                   => ~Nobleman~
  nobl7,   6, 0, ~~                                   => ~Nobleman~
  nobl8,   6, 0, ~GiveItem("RING17",LastTalkedToBy)~  => ~Nobleman~
  nobw5,   2, 1, ~AddJournalEntry(27327,QUEST)~       => ~Noblewoman (quest entry never clears)~  
  nobw9,   6, 0, ~~                                   => ~Noblewoman (quest entry never clears)~   
  oberan,  4, 0, ~~                                   => ~Oberan~
  oublek, 24, 0, ~~                                   => ~Oublek~
  perdue, 10, 0, ~~                                   => ~Perdue~
  poe,    21, 0, ~~                                   => ~Poe~
  poghm4,  2, 0, ~~                                   => ~Priest of Oghma~
  prat,    4, 0, ~~                                   => ~Prat~
  prost7,  6, 2, ~~                                   => ~Courtesan~
  prost8,  3, 1, ~~                                   => ~Courtesan~
  quayle,  6, 0, ~~                                   => ~Quayle~
  ragefa, 16, 0, ~~                                   => ~Ragefast~
  raiken, 17, 0, ~RevealAreaOnMap("AR1900")
AddJournalEntry(27383,INFO)~                           => ~Raiken~
  ramazi, 21, 0, ~~                                   => ~Raiken~   
  read4,   2, 0, ~~                                   => ~unused, but assigned to Reader (read4)~
  rielta,  3, 0, ~AddJournalEntry(26972,QUEST)~       => ~Rieltar - journal entry gets cleared at end of ch6, so no worries setting it here~
  safana, 11, 0, ~~                                   => ~Safana (charmed, male in party)~   
  safana, 14, 0, ~~                                   => ~Safana (charmed, no male in party)~   
  seniya,  3, 0, ~~                                   => ~Seniyad~   
  serva2, 11, 0, ~~                                   => ~Servant~   
  servan,  5, 0, ~~                                   => ~Servant~   
  serwen,  3, 0, ~~                                   => ~Serving Wench~   
  sewerc,  2, 0, ~~                                   => ~Sewer Cleaner~   
  sil,    10, 1, ~~                                   => ~Sewer Cleaner~   
  silenc,  0, 0, ~SetGlobal("SeenSanctuary","GLOBAL",1)
StartStore("stosilen",LastTalkedToBy(Myself))~         => ~Silence - has special 'hit the bricks' for NTTT>5, but only worried about =0~
  skie,    9, 0, ~~                                   => ~Skie~
  smith,   1, 0, ~GiveItem("CHAN01",LastTalkedToBy)~  => ~Smith~
  smuggl, 12, 0, ~AddJournalEntry(7166,INFO)~         => ~Smuggler~   
  sonner, 21, 0, ~~                                   => ~Sonner~   
  telman,  8, 0, ~~                                   => ~Telman~
  tenya,  29, 0, ~~                                   => ~Tenya~
  teven,  18, 0, ~AddJournalEntry(27476,INFO)~        => ~Teven~   
  thalan, 33, 0, ~~                                   => ~Thalantyr~
  thaldo,  5, 0, ~AddJournalEntry(27480,INFO)~        => ~Thaldorn~   
  tiax,    8, 0, ~~                                   => ~Tiax~   
  torlob,  2, 0, ~~                                   => ~Tor Lobo~   
  trave2,  2, 1, ~~                                   => ~Traveler~   
  travel,  9, 0, ~~                                   => ~Traveler~   
  viconi, 10, 0, ~~                                   => ~Viconia~   
  volose,  5, 0, ~~                                   => ~Waitress~  
  wilton,  2, 0, ~~                                   => ~Wilton~ 
  xzar,   20, 0, ~~                                   => ~Xzar~ 
  yago,    7, 0, ~AddJournalEntry(26899,INFO)~        => ~Yago~    
  yeslic,  6, 0, ~~                                   => ~Yeslick~

//bassil, 14, 0, ~~                                   => ~Basillus - goes hostile after charmed dialogue regardless~
//bounty,  7, 0, ~~                                   => ~Bounty Hunter - actually has dialogue for being charmed too many times~
//brandi, 12, 0, ~AddJournalEntry(26824,QUEST)~       => ~Brandilar - done manually to prevent re-opening a closed quest~
//digger, 13, 4, ~~                                   => ~Digger - not needed if more aggressive fix adopted~
//drizzt, 15, 0, ~~                                   => ~Drizzt - leaves immediately after his charmed dialogue~
//ffhunt,  1, 0, ~~                                   => ~Flaming Fist Enforcer - has multiple replies to charmed states~
//ftown2,  9, 0, ~~                                   => ~Commoner (wife of Joseph) - charmed state has replies, modify manually~
//greywo,  7, 0, ~~                                   => ~Greywolf - leaves immediately after his charmed dialogue~
//helsha,  6, 0, ~~                                   => ~Helshara - needed additional fixes~
//hentol,  0, 0, ~~                                   => ~Hentold - NTTT states no longer make sense after he gives up item in charmed state~
//ithmee,  7, 0, ~~                                   => ~Ithmeera - needed additional fixes~
//laurel,  6, 0, ~~                                   => ~Laurel - has special state for NTTT = 11, so do manually~
//minern,  3, 1, ~~                                   => ~Miner - has multiple replies to charmed states~
//mtbe2,   0, 0, ~AddJournalEntry(27279,QUEST)~       => ~Commoner (used by mtbe2, mtbe12, mrcolson) - done manually to prevent re-opening a closed quest~
//mtbe6,   0, 0, ~AddJournalEntry(8058,QUEST)~        => ~Commoner (Galteran) - done manually to prevent re-opening a closed quest~
//mtbe8,   2, 0, ~~                                   => ~Commoner - leaves after charmed dialogue~
//shaell, 10, 0, ~~                                   => ~Shaella - leaves after charmed dialogue~

END

<<<<<<<<./inline/charm_base_extend_top.d

// %comment%
EXTEND_BOTTOM %params_0% %params_1%
>>>>>>>>
<<<<<<<<./inline/charm_base_extend.d
  IF ~NumTimesTalkedTo(%index%)~ THEN DO ~SetNumTimesTalkedTo(%index%)%params_3%~ EXIT
>>>>>>>>
<<<<<<<<./inline/charm_base_extend_bottom.d
END
>>>>>>>>

ACTION_PHP_EACH cd_bgee_charm AS params => comment BEGIN
  COPY ~eefixpack/files/d/bgee_charm_fixes_working.d~ ~eefixpack/files/d/bgee_charm_fixes_working.d~
    //APPEND_FILE_EVALUATE ~./inline/charm_base.d~ 
    APPEND_FILE_EVALUATE ~./inline/charm_base_extend_top.d~ 
    FOR (index = 0 ; index <= params_2 ; ++index) BEGIN
      APPEND_FILE_EVALUATE ~./inline/charm_base_extend.d~ 
    END  
    APPEND_FILE_EVALUATE ~./inline/charm_base_extend_bottom.d~ 
END

COPY ~eefixpack/files/d/bgee_charm_fixes_working.d~ ~eefixpack/files/d/bgee_charm_fixes_working.d~
*/

// Aldeth Sashenstar (prevents quest)
EXTEND_BOTTOM aldeth 26
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Alora
EXTEND_BOTTOM alora 10
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// "Lady" Alyth Elendara
EXTEND_BOTTOM alyth 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Amnian Soldier
EXTEND_BOTTOM amnis2 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Amnian Soldier
EXTEND_BOTTOM amnise 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Ardenor Crush
EXTEND_BOTTOM ardeno 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26850,INFO)~ EXIT
END

// unused bandct
EXTEND_BOTTOM bandct 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26857,INFO)~ EXIT
END

// Bentan
EXTEND_BOTTOM bentan 13
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Boy
EXTEND_BOTTOM boyba2 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Boy
EXTEND_BOTTOM boyba3 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Boy
EXTEND_BOTTOM boybe1 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Boy
EXTEND_BOTTOM boybe2 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Branwen
EXTEND_BOTTOM branwe 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26891,INFO)~ EXIT
END

// Brathlen
EXTEND_BOTTOM brathl 13
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)SetGlobal("WardsClue","GLOBAL",1)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)SetGlobal("WardsClue","GLOBAL",1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)SetGlobal("WardsClue","GLOBAL",1)~ EXIT
  IF ~NumTimesTalkedTo(3)~ THEN DO ~SetNumTimesTalkedTo(3)SetGlobal("WardsClue","GLOBAL",1)~ EXIT
  IF ~NumTimesTalkedTo(4)~ THEN DO ~SetNumTimesTalkedTo(4)SetGlobal("WardsClue","GLOBAL",1)~ EXIT
  IF ~NumTimesTalkedTo(5)~ THEN DO ~SetNumTimesTalkedTo(5)SetGlobal("WardsClue","GLOBAL",1)~ EXIT
  IF ~NumTimesTalkedTo(6)~ THEN DO ~SetNumTimesTalkedTo(6)SetGlobal("WardsClue","GLOBAL",1)~ EXIT
END

// Brevlik
EXTEND_BOTTOM brevli 30
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(50)~ EXIT
END

// Brielbara
EXTEND_BOTTOM brielb 15
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26901,INFO)~ EXIT
END

// Brilla
EXTEND_BOTTOM brilla 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Centeol
EXTEND_BOTTOM centeo 7
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26909,INFO)~ EXIT
END

// Charleston
EXTEND_BOTTOM charle 22
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Davaeorn - quest entry ok (cleared after mine floods)
EXTEND_BOTTOM davaeo 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26929,QUEST_DONE)~ EXIT
END

// Deagan
EXTEND_BOTTOM deagan 7
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(6580,INFO)~ EXIT
END

// Delthyr
EXTEND_BOTTOM delthy 19
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26964,INFO)~ EXIT
END

// Dillar
EXTEND_BOTTOM dillar 7
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Drienne
EXTEND_BOTTOM drienn 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Druid (one of Seniyad's shadow druids)
EXTEND_BOTTOM druidc 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(6590,INFO)~ EXIT
END

// Drunk
EXTEND_BOTTOM drunk 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Dynaheir (NTTT can also break edwinj 0
EXTEND_BOTTOM dynahe 16
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Fahrington
EXTEND_BOTTOM fahrin 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Faldorn
EXTEND_BOTTOM faldor 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27061,INFO)~ EXIT
END

// Farmer
EXTEND_BOTTOM farm3 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Farmer (unused?)
EXTEND_BOTTOM farm5 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Farmer Brun (prevents quest)
EXTEND_BOTTOM farmbr 13
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Cook
EXTEND_BOTTOM fcook2 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Cook
EXTEND_BOTTOM fcook3 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Flaming Fist Mercenary
EXTEND_BOTTOM flam10 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Flaming Fist Mercenary (viconia's tracker)
EXTEND_BOTTOM flam2 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27084,QUEST)~ EXIT
END

// Flaming Fist Mercenary (samuel's tracker)
EXTEND_BOTTOM flam4 14
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27088,INFO)~ EXIT
END

// Flaming Fist Mercenary
EXTEND_BOTTOM flam5 15
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27088,INFO)~ EXIT
END

// Flaming Fist Mercenary (guards treasury, has two charmed states)
EXTEND_BOTTOM flam7 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Flaming Fist Mercenary (guards treasury, has two charmed states)
EXTEND_BOTTOM flam7 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Flaming Fist Mercenary
EXTEND_BOTTOM flam8 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Flaming Fist Mercenary
EXTEND_BOTTOM flam9 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Dilos
EXTEND_BOTTOM flambg 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27088,INFO)~ EXIT
END

// Flaming Fist Enforcer (flamen, flamen2) and Pheonix Guard (pheogurd)
EXTEND_BOTTOM flamen 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Flaming Fist Mercenary (guard on bridge to BG)
EXTEND_BOTTOM flamgg 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(6934,INFO)~ EXIT
END

// Guard (FAI)
EXTEND_BOTTOM friend 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// unused (FAI server?)
EXTEND_BOTTOM friwen 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Commoner
EXTEND_BOTTOM ftobe2 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner (former adventurer)
EXTEND_BOTTOM ftobe3 7
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner (ar3316, calls guards)
EXTEND_BOTTOM ftobe4 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)~ EXIT
END

// Commoner
EXTEND_BOTTOM ftobe5 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GiveItem("RING11",LastTalkedToBy)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)GiveItem("RING11",LastTalkedToBy)~ EXIT
END

// Commoner
EXTEND_BOTTOM ftobe6 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner
EXTEND_BOTTOM ftobe7 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)~ EXIT
END

// Commoner (unused?)
EXTEND_BOTTOM ftobe8 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner
EXTEND_BOTTOM ftowb6 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Commoner
EXTEND_BOTTOM ftowb7 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Gallor
EXTEND_BOTTOM gallor 10
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Gantolandan
EXTEND_BOTTOM gantol 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)~ EXIT
END

// Girl
EXTEND_BOTTOM girba1 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Girl
EXTEND_BOTTOM girba2 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Girl
EXTEND_BOTTOM girba3 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Glanmarie
EXTEND_BOTTOM glanma 14
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Halfling Woman
EXTEND_BOTTOM haffg2 10
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Halfling Enforcer
EXTEND_BOTTOM halfen 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Halfling Woman
EXTEND_BOTTOM halffg 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)RevealAreaOnMap("AR4500")~ EXIT
END

// Halfling Man (Bunsen)
EXTEND_BOTTOM halfg2 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Halfling Man
EXTEND_BOTTOM halfg3 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Halfling Man
EXTEND_BOTTOM halfg4 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GiveItem("POTN40",LastTalkedToBy)~ EXIT
END

// Halfling Man
EXTEND_BOTTOM halfg5 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Halfling Man
EXTEND_BOTTOM halfg6 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GiveItem("slng01",LastTalkedToBy)~ EXIT
END

// Furret
EXTEND_BOTTOM halftr 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Hobgoblin
EXTEND_BOTTOM hobgo5 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(7012,INFO)~ EXIT
END

// Guard Enforcer
EXTEND_BOTTOM housen 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Carl
EXTEND_BOTTOM housg1 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)~ EXIT
END

// Guard
EXTEND_BOTTOM housg3 0
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Guard (undercellar)
EXTEND_BOTTOM housg4 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Guard
EXTEND_BOTTOM housg6 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)~ EXIT
END

// Ted
EXTEND_BOTTOM hunter 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Guard - quest entry ok (cleared after mine floods)
EXTEND_BOTTOM iron11 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27172,QUEST)~ EXIT
END

// Guard
EXTEND_BOTTOM iron12 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Guard
EXTEND_BOTTOM iron14 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Guard - quest entry ok (cleared after mine floods)
EXTEND_BOTTOM iron3 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27172,QUEST)~ EXIT
END

// Guard - quest entry ok (cleared after mine floods)
EXTEND_BOTTOM iron4 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27172,QUEST)~ EXIT
END

// Guard - quest entry ok (cleared after mine floods)
EXTEND_BOTTOM iron5 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27172,QUEST)~ EXIT
END

// Guard
EXTEND_BOTTOM iron6 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Merchant
EXTEND_BOTTOM ironm2 0
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(25)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)GivePartyGold(25)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)GivePartyGold(25)~ EXIT
END

// Merchant
EXTEND_BOTTOM ironm3 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(25)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)GivePartyGold(25)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)GivePartyGold(25)~ EXIT
END

// Merchant
EXTEND_BOTTOM ironm4 11
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(7686,INFO)~ EXIT
END

// Ithtyl Calantryn
EXTEND_BOTTOM ithtyl 0
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(20)~ EXIT
END

// Jebadoh
EXTEND_BOTTOM jebado 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Jhasso
EXTEND_BOTTOM jhasso 16
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Landrin
EXTEND_BOTTOM landri 10
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Lena
EXTEND_BOTTOM lena 7
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(1000000)~ EXIT
END

// Lobar
EXTEND_BOTTOM lobar 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Marl
EXTEND_BOTTOM marl 17
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27255,INFO)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)AddJournalEntry(27255,INFO)~ EXIT
END

// Cook
EXTEND_BOTTOM mcook2 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Cook
EXTEND_BOTTOM mcook3 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Cook
EXTEND_BOTTOM mcook5 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Miner
EXTEND_BOTTOM minec5 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Monk or Watcher at CK (when guards called)
EXTEND_BOTTOM monken 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Butler
EXTEND_BOTTOM mtbe10 0
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Mr. Colquetle - don't re-weight for charmed dialogues
EXTEND_BOTTOM mtbe11 11
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtbe3 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtbe4 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtbe5 7
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Alain (ar3329) - summons mercs
EXTEND_BOTTOM mtbe9 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtob2 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(1)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtob3 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtob4 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtob5 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtob7 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(1)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)GivePartyGold(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)GivePartyGold(1)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtob8 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(1)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)GivePartyGold(1)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtob9 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(1)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)GivePartyGold(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)GivePartyGold(1)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtowf2 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtown2 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Niklos
EXTEND_BOTTOM niklos 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Nila
EXTEND_BOTTOM nila 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Gerard Travenhurst
EXTEND_BOTTOM nobl10 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GiveItem("ring10",LastTalkedToBy)~ EXIT
END

// Nobleman
EXTEND_BOTTOM nobl11 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(10)~ EXIT
END

// Nobleman (quest entry never clears)
EXTEND_BOTTOM nobl12 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27327,QUEST)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)AddJournalEntry(27327,QUEST)~ EXIT
END

// Nobleman
EXTEND_BOTTOM nobl14 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Nobleman
EXTEND_BOTTOM nobl4 7
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(20)~ EXIT
END

// Nobleman
EXTEND_BOTTOM nobl5 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Nobleman
EXTEND_BOTTOM nobl6 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Nobleman
EXTEND_BOTTOM nobl7 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Nobleman
EXTEND_BOTTOM nobl8 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GiveItem("RING17",LastTalkedToBy)~ EXIT
END

// Noblewoman (quest entry never clears)
EXTEND_BOTTOM nobw5 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27327,QUEST)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)AddJournalEntry(27327,QUEST)~ EXIT
END

// Noblewoman (quest entry never clears)
EXTEND_BOTTOM nobw9 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Oberan
EXTEND_BOTTOM oberan 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Oublek
EXTEND_BOTTOM oublek 24
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Perdue
EXTEND_BOTTOM perdue 10
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Poe
EXTEND_BOTTOM poe 21
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Priest of Oghma
EXTEND_BOTTOM poghm4 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Prat
EXTEND_BOTTOM prat 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Courtesan
EXTEND_BOTTOM prost7 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)~ EXIT
END

// Courtesan
EXTEND_BOTTOM prost8 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Quayle
EXTEND_BOTTOM quayle 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Ragefast
EXTEND_BOTTOM ragefa 16
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Raiken
EXTEND_BOTTOM raiken 17
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)RevealAreaOnMap("AR1900")
AddJournalEntry(27383,INFO)~ EXIT
END

// Raiken
EXTEND_BOTTOM ramazi 21
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// unused, but assigned to Reader (read4)
EXTEND_BOTTOM read4 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Rieltar - journal entry gets cleared at end of ch6, so no worries setting it here
EXTEND_BOTTOM rielta 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26972,QUEST)~ EXIT
END

// Safana (charmed, male in party)
EXTEND_BOTTOM safana 11
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Safana (charmed, no male in party)
EXTEND_BOTTOM safana 14
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Seniyad
EXTEND_BOTTOM seniya 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Servant
EXTEND_BOTTOM serva2 11
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Servant
EXTEND_BOTTOM servan 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Serving Wench
EXTEND_BOTTOM serwen 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Sewer Cleaner
EXTEND_BOTTOM sewerc 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Sewer Cleaner
EXTEND_BOTTOM sil 10
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Silence - has special 'hit the bricks' for NTTT>5, but only worried about =0
EXTEND_BOTTOM silenc 0
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)SetGlobal("SeenSanctuary","GLOBAL",1)
StartStore("stosilen",LastTalkedToBy(Myself))~ EXIT
END

// Skie
EXTEND_BOTTOM skie 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Smith
EXTEND_BOTTOM smith 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GiveItem("CHAN01",LastTalkedToBy)~ EXIT
END

// Smuggler
EXTEND_BOTTOM smuggl 12
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(7166,INFO)~ EXIT
END

// Sonner
EXTEND_BOTTOM sonner 21
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Telman
EXTEND_BOTTOM telman 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Tenya
EXTEND_BOTTOM tenya 29
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Teven
EXTEND_BOTTOM teven 18
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27476,INFO)~ EXIT
END

// Thalantyr
EXTEND_BOTTOM thalan 33
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Thaldorn
EXTEND_BOTTOM thaldo 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27480,INFO)~ EXIT
END

// Tiax
EXTEND_BOTTOM tiax 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Tor Lobo
EXTEND_BOTTOM torlob 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Traveler
EXTEND_BOTTOM trave2 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Traveler
EXTEND_BOTTOM travel 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Viconia
EXTEND_BOTTOM viconi 10
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Waitress
EXTEND_BOTTOM volose 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Wilton
EXTEND_BOTTOM wilton 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Xzar
EXTEND_BOTTOM xzar 20
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Yago
EXTEND_BOTTOM yago 7
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26899,INFO)~ EXIT
END

// Yeslick
EXTEND_BOTTOM yeslic 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Aldeth Sashenstar (prevents quest)
EXTEND_BOTTOM aldeth 26
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Alora
EXTEND_BOTTOM alora 10
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// "Lady" Alyth Elendara
EXTEND_BOTTOM alyth 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Amnian Soldier
EXTEND_BOTTOM amnis2 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Amnian Soldier
EXTEND_BOTTOM amnise 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Ardenor Crush
EXTEND_BOTTOM ardeno 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26850,INFO)~ EXIT
END

// unused bandct
EXTEND_BOTTOM bandct 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26857,INFO)~ EXIT
END

// Bentan
EXTEND_BOTTOM bentan 13
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Boy
EXTEND_BOTTOM boyba2 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Boy
EXTEND_BOTTOM boyba3 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Boy
EXTEND_BOTTOM boybe1 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Boy
EXTEND_BOTTOM boybe2 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Branwen
EXTEND_BOTTOM branwe 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26891,INFO)~ EXIT
END

// Brathlen
EXTEND_BOTTOM brathl 13
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)SetGlobal("WardsClue","GLOBAL",1)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)SetGlobal("WardsClue","GLOBAL",1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)SetGlobal("WardsClue","GLOBAL",1)~ EXIT
  IF ~NumTimesTalkedTo(3)~ THEN DO ~SetNumTimesTalkedTo(3)SetGlobal("WardsClue","GLOBAL",1)~ EXIT
  IF ~NumTimesTalkedTo(4)~ THEN DO ~SetNumTimesTalkedTo(4)SetGlobal("WardsClue","GLOBAL",1)~ EXIT
  IF ~NumTimesTalkedTo(5)~ THEN DO ~SetNumTimesTalkedTo(5)SetGlobal("WardsClue","GLOBAL",1)~ EXIT
  IF ~NumTimesTalkedTo(6)~ THEN DO ~SetNumTimesTalkedTo(6)SetGlobal("WardsClue","GLOBAL",1)~ EXIT
END

// Brevlik
EXTEND_BOTTOM brevli 30
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(50)~ EXIT
END

// Brielbara
EXTEND_BOTTOM brielb 15
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26901,INFO)~ EXIT
END

// Brilla
EXTEND_BOTTOM brilla 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Centeol
EXTEND_BOTTOM centeo 7
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26909,INFO)~ EXIT
END

// Charleston
EXTEND_BOTTOM charle 22
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Davaeorn - quest entry ok (cleared after mine floods)
EXTEND_BOTTOM davaeo 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26929,QUEST_DONE)~ EXIT
END

// Deagan
EXTEND_BOTTOM deagan 7
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(6580,INFO)~ EXIT
END

// Delthyr
EXTEND_BOTTOM delthy 19
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26964,INFO)~ EXIT
END

// Dillar
EXTEND_BOTTOM dillar 7
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Drienne
EXTEND_BOTTOM drienn 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Druid (one of Seniyad's shadow druids)
EXTEND_BOTTOM druidc 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(6590,INFO)~ EXIT
END

// Drunk
EXTEND_BOTTOM drunk 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Dynaheir (NTTT can also break edwinj 0
EXTEND_BOTTOM dynahe 16
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Fahrington
EXTEND_BOTTOM fahrin 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Faldorn
EXTEND_BOTTOM faldor 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27061,INFO)~ EXIT
END

// Farmer
EXTEND_BOTTOM farm3 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Farmer (unused?)
EXTEND_BOTTOM farm5 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Farmer Brun (prevents quest)
EXTEND_BOTTOM farmbr 13
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Cook
EXTEND_BOTTOM fcook2 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Cook
EXTEND_BOTTOM fcook3 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Flaming Fist Mercenary
EXTEND_BOTTOM flam10 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Flaming Fist Mercenary (viconia's tracker)
EXTEND_BOTTOM flam2 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27084,QUEST)~ EXIT
END

// Flaming Fist Mercenary (samuel's tracker)
EXTEND_BOTTOM flam4 14
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27088,INFO)~ EXIT
END

// Flaming Fist Mercenary
EXTEND_BOTTOM flam5 15
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27088,INFO)~ EXIT
END

// Flaming Fist Mercenary (guards treasury, has two charmed states)
EXTEND_BOTTOM flam7 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Flaming Fist Mercenary (guards treasury, has two charmed states)
EXTEND_BOTTOM flam7 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Flaming Fist Mercenary
EXTEND_BOTTOM flam8 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Flaming Fist Mercenary
EXTEND_BOTTOM flam9 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Dilos
EXTEND_BOTTOM flambg 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27088,INFO)~ EXIT
END

// Flaming Fist Enforcer (flamen, flamen2) and Pheonix Guard (pheogurd)
EXTEND_BOTTOM flamen 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Flaming Fist Mercenary (guard on bridge to BG)
EXTEND_BOTTOM flamgg 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(6934,INFO)~ EXIT
END

// Guard (FAI)
EXTEND_BOTTOM friend 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// unused (FAI server?)
EXTEND_BOTTOM friwen 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Commoner
EXTEND_BOTTOM ftobe2 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner (former adventurer)
EXTEND_BOTTOM ftobe3 7
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner (ar3316, calls guards)
EXTEND_BOTTOM ftobe4 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)~ EXIT
END

// Commoner
EXTEND_BOTTOM ftobe5 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GiveItem("RING11",LastTalkedToBy)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)GiveItem("RING11",LastTalkedToBy)~ EXIT
END

// Commoner
EXTEND_BOTTOM ftobe6 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner
EXTEND_BOTTOM ftobe7 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)~ EXIT
END

// Commoner (unused?)
EXTEND_BOTTOM ftobe8 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner
EXTEND_BOTTOM ftowb6 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Commoner
EXTEND_BOTTOM ftowb7 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Gallor
EXTEND_BOTTOM gallor 10
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Gantolandan
EXTEND_BOTTOM gantol 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)~ EXIT
END

// Girl
EXTEND_BOTTOM girba1 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Girl
EXTEND_BOTTOM girba2 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Girl
EXTEND_BOTTOM girba3 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Glanmarie
EXTEND_BOTTOM glanma 14
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Halfling Woman
EXTEND_BOTTOM haffg2 10
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Halfling Enforcer
EXTEND_BOTTOM halfen 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Halfling Woman
EXTEND_BOTTOM halffg 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)RevealAreaOnMap("AR4500")~ EXIT
END

// Halfling Man (Bunsen)
EXTEND_BOTTOM halfg2 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Halfling Man
EXTEND_BOTTOM halfg3 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Halfling Man
EXTEND_BOTTOM halfg4 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GiveItem("POTN40",LastTalkedToBy)~ EXIT
END

// Halfling Man
EXTEND_BOTTOM halfg5 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Halfling Man
EXTEND_BOTTOM halfg6 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GiveItem("slng01",LastTalkedToBy)~ EXIT
END

// Furret
EXTEND_BOTTOM halftr 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Hobgoblin
EXTEND_BOTTOM hobgo5 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(7012,INFO)~ EXIT
END

// Guard Enforcer
EXTEND_BOTTOM housen 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Carl
EXTEND_BOTTOM housg1 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)~ EXIT
END

// Guard
EXTEND_BOTTOM housg3 0
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Guard (undercellar)
EXTEND_BOTTOM housg4 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Guard
EXTEND_BOTTOM housg6 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)~ EXIT
END

// Ted
EXTEND_BOTTOM hunter 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Guard - quest entry ok (cleared after mine floods)
EXTEND_BOTTOM iron11 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27172,QUEST)~ EXIT
END

// Guard
EXTEND_BOTTOM iron12 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Guard
EXTEND_BOTTOM iron14 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Guard - quest entry ok (cleared after mine floods)
EXTEND_BOTTOM iron3 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27172,QUEST)~ EXIT
END

// Guard - quest entry ok (cleared after mine floods)
EXTEND_BOTTOM iron4 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27172,QUEST)~ EXIT
END

// Guard - quest entry ok (cleared after mine floods)
EXTEND_BOTTOM iron5 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27172,QUEST)~ EXIT
END

// Guard
EXTEND_BOTTOM iron6 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Merchant
EXTEND_BOTTOM ironm2 0
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(25)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)GivePartyGold(25)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)GivePartyGold(25)~ EXIT
END

// Merchant
EXTEND_BOTTOM ironm3 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(25)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)GivePartyGold(25)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)GivePartyGold(25)~ EXIT
END

// Merchant
EXTEND_BOTTOM ironm4 11
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(7686,INFO)~ EXIT
END

// Ithtyl Calantryn
EXTEND_BOTTOM ithtyl 0
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(20)~ EXIT
END

// Jebadoh
EXTEND_BOTTOM jebado 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Jhasso
EXTEND_BOTTOM jhasso 16
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Landrin
EXTEND_BOTTOM landri 10
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Lena
EXTEND_BOTTOM lena 7
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(1000000)~ EXIT
END

// Lobar
EXTEND_BOTTOM lobar 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Marl
EXTEND_BOTTOM marl 17
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27255,INFO)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)AddJournalEntry(27255,INFO)~ EXIT
END

// Cook
EXTEND_BOTTOM mcook2 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Cook
EXTEND_BOTTOM mcook3 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Cook
EXTEND_BOTTOM mcook5 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Miner
EXTEND_BOTTOM minec5 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Monk or Watcher at CK (when guards called)
EXTEND_BOTTOM monken 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Butler
EXTEND_BOTTOM mtbe10 0
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Mr. Colquetle - don't re-weight for charmed dialogues
EXTEND_BOTTOM mtbe11 11
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtbe3 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtbe4 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtbe5 7
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Alain (ar3329) - summons mercs
EXTEND_BOTTOM mtbe9 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtob2 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(1)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtob3 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtob4 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtob5 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtob7 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(1)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)GivePartyGold(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)GivePartyGold(1)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtob8 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(1)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)GivePartyGold(1)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtob9 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(1)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)GivePartyGold(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)GivePartyGold(1)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtowf2 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Commoner
EXTEND_BOTTOM mtown2 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Niklos
EXTEND_BOTTOM niklos 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Nila
EXTEND_BOTTOM nila 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Gerard Travenhurst
EXTEND_BOTTOM nobl10 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GiveItem("ring10",LastTalkedToBy)~ EXIT
END

// Nobleman
EXTEND_BOTTOM nobl11 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(10)~ EXIT
END

// Nobleman (quest entry never clears)
EXTEND_BOTTOM nobl12 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27327,QUEST)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)AddJournalEntry(27327,QUEST)~ EXIT
END

// Nobleman
EXTEND_BOTTOM nobl14 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Nobleman
EXTEND_BOTTOM nobl4 7
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GivePartyGold(20)~ EXIT
END

// Nobleman
EXTEND_BOTTOM nobl5 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Nobleman
EXTEND_BOTTOM nobl6 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Nobleman
EXTEND_BOTTOM nobl7 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Nobleman
EXTEND_BOTTOM nobl8 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GiveItem("RING17",LastTalkedToBy)~ EXIT
END

// Noblewoman (quest entry never clears)
EXTEND_BOTTOM nobw5 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27327,QUEST)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)AddJournalEntry(27327,QUEST)~ EXIT
END

// Noblewoman (quest entry never clears)
EXTEND_BOTTOM nobw9 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Oberan
EXTEND_BOTTOM oberan 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Oublek
EXTEND_BOTTOM oublek 24
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Perdue
EXTEND_BOTTOM perdue 10
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Poe
EXTEND_BOTTOM poe 21
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Priest of Oghma
EXTEND_BOTTOM poghm4 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Prat
EXTEND_BOTTOM prat 4
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Courtesan
EXTEND_BOTTOM prost7 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
  IF ~NumTimesTalkedTo(2)~ THEN DO ~SetNumTimesTalkedTo(2)~ EXIT
END

// Courtesan
EXTEND_BOTTOM prost8 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Quayle
EXTEND_BOTTOM quayle 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Ragefast
EXTEND_BOTTOM ragefa 16
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Raiken
EXTEND_BOTTOM raiken 17
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)RevealAreaOnMap("AR1900")
AddJournalEntry(27383,INFO)~ EXIT
END

// Raiken
EXTEND_BOTTOM ramazi 21
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// unused, but assigned to Reader (read4)
EXTEND_BOTTOM read4 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Rieltar - journal entry gets cleared at end of ch6, so no worries setting it here
EXTEND_BOTTOM rielta 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26972,QUEST)~ EXIT
END

// Safana (charmed, male in party)
EXTEND_BOTTOM safana 11
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Safana (charmed, no male in party)
EXTEND_BOTTOM safana 14
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Seniyad
EXTEND_BOTTOM seniya 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Servant
EXTEND_BOTTOM serva2 11
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Servant
EXTEND_BOTTOM servan 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Serving Wench
EXTEND_BOTTOM serwen 3
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Sewer Cleaner
EXTEND_BOTTOM sewerc 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Sewer Cleaner
EXTEND_BOTTOM sil 10
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Silence - has special 'hit the bricks' for NTTT>5, but only worried about =0
EXTEND_BOTTOM silenc 0
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)SetGlobal("SeenSanctuary","GLOBAL",1)
StartStore("stosilen",LastTalkedToBy(Myself))~ EXIT
END

// Skie
EXTEND_BOTTOM skie 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Smith
EXTEND_BOTTOM smith 1
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)GiveItem("CHAN01",LastTalkedToBy)~ EXIT
END

// Smuggler
EXTEND_BOTTOM smuggl 12
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(7166,INFO)~ EXIT
END

// Sonner
EXTEND_BOTTOM sonner 21
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Telman
EXTEND_BOTTOM telman 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Tenya
EXTEND_BOTTOM tenya 29
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Teven
EXTEND_BOTTOM teven 18
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27476,INFO)~ EXIT
END

// Thalantyr
EXTEND_BOTTOM thalan 33
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Thaldorn
EXTEND_BOTTOM thaldo 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(27480,INFO)~ EXIT
END

// Tiax
EXTEND_BOTTOM tiax 8
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Tor Lobo
EXTEND_BOTTOM torlob 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Traveler
EXTEND_BOTTOM trave2 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
  IF ~NumTimesTalkedTo(1)~ THEN DO ~SetNumTimesTalkedTo(1)~ EXIT
END

// Traveler
EXTEND_BOTTOM travel 9
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Viconia
EXTEND_BOTTOM viconi 10
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Waitress
EXTEND_BOTTOM volose 5
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Wilton
EXTEND_BOTTOM wilton 2
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Xzar
EXTEND_BOTTOM xzar 20
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END

// Yago
EXTEND_BOTTOM yago 7
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)AddJournalEntry(26899,INFO)~ EXIT
END

// Yeslick
EXTEND_BOTTOM yeslic 6
  IF ~NumTimesTalkedTo(0)~ THEN DO ~SetNumTimesTalkedTo(0)~ EXIT
END
