// able to move majority to bulk item/spell fixes; original code still in _orig file

COPY_EXISTING "gberry.itm" "override"
  LAUNCH_PATCH_FUNCTION "DELETE_EFFECT" INT_VAR "match_opcode" = 139 END
  LAUNCH_PATCH_FUNCTION ~ALTER_EFFECT~ INT_VAR ~resist_dispel~ = 0 END
  BUT_ONLY IF_EXISTS
  
COPY_EXISTING "%CLERIC_MASS_CURE%.spl" "override"
  LAUNCH_PATCH_FUNCTION ~ALTER_EFFECT~ INT_VAR ~target~ = 2 ~resist_dispel~ = BIT1 END
  BUT_ONLY IF_EXISTS

