DEFINE_ACTION_FUNCTION "DAMAGE"
BEGIN
	/*
	****************************************************************************************
	***************************************** ITM files ************************************
	****************************************************************************************
	*/

	WITH_SCOPE BEGIN
		ACTION_MATCH 1 WITH
			(GAME_IS ~bgee~) BEGIN
				ACTION_DEFINE_ASSOCIATIVE_ARRAY "patch_data" BEGIN
					// parent resref , ability , permutation/extract => child resref
				END
			END
			(GAME_IS ~bg2ee eet~) BEGIN
				ACTION_DEFINE_ASSOCIATIVE_ARRAY "patch_data" BEGIN
					// parent resref , ability , permutation/extract => child resref
				END
			END
			(GAME_IS ~iwdee~) BEGIN
				ACTION_DEFINE_ASSOCIATIVE_ARRAY "patch_data" BEGIN
					// parent resref , ability , permutation/extract => child resref
				END
			END
			DEFAULT
				FAIL "Game not supported"
		END
		/* Main */
		ACTION_PHP_EACH "patch_data" AS "x" => "y" BEGIN
			COPY_EXISTING "%x_0%.itm" "override"
				// Transfer effects onto a new SPL file (if needed)
				PATCH_IF ("%y%" STRING_COMPARE_CASE "") BEGIN
					LAUNCH_PATCH_FUNCTION "gt_extract_effects_as_subspell"
					INT_VAR
						"ability" = "%x_1%"
					STR_VAR
						"subspell_resref" = "%y%"
						"extract" = "%x_2%"
					END
				END ELSE BEGIN
					LAUNCH_PATCH_FUNCTION "gt_permute_effects"
					INT_VAR
						"ability" = "%x_1%"
					STR_VAR
						"permutation" = "%x_2%"
					END
				END
			BUT_ONLY_IF_IT_CHANGES
		END
	END

	/*
	****************************************************************************************
	***************************************** SPL files ************************************
	****************************************************************************************
	*/

	WITH_SCOPE BEGIN
		ACTION_MATCH 1 WITH
			(GAME_IS ~bgee~) BEGIN
				ACTION_DEFINE_ASSOCIATIVE_ARRAY "patch_data" BEGIN
					// parent resref , ability , permutation/extract => child resref
				END
			END
			(GAME_IS ~bg2ee eet~) BEGIN
				ACTION_DEFINE_ASSOCIATIVE_ARRAY "patch_data" BEGIN
					// parent resref , ability , permutation/extract => child resref
				END
			END
			(GAME_IS ~iwdee~) BEGIN
				ACTION_DEFINE_ASSOCIATIVE_ARRAY "patch_data" BEGIN
					// parent resref , ability , permutation/extract => child resref
					"#beltyn" , "-1" , "0,1" => "%WIZARD_BELTYNS_BURNING_BLOOD%A"
					"#deathf1" , "-1" , "0" => "%TRAP_DEATH_FOG%A"
					"#deathf2" , "-1" , "0" => "%TRAP_DEATH_FOG%B"
					"#deathf3" , "-1" , "0" => "%TRAP_DEATH_FOG%C"
					"#sunrund" , "-1" , "0" => "cdsunrun"
					"bdsumst1" , "-1" , "0,2" => "bdsumst4" // Flame Arrow
					"ltouch" , "-1" , "0" => "%WIZARD_LICH_TOUCH%A"
					"%SUN_SOUL_SUN_SOULRAY%" , "-1" , "1=>0" => ""
					"%SUN_SOUL_SUN_SOULBEAM%A" , "-1" , "1,2" => "%SUN_SOUL_SUN_SOULBEAM%B"
					"spcl411" , 1 , "1" => "spcl411a"
					"spcl411" , 2 , "1" => "spcl411b"
					"spcl411" , 3 , "1" => "spcl411b"
					"spcl411f" , 1 , "0" => "spcl411c" // unused...?
					"spcl411f" , 2 , "0" => "spcl411c" // unused...?
					"spcl411f" , 3 , "0" => "spcl411c" // unused...?
					"spcl415" , 0 , "0=>-1" => ""
					"spcl911b" , 0 , "0=>-1" => ""
					"spdr101" , 1 , "0=>-1" => "" // Chromatic Orb (Avenger)
					"spdr101" , 2 , "1=>-1" => "" // Chromatic Orb (Avenger)
					"%INNATE_DRAGON_WING_BUFFET%" , "-1" , "5,6" => "%INNATE_DRAGON_WING_BUFFET%A"
					"%INNATE_BOMBARDIER_BEETLE_CLOUD%" , "-1" , "0" => "%INNATE_BOMBARDIER_BEETLE_CLOUD%A"
					"%AIR_ELEMENTAL_EFFECT%" , "-1" , "1=>-1" => ""
					"spogre01" , "-1" , "6=>-1" => "" // Earthquake
					"%CLERIC_ALICORN_LANCE%" , "-1" , "1=>-1" => ""
					"%CLERIC_WRITHING_FOG%" , "-1" , "1=>8" => ""
					"%CLERIC_CLOUDBURST%" , "-1" , "12,13" => "%CLERIC_CLOUDBURST%A"
					"%CLERIC_PRODUCE_FIRE%" , "-1" , "1" => "%CLERIC_PRODUCE_FIRE%A"
					"%CLERIC_SMASHING_WAVE%" , "-1" , "4" => "%CLERIC_SMASHING_WAVE%A"
					"%CLERIC_INSECT_PLAGUE%" , "-1" , "3" => "%CLERIC_INSECT_PLAGUE%A"
					"%CLERIC_SPIKE_STONES%" , "-1" , "1=>-1" => ""
					//"%CLERIC_FALSE_DAWN%" , "-1" , "2" => "%CLERIC_FALSE_DAWN%A" // cam: fixed elsewhere
					"%CLERIC_WHIRLWIND%" , "-1" , "5,6" => "%CLERIC_WHIRLWIND%A"
					"%CLERIC_EARTHQUAKE%" , "-1" , "6=>-1" => ""
					"%CLERIC_STORM_OF_VENGEANCE%" , "-1" , "0,1,2,3,4,5,6,7,8" => "%CLERIC_STORM_OF_VENGEANCE%A"
					"%CLERIC_IMPLOSION%" , "-1" , "2" => "%CLERIC_IMPLOSION%A"
					"%TRAP_ARROW_SLAYING%" , "-1" , "0" => "%TRAP_ARROW_SLAYING%A"
					"%TRAP_ARROW_ACID%" , "-1" , "0" => "%TRAP_ARROW_ACID%A"
					"%TRAP_ARROW_BITING%" , "-1" , "0" => "%TRAP_ARROW_BITING%A"
					"%TRAP_ARROW_DETONATION%" , "-1" , "0" => "%TRAP_ARROW_DETONATION%A"
					"%TRAP_ARROW_DISPELLING%" , "-1" , "0=>-1" => ""
					"%TRAP_ARROW_FIRE%" , "-1" , "0" => "%TRAP_ARROW_FIRE%A"
					"%TRAP_ARROW_ICE%" , "-1" , "0" => "%TRAP_ARROW_ICE%A"
					"%TRAP_DISEASE_DARTS%" , "-1" , "0" => "%TRAP_DISEASE_DARTS%A"
					"%TRAP_POISON_DAMAGE_DARTS%" , "-1" , "0" => "%TRAP_POISON_DAMAGE_DARTS%A"
					"%TRAP_POISON_PARALYZATION_DARTS%" , "-1" , "0" => "%TRAP_POISON_PARALYZATION_DARTS%A"
					"%TRAP_POISON_CONFUSION_DARTS%" , "-1" , "0" => "%TRAP_POISON_CONFUSION_DARTS%A"
					//"%WIZARD_CHILL_TOUCH%B" -- fixed elsewhere
					"%WIZARD_CHROMATIC_ORB%" , 1 , "0=>-1" => ""
					"%WIZARD_CHROMATIC_ORB%" , 2 , "1=>-1" => ""
					"%WIZARD_FLAME_ARROW%" , 0 , "0" => "%WIZARD_FLAME_ARROW%A"
					"%WIZARD_FLAME_ARROW%" , 1 , "0,2" => "%WIZARD_FLAME_ARROW%B"
					"%WIZARD_FLAME_ARROW%" , 2 , "0,2,4" => "%WIZARD_FLAME_ARROW%C"
					"%WIZARD_FLAME_ARROW%" , 3 , "0,2,4,6" => "%WIZARD_FLAME_ARROW%D"
					"%WIZARD_FLAME_ARROW%" , 4 , "0,2,4,6,8" => "%WIZARD_FLAME_ARROW%E"
					"%WIZARD_FLAME_ARROW%" , 5 , "0,2,4,6,8,10" => "%WIZARD_FLAME_ARROW%F"
					//WIZARD_SHROUD_OF_FLAME -- should the Eye of Mage absorb the possibility to spread the shroud...? Guess so...
					//"%WIZARD_DEATH_FOG%" , "-1" , "5=>-1" => "" -- should it be recoded à la "%TRAP_DEATH_FOG%" (no need for splstates)...?
					"%WIZARD_PRISMATIC_SPRAY%" , "-1" , "4,5" => "%WIZARD_PRISMATIC_SPRAY%A"
					//WIZARD_BIGBYS_CLENCHED_FIST
					//WIZARD_BIGBYS_CRUSHING_HAND
					"%WIZARD_DRAGONS_BREATH%" , "-1" , "1=>-1" => ""
					"%WIZARD_COMET%" , "-1" , "1=>-1" => ""
					"spwish27" , "-1" , "2=>-1" => "" // Knockback
					"spyanc01" , "-1" , "2=>-1" => "" // Whirlwind
				END
			END
			DEFAULT
				FAIL "Game not supported"
		END
		/* Main */
		ACTION_PHP_EACH "patch_data" AS "x" => "y" BEGIN
			COPY_EXISTING "%x_0%.spl" "override"
				// Transfer effects onto a new SPL file (if needed)
				PATCH_IF ("%y%" STRING_COMPARE_CASE "") BEGIN
					LAUNCH_PATCH_FUNCTION "gt_extract_effects_as_subspell"
					INT_VAR
						"ability" = "%x_1%"
					STR_VAR
						"subspell_resref" = "%y%"
						"extract" = "%x_2%"
					END
				END ELSE BEGIN
					LAUNCH_PATCH_FUNCTION "gt_permute_effects"
					INT_VAR
						"ability" = "%x_1%"
					STR_VAR
						"permutation" = "%x_2%"
					END
				END
			BUT_ONLY_IF_IT_CHANGES
		END
	END
END

/////////////////////////////////////////////////////////////////
/*

Collect SPL/ITM files to check

*/
//////////////////////////////////////////////////////////////////

/*
WITH_SCOPE BEGIN
	OUTER_SET "count_spl" = 0
	OUTER_SET "count_itm" = 0
	COPY_EXISTING_REGEXP - "^.+\.\(spl\|itm\)$" "override"
		PATCH_MATCH "%DEST_EXT%" WITH
			"itm" BEGIN
				GET_OFFSET_ARRAY "ab_array" ITM_V10_HEADERS
				TEXT_SPRINT "filename" "rearrange_itm"
			END
			"spl" BEGIN
				GET_OFFSET_ARRAY "ab_array" SPL_V10_HEADERS
				TEXT_SPRINT "filename" "rearrange_spl"
			END
			DEFAULT
				PATCH_FAIL "~%DEST_FILE%~"
		END
		PHP_EACH "ab_array" AS "ab_ind" => "ab_off" BEGIN
			PATCH_IF SHORT_AT ("%ab_off%" + 0x1E) > 1 BEGIN
				GET_OFFSET_ARRAY2 "fx_array" "%ab_off%" SPL_V10_HEAD_EFFECTS
				SET "done_first" = 0
				PHP_EACH "fx_array" AS "fx_ind" => "fx_off" BEGIN
					PATCH_MATCH SHORT_AT "%fx_off%" WITH
						12 WHEN !("%done_first%") BEGIN
							PATCH_MATCH SHORT_AT ("%fx_off%" + 0xA) WITH
								(IDS_OF_SYMBOL ("DMGTYPE" "STUNNING") >> 16) BEGIN END
								(IDS_OF_SYMBOL ("DMGTYPE" "MAGIC") >> 16) BEGIN END
								DEFAULT
									SET "done_first" = 1
									PATCH_IF ("%fx_ind%" != SHORT_AT ("%ab_off%" + 0x1E) - 1) BEGIN
										INNER_ACTION BEGIN
											ACTION_IF ("%DEST_EXT%" STRING_EQUAL_CASE "itm") BEGIN
												OUTER_SET "count_itm" += 1
												APPEND_OUTER "%MOD_FOLDER%/%filename%.txt" "%count_itm%) ~%DEST_FILE%~ => ability #%ab_ind%, position #%fx_ind%" UNLESS "%count_itm%) ~%DEST_FILE%~ => ability #%ab_ind%, position #%fx_ind%"
											END ELSE BEGIN
												OUTER_SET "count_spl" += 1
												APPEND_OUTER "%MOD_FOLDER%/%filename%.txt" "%count_spl%) ~%DEST_FILE%~ => ability #%ab_ind%, position #%fx_ind%" UNLESS "%count_spl%) ~%DEST_FILE%~ => ability #%ab_ind%, position #%fx_ind%"
											END
										END
									END
							END
						END
						DEFAULT
					END
				END
			END
		END
	BUT_ONLY_IF_IT_CHANGES
END
*/