DEFINE_ACTION_FUNCTION "DAMAGE"
BEGIN
	/*
	****************************************************************************************
	***************************************** ITM files ************************************
	****************************************************************************************
	*/

	WITH_SCOPE BEGIN
		ACTION_MATCH 1 WITH
			(GAME_IS ~bgee~) BEGIN
				ACTION_DEFINE_ASSOCIATIVE_ARRAY "patch_data" BEGIN
					// parent resref , damage type => child resref
				END
			END
			(GAME_IS ~bg2ee eet~) BEGIN
				ACTION_DEFINE_ASSOCIATIVE_ARRAY "patch_data" BEGIN
					// parent resref , damage type => child resref
				END
			END
			(GAME_IS ~iwdee~) BEGIN
				ACTION_DEFINE_ASSOCIATIVE_ARRAY "patch_data" BEGIN
					// parent resref , damage type => child resref
					"sflail" , 0x1000000 => "sflail1"
				END
			END
			DEFAULT
				FAIL "Game not supported"
		END
		/* Main */
		ACTION_PHP_EACH "patch_data" AS "parent_resref" => "child_resref" BEGIN
			COPY_EXISTING "%parent_resref%.itm" "override"
				// Transfer effects onto a new SPL file (if needed)
				PATCH_IF ("%child_resref%" STRING_COMPARE_CASE "") BEGIN
					LAUNCH_PATCH_FUNCTION "gt_extract_effects_as_subspell"
					INT_VAR
						"effectID" = 12
						"damage_type" = "%parent_resref_1%"
					STR_VAR
						"subspell_resref" = "%child_resref%"
						"icon" = "^\(6\|102\)$"
						"string" = "^\(Bleeding\|Suffers Bleeding Wound\|Bleeding Wound\)$"
					END
				END ELSE BEGIN
					LAUNCH_PATCH_FUNCTION "gt_permute_effects" END
				END
			BUT_ONLY_IF_IT_CHANGES IF_EXISTS
		END
	END

	/*
	****************************************************************************************
	***************************************** SPL files ************************************
	****************************************************************************************
	*/

	WITH_SCOPE BEGIN
		ACTION_MATCH 1 WITH
			(GAME_IS ~bgee~) BEGIN
				ACTION_DEFINE_ASSOCIATIVE_ARRAY "patch_data" BEGIN
					// parent resref => child resref
					// Crushing
					"bdtr01" , 0x0 => "bdtr01a"
					"%DRAGON_WING_BUFFET%" , 0x0 => "%DRAGON_WING_BUFFET%a"
					"%MEPHIT_SOOTY_BALL%" , 0x0 => "%MEPHIT_SOOTY_BALL%a"
					"%MEPHIT_SALT_CRYSTAL%" , 0x0 => "%MEPHIT_SALT_CRYSTAL%a"
					"%AIR_ELEMENTAL_EFFECT%" , 0x0 => "%AIR_ELEMENTAL_EFFECT%a"
					"spogre01" , 0x0 => "spogre02" // Earthquake
					"%CLERIC_EARTHQUAKE%" , 0x0 => "%CLERIC_EARTHQUAKE%a"
					"%WIZARD_BIGBYS_CLENCHED_FIST%" , 0x0 => "%WIZARD_BIGBYS_CLENCHED_FIST%b"
					"%WIZARD_BIGBYS_CLENCHED_FIST%a" , 0x0 => "%WIZARD_BIGBYS_CLENCHED_FIST%c"
					"%WIZARD_BIGBYS_CRUSHING_HAND%" , 0x0 => "%WIZARD_BIGBYS_CRUSHING_HAND%b"
					"%WIZARD_BIGBYS_CRUSHING_HAND%a" , 0x0 => "%WIZARD_BIGBYS_CRUSHING_HAND%c"
					"%CRUSHING_TRAP%" , 0x0 => "%CRUSHING_TRAP%a"
					"spyanc01" , 0x0 => "spyanc02" // Air Elemental Whirlwind
					// Acid
					"bdcut57a" , 0x10000 => "bdcut57b" // Chromatic Orb
					"bddagg05" , 0x10000 => "" // Acid-Etched Dagger +2
					"shoal" , 0x10000 => "shoal01" // Nereid's Kiss
					"shoal1" , 0x10000 => "shoal2" // Nereid's Kiss
					"spdr101" , 0x10000 => "spdr101b" // Chromatic Orb (Avenger)
					"%BOMBARDIER_BEETLE_CLOUD%" , 0x10000 => "%BOMBARDIER_BEETLE_CLOUD%a"
					"%TRAP_SLIME%" , 0x10000 => "%TRAP_SLIME%a"
					"%WIZARD_CHROMATIC_ORB%" , 0x10000 => "%WIZARD_CHROMATIC_ORB%b"
					"%WIZARD_DEATH_FOG%" , 0x10000 => "%WIZARD_DEATH_FOG%a"
					// Cold
					"bdsw2h01" , 0x20000 => "bds2h01a" // Dragon Blade +3
					"bdunslgu" , 0x20000 => "bdunslg0" // Chill Ray
					"%DRAGON_RAIN%" , 0x20000 => "%DRAGON_RAIN%a"
					"%CLERIC_WRITHING_FOG%" , 0x20000 => "%CLERIC_WRITHING_FOG%a"
					// Electricity
					"%VIEKANG_LIGHTNING%" , 0x40000 => "%VIEKANG_LIGHTNING%a"
					// Fire
					"bdalldie" , 0x80000 => "bdaldie0"
					"bdshld02" , 0x80000 => "bdshl02a" // Shield of Barnassus: The Suncatcher
					"%SUN_SOUL_SUN_SOULRAY%" , 0x80000 => ""
					"%SUN_SOUL_SUN_SOULBEAM%a" , 0x80000 => "%SUN_SOUL_SUN_SOULBEAM%b"
					"spdr101" , 0x80000 => "spdr101c" // Chromatic Orb (Avenger)
					"%MEPHIT_WATER_JET%" , 0x80000 => "%MEPHIT_WATER_JET%a"
					"%CLERIC_FALSE_DAWN%" , 0x80000 => "%CLERIC_FALSE_DAWN%a"
					"%WIZARD_CHROMATIC_ORB%" , 0x80000 => "%WIZARD_CHROMATIC_ORB%c"
					"%WIZARD_FLAME_ARROW%" , 0x80000 => "%WIZARD_FLAME_ARROW%a"
					"%SAREVOK_STRIKE%" , 0x80000 => "%SAREVOK_STRIKE%a"
					// Piercing
					"bdgassa3" , 0x100000 => "bdgass3a"
					"bdhalb02" , 0x100000 => "" // Festering Spear +1
					"bdimpale" , 0x100000 => "bdimpal0" // Impale
					"bdsw1h21" , 0x100000 => "" // Vexation +2
					"TRAP_DARTS" , 0x100000 => "%TRAP_DARTS%a"
					"%TRAP_ARROW_SLAYING%" , 0x100000 => "%TRAP_ARROW_SLAYING%a"
					"%TRAP_ARROW_ACID%" , 0x100000 => "%TRAP_ARROW_ACID%a"
					"%TRAP_ARROW_DETONATION%" , 0x100000 => "%TRAP_ARROW_DETONATION%a"
					"%TRAP_ARROW_DISPELLING%" , 0x100000 => "%TRAP_ARROW_DISPELLING%a"
					"%TRAP_ARROW_FIRE%" , 0x100000 => "%TRAP_ARROW_FIRE%a"
					"%TRAP_ARROW_ICE%" , 0x100000 => "%TRAP_ARROW_ICE%a"
					"spwi019" , 0x100000 => "spwi019a"
					// Poison
					"%SPORE_DEATH%" , 0x200000 => "%SPORE_DEATH%a"
					"%TRAP_CLOUDKILL%" , 0x200000 => "%TRAP_CLOUDKILL%a"
					"%WIZARD_CLOUDKILL%" , 0x200000 => "%WIZARD_CLOUDKILL%a"
					// Missile
					"spcl411" , 0x800000 => "spcl411a"
					"spcl411f" , 0x800000 => "spcl411g"
					"spcl415" , 0x800000 => "spcl415a"
					"%TRAP_ARROW_BITING%" , 0x800000 => "%TRAP_ARROW_BITING%a"
					// Slashing
					"bddcor1a" , 0x1000000 => ""
				END
			END
			(GAME_IS ~bg2ee eet~) BEGIN
				ACTION_DEFINE_ASSOCIATIVE_ARRAY "patch_data" BEGIN
					// parent resref , damage type => child resref
					// Crushing
					"abzaway" , 0x0 => "abzaway0"
					"balth01" , 0x0 => "balth01c" // Solar Stance!
					"balth09" , 0x0 => "balth09a" // Shadowless Kick!
					"ch3away" , 0x0 => "ch3away0"
					"jwwhirl" , 0x0 => "jwwhirl0"
					"ohbquake" , 0x0 => "cdbquake" // Earthquake
					"ohbwhirl" , 0x0 => "cdbwhirl" // Whirlwind
					"%DRAGON_WING_BUFFET%" , 0x0 => "%DRAGON_WING_BUFFET%a"
					"%BRAIN_PSIONIC_BLAST%" , 0x0 => "%BRAIN_PSIONIC_BLAST%a"
					"%MEPHIT_SOOTY_BALL%" , 0x0 => "%MEPHIT_SOOTY_BALL%a"
					"%MEPHIT_SALT_CRYSTAL%" , 0x0 => "%MEPHIT_SALT_CRYSTAL%a"
					"%AIR_ELEMENTAL_EFFECT%" , 0x0 => "%AIR_ELEMENTAL_EFFECT%a"
					"spogre01" , 0x0 => "spogre02" // Earthquake
					"%CLERIC_EARTHQUAKE%" , 0x0 => "%CLERIC_EARTHQUAKE%a"
					"%WIZARD_BIGBYS_CLENCHED_FIST%" , 0x0 => "%WIZARD_BIGBYS_CLENCHED_FIST%b"
					"%WIZARD_BIGBYS_CLENCHED_FIST%a" , 0x0 => "%WIZARD_BIGBYS_CLENCHED_FIST%c"
					"%WIZARD_BIGBYS_CRUSHING_HAND%" , 0x0 => "%WIZARD_BIGBYS_CRUSHING_HAND%b"
					"%WIZARD_BIGBYS_CRUSHING_HAND%a" , 0x0 => "%WIZARD_BIGBYS_CRUSHING_HAND%c"
					"%CRUSHING_TRAP%" , 0x0 => "%CRUSHING_TRAP%a"
					"spwish27" , 0x0 => "spwis27a" // Knockback
					"spyanc01" , 0x0 => "spyanc02" // Air Elemental Whirlwind
					// Acid
					"ohdmask" , 0x10000 => "ohdmask0" // Breathe Acid
					"ohrgrog" , 0x10000 => "ohrgrog0"
					"spdr101" , 0x10000 => "spdr101b" // Chromatic Orb (Avenger)
					"%TRAP_SLIME%" , 0x10000 => "%TRAP_SLIME%a"
					"%CLERIC_STORM_OF_VENGEANCE%" , 0x10000 => "%CLERIC_STORM_OF_VENGEANCE%a"
					"%WIZARD_CHROMATIC_ORB%" , 0x10000 => "%WIZARD_CHROMATIC_ORB%b"
					"%WIZARD_DEATH_FOG%" , 0x10000 => "%WIZARD_DEATH_FOG%a"
					// Cold
					"bdsw2h01" , 0x20000 => "bds2h01a" // Dragon Blade +3
					"ohbicew" , 0x20000 => "ohbicew0" // Wall of Ice
					"ohddivrt" , 0x20000 => "ohddivr0" // Divine Retribution
					"%DRAGON_RAIN%" , 0x20000 => "%DRAGON_RAIN%a"
					"%CLERIC_WRITHING_FOG%" , 0x20000 => "%CLERIC_WRITHING_FOG%a"
					// Electricity
					"cdstaf12" , 0x40000 => "cdstf12a" // Lightning Bolt
					"%ABAZIGAL_SHOCKWAVE%" , 0x40000 => "%ABAZIGAL_SHOCKWAVE%a"
					"%POWER_AMP%" , 0x40000 => "%POWER_AMP%a"
					"%VIEKANG_LIGHTNING%" , 0x40000 => "%VIEKANG_LIGHTNING%a"
					"%CLERIC_STORM_OF_VENGEANCE%" , 0x10000 => "%CLERIC_STORM_OF_VENGEANCE%b"
					// Fire
					"balth01" , 0x80000 => "balth01d" // Solar Stance!
					"jwsiege" , 0x80000 => "jwsiege0"
					"%SUN_SOUL_SUN_SOULRAY%" , 0x80000 => ""
					"%SUN_SOUL_SUN_SOULBEAM%a" , 0x80000 => "%SUN_SOUL_SUN_SOULBEAM%b"
					"%ROGUE_SET_EXPLODING_TRAP%b" , 0x80000 => "%ROGUE_SET_EXPLODING_TRAP%c"
					"spdr101" , 0x80000 => "spdr101c" // Chromatic Orb (Avenger)
					"%BURNING_MAN_CINDER_SHOWER%" , 0x80000 => "%BURNING_MAN_CINDER_SHOWER%a"
					"%DECK_DEFIANCE%" , 0x80000 => "%DECK_DEFIANCE%a"
					"%CUTSCENE_DAMAGE_1C%" , 0x80000 => "%CUTSCENE_DAMAGE_1C%a"
					"%CUTSCENE_DAMAGE_1B%" , 0x80000 => "%CUTSCENE_DAMAGE_1B%a"
					"%CUTSCENE_DAMAGE_1%" , 0x80000 => "%CUTSCENE_DAMAGE_1%a"
					"%APPRENTI_DEATH%" , 0x80000 => "%APPRENTI_DEATH%a"
					"%MEPHIT_WATER_JET%" , 0x80000 => "%MEPHIT_WATER_JET%a"
					"%CLERIC_FALSE_DAWN%" , 0x80000 => "%CLERIC_FALSE_DAWN%a"
					"%CLERIC_STORM_OF_VENGEANCE%" , 0x10000 => "%CLERIC_STORM_OF_VENGEANCE%c"
					"%CLERIC_IMPLOSION%" , 0x10000 => "%CLERIC_IMPLOSION%a"
					"%WIZARD_CHROMATIC_ORB%" , 0x80000 => "%WIZARD_CHROMATIC_ORB%c"
					"%WIZARD_FLAME_ARROW%" , 0x80000 => "%WIZARD_FLAME_ARROW%a"
					"%WIZARD_DRAGONS_BREATH%" , 0x80000 => "%WIZARD_DRAGONS_BREATH%a"
					"%WIZARD_COMET%" , 0x80000 => "%WIZARD_COMET%a"
					// Piercing
					"melis01" , 0x100000 => "melis01a" // Bone Blades
					"ohbbleed" , 0x100000 => "ohbbled0"
					"%YELLOW_DRAGON_BREATH%" , 0x100000 => "%YELLOW_DRAGON_BREATH%b"
					"TRAP_DARTS" , 0x100000 => "%TRAP_DARTS%a"
					"%TRAP_ARROW_SLAYING%" , 0x100000 => "%TRAP_ARROW_SLAYING%a"
					"%TRAP_ARROW_ACID%" , 0x100000 => "%TRAP_ARROW_ACID%a"
					"%TRAP_ARROW_DETONATION%" , 0x100000 => "%TRAP_ARROW_DETONATION%a"
					"%TRAP_ARROW_DISPELLING%" , 0x100000 => "%TRAP_ARROW_DISPELLING%a"
					"%TRAP_ARROW_FIRE%" , 0x100000 => "%TRAP_ARROW_FIRE%a"
					"%TRAP_ARROW_ICE%" , 0x100000 => "%TRAP_ARROW_ICE%a"
					"spwi019" , 0x100000 => "spwi019a"
					// Poison
					"bhaal2b" , 0x200000 => "bhaal2b0" // Dark Taint
					"%SPORE_DEATH%" , 0x200000 => "%SPORE_DEATH%a"
					"%TRAP_CLOUDKILL%" , 0x200000 => "%TRAP_CLOUDKILL%a"
					"%WIZARD_CLOUDKILL%" , 0x200000 => "%WIZARD_CLOUDKILL%a"
					// Missile
					"eyeeglm3" , 0x800000 => "eyeglm3a"
					"eyeeglm4" , 0x800000 => "eyeglm4a"
					"eyeeglm7" , 0x800000 => "eyeglm7a"
					"spcl411" , 0x800000 => "spcl411a"
					"spcl411f" , 0x800000 => "spcl411g"
					"spcl415" , 0x800000 => "spcl415a"
					"%TRAP_ARROW_BITING%" , 0x800000 => "%TRAP_ARROW_BITING%a"
					// Slashing
					"melis01" , 0x1000000 => "melis01b" // Bone Blades
					"sareveff" => "sareeff0"
				END
			END
			(GAME_IS ~iwdee~) BEGIN
				ACTION_DEFINE_ASSOCIATIVE_ARRAY "patch_data" BEGIN
					// parent resref , damage type => child resref
					// Crushing
					"%INNATE_DRAGON_WING_BUFFET%" , 0x0 => "%INNATE_DRAGON_WING_BUFFET%a"
					"%AIR_ELEMENTAL_EFFECT%" , 0x0 => "%AIR_ELEMENTAL_EFFECT%a"
					"spogre01" , 0x0 => "spogre02" // Earthquake
					"%CLERIC_SMASHING_WAVE%" , 0x0 => "%CLERIC_SMASHING_WAVE%a"
					"%CLERIC_WHIRLWIND%" , 0x0 => "%CLERIC_WHIRLWIND%a"
					"%CLERIC_EARTHQUAKE%" => "%CLERIC_EARTHQUAKE%a"
					"%WIZARD_BIGBYS_CLENCHED_FIST%" , 0x0 => "%WIZARD_BIGBYS_CLENCHED_FIST%b"
					"%WIZARD_BIGBYS_CLENCHED_FIST%a" , 0x0 => "%WIZARD_BIGBYS_CLENCHED_FIST%c"
					"%WIZARD_BIGBYS_CRUSHING_HAND%" , 0x0 => "%WIZARD_BIGBYS_CRUSHING_HAND%b"
					"%WIZARD_BIGBYS_CRUSHING_HAND%a" , 0x0 => "%WIZARD_BIGBYS_CRUSHING_HAND%c"
					"spwish27" , 0x0 => "spwis27a" // Knockback
					"spyanc01" , 0x0 => "spyanc02" // Whirlwind
					// Acid
					"#deathf1" , 0x10000 => "%TRAP_DEATH_FOG%a"
					"#deathf2" , 0x10000 => "%TRAP_DEATH_FOG%b"
					"#deathf3" , 0x10000 => "%TRAP_DEATH_FOG%c"
					"%INNATE_BOMBARDIER_BEETLE_CLOUD%" , 0x10000 => "%INNATE_BOMBARDIER_BEETLE_CLOUD%a"
					"%CLERIC_STORM_OF_VENGEANCE%" , 0x10000 => "%CLERIC_STORM_OF_VENGEANCE%a"
					"%WIZARD_DEATH_FOG%" , 0x10000 => "%WIZARD_DEATH_FOG%a" // should it be recoded à la "%TRAP_DEATH_FOG%" (no need for splstates)...?
					// Cold
					"ltouch" , 0x20000 => "%WIZARD_LICH_TOUCH%a" // cold
					"%CLERIC_WRITHING_FOG%" , 0x20000 => "%CLERIC_WRITHING_FOG%a"
					// "%WIZARD_CHILL_TOUCH%b" -- fixed elsewhere
					// Electricity
					"%CLERIC_CLOUDBURST%" , 0x40000 => "%CLERIC_CLOUDBURST%a"
					"%CLERIC_STORM_OF_VENGEANCE%" , 0x40000 => "%CLERIC_STORM_OF_VENGEANCE%b"
					// Fire
					"#beltyn" , 0x80000 => "%WIZARD_BELTYNS_BURNING_BLOOD%a"
					"#sunrund" , 0x80000 => "#sunrun1"
					"bdsumst1" , 0x80000 => "bdsumst4" // Flame Arrow
					"%SUN_SOUL_SUN_SOULRAY%" , 0x80000 => ""
					"%SUN_SOUL_SUN_SOULBEAM%a" , 0x80000 => "%SUN_SOUL_SUN_SOULBEAM%b"
					"%ROGUE_SET_EXPLODING_TRAP%b" => "%ROGUE_SET_EXPLODING_TRAP%c"
					"spdr101" , 0x80000 => "spdr101b" // Chromatic Orb (Avenger)
					"%CLERIC_PRODUCE_FIRE%" , 0x80000 => "%CLERIC_PRODUCE_FIRE%a"
					"%CLERIC_FALSE_DAWN%" , 0x80000 => "%CLERIC_FALSE_DAWN%b"
					"%CLERIC_STORM_OF_VENGEANCE%" , 0x80000 => "%CLERIC_STORM_OF_VENGEANCE%c"
					"%CLERIC_IMPLOSION%" , 0x80000 => "%CLERIC_IMPLOSION%a"
					"%WIZARD_CHROMATIC_ORB%" , 0x80000 => "%WIZARD_CHROMATIC_ORB%b"
					"%WIZARD_FLAME_ARROW%" , 0x80000 => "%WIZARD_FLAME_ARROW%a"
					//WIZARD_SHROUD_OF_FLAME -- should the Eye of Mage absorb the possibility to spread the shroud...? Guess so...?
					"%WIZARD_DRAGONS_BREATH%" , 0x80000 => "%WIZARD_DRAGONS_BREATH%a"
					"%WIZARD_COMET%" , 0x80000 => "%WIZARD_COMET%a"
					// Piercing
					"%CLERIC_ALICORN_LANCE%" , 0x100000 => "%CLERIC_ALICORN_LANCE%a"
					"%CLERIC_INSECT_PLAGUE%" , 0x100000 => "%CLERIC_INSECT_PLAGUE%a"
					"%CLERIC_SPIKE_STONES%" , 0x100000 => "%CLERIC_SPIKE_STONES%a"
					// Poison
					"%WIZARD_PRISMATIC_SPRAY%" , 0x200000 => "%WIZARD_PRISMATIC_SPRAY%b"
					// Missile
					"spcl411" , 0x800000 => "spcl411a"
					"spcl411f" , 0x800000 => "cdcl411f"
					"spcl415" => "spcl415b"
					"%TRAP_ARROW_SLAYING%" , 0x800000 => "%TRAP_ARROW_SLAYING%a"
					"%TRAP_ARROW_ACID%" , 0x800000 => "%TRAP_ARROW_ACID%a"
					"%TRAP_ARROW_BITING%" , 0x800000 => "%TRAP_ARROW_BITING%a"
					"%TRAP_ARROW_DETONATION%" , 0x800000 => "%TRAP_ARROW_DETONATION%a"
					"%TRAP_ARROW_DISPELLING%" , 0x800000 => "%TRAP_ARROW_DISPELLING%a"
					"%TRAP_ARROW_FIRE%" , 0x800000 => "%TRAP_ARROW_FIRE%a"
					"%TRAP_ARROW_ICE%" , 0x800000 => "%TRAP_ARROW_ICE%a"
					"%TRAP_DISEASE_DARTS%" , 0x800000 => "%TRAP_DISEASE_DARTS%a"
					"%TRAP_POISON_DAMAGE_DARTS%" , 0x800000 => "%TRAP_POISON_DAMAGE_DARTS%a"
					"%TRAP_POISON_PARALYZATION_DARTS%" , 0x800000 => "%TRAP_POISON_PARALYZATION_DARTS%a"
					"%TRAP_POISON_CONFUSION_DARTS%" , 0x800000 => "%TRAP_POISON_CONFUSION_DARTS%a"
					// Slashing
					"%CLERIC_WHIRLWIND%" , 0x1000000 => "%CLERIC_WHIRLWIND%b"
				END
			END
			DEFAULT
				FAIL "Game not supported"
		END
		/* Main */
		ACTION_PHP_EACH "patch_data" AS "parent_resref" => "child_resref" BEGIN
			COPY_EXISTING "%parent_resref%.spl" "override"
				// Transfer effects onto a new SPL file (if needed)
				PATCH_IF ("%child_resref%" STRING_COMPARE_CASE "") BEGIN
					LAUNCH_PATCH_FUNCTION "gt_extract_effects_as_subspell"
					INT_VAR
						"effectID" = 0xC
						"damage_type" = "%parent_resref_1%"
					STR_VAR
						"subspell_resref" = "%child_resref%"
						"icon" = "^\(6\|102\)"
						"string" = "^Bleeding$"
					END
				END ELSE BEGIN
					LAUNCH_PATCH_FUNCTION "gt_reorder_effect_stack" INT_VAR "effectID" = 0xC END
				END
			BUT_ONLY_IF_IT_CHANGES IF_EXISTS
		END
	END
END

/////////////////////////////////////////////////////////////////
/*

Collect SPL/ITM files to check

*/
//////////////////////////////////////////////////////////////////

/*
WITH_SCOPE BEGIN
	OUTER_SET "count_spl" = 0
	OUTER_SET "count_itm" = 0
	COPY_EXISTING_REGEXP - "^.+\.\(spl\|itm\)$" "override"
		PATCH_MATCH "%DEST_EXT%" WITH
			"itm" BEGIN
				GET_OFFSET_ARRAY "ab_array" ITM_V10_HEADERS
				TEXT_SPRINT "filename" "rearrange_itm"
			END
			"spl" BEGIN
				GET_OFFSET_ARRAY "ab_array" SPL_V10_HEADERS
				TEXT_SPRINT "filename" "rearrange_spl"
			END
			DEFAULT
				PATCH_FAIL "~%DEST_FILE%~"
		END
		PHP_EACH "ab_array" AS "ab_ind" => "ab_off" BEGIN
			PATCH_IF SHORT_AT ("%ab_off%" + 0x1E) > 1 BEGIN
				GET_OFFSET_ARRAY2 "fx_array" "%ab_off%" SPL_V10_HEAD_EFFECTS
				SET "done_first" = 0
				PHP_EACH "fx_array" AS "fx_ind" => "fx_off" BEGIN
					PATCH_MATCH SHORT_AT "%fx_off%" WITH
						12 WHEN !("%done_first%") BEGIN
							PATCH_MATCH SHORT_AT ("%fx_off%" + 0xA) WITH
								(IDS_OF_SYMBOL ("DMGTYPE" "STUNNING") >> 16) BEGIN END
								(IDS_OF_SYMBOL ("DMGTYPE" "MAGIC") >> 16) BEGIN END
								DEFAULT
									SET "done_first" = 1
									PATCH_IF ("%fx_ind%" != SHORT_AT ("%ab_off%" + 0x1E) - 1) BEGIN
										INNER_ACTION BEGIN
											ACTION_IF ("%DEST_EXT%" STRING_EQUAL_CASE "itm") BEGIN
												OUTER_SET "count_itm" += 1
												APPEND_OUTER "%MOD_FOLDER%/%filename%.txt" "%count_itm%) ~%DEST_FILE%~ => ability #%ab_ind%, position #%fx_ind%" UNLESS "%count_itm%) ~%DEST_FILE%~ => ability #%ab_ind%, position #%fx_ind%"
											END ELSE BEGIN
												OUTER_SET "count_spl" += 1
												APPEND_OUTER "%MOD_FOLDER%/%filename%.txt" "%count_spl%) ~%DEST_FILE%~ => ability #%ab_ind%, position #%fx_ind%" UNLESS "%count_spl%) ~%DEST_FILE%~ => ability #%ab_ind%, position #%fx_ind%"
											END
										END
									END
							END
						END
						DEFAULT
					END
				END
			END
		END
	BUT_ONLY_IF_IT_CHANGES
END
*/